### ISSUE TITLE
NX_X11 is being built without poll() but uses select() instead

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#1000]
While debugging some build issues I saw the following in my build logs:
```
NX_X11 will be built with the following settings:
 Loadable xcursor library support:        yes
 Threading support:                       yes
 Use Threads safe API:                    yes
 Threads stubs in libNX_X11:              no
 USE_POLL:                                no
 XCMS:                                    yes
 Internationalization support:            yes
 XF86BigFont support:                     yes
 XKB support:                             yes
 XLOCALEDIR environment variable support: yes
 Compose table cache enabled:             yes

```
Is it expected that USE_POLL is no or is it better to use poll() than select()?
Do other builds have USE_POLL=yes and I should fix my build configuration?

Thanks,
Simon

**Comment by uli42** [comment]
On Thu, Feb 4, 2021 at 9:51 AM Simon Matter <notifications@github.com>
wrote:

> While debugging some build issues I saw the following in my build logs:
>
> NX_X11 will be built with the following settings:
>  Loadable xcursor library support:        yes
>  Threading support:                       yes
>  Use Threads safe API:                    yes
>  Threads stubs in libNX_X11:              no
>  USE_POLL:                                no
>  XCMS:                                    yes
>  Internationalization support:            yes
>  XF86BigFont support:                     yes
>  XKB support:                             yes
>  XLOCALEDIR environment variable support: yes
>  Compose table cache enabled:             yes
>
>
> Is it expected that USE_POLL is no or is it better to use poll() than
> select()?
> Do other build have USE_POLL=yes and I should fix my build configuration?
>

Congratulations to issue #1000 ;-)

IIRC due to the nx patches to the Xtrans libraries select() must be used -
but I have not checked that thoroughly. But If you want to try that feel
free.

Uli

**Comment by realsimix** [comment]
OK, found it, --disable-poll is explicitly called from the Makefile. So I guess all is well with my builds.

Regards,
Simon
