### ISSUE TITLE
Small display corruptions

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#1019]
I'm seeing small display corruptions in windows where parts of the underlying display are still visible. The corrupt areas are maybe 1-2% of the window size. Doing some mouse movements inside the corrupt window does most of the time redraw the area correctly. It happens with different programs but the easiest to reproduce it is with Firefox.

Needless to say that I'm unable to show the problem since doing a screen dump with `xwd` always produces correct pictures.

System is:
ARM based Pinebook Pro
Manjaro Linux
nxproxy-3.5.99.26

Server side is CentOS 7, nxagent-3.5.99.26.

Other clients with Intel/AMD CPU and different CentOS versions, but same nxproxy-3.5.99.26, don't show any problems.

I don't know how to find the problem but as a start I've compared the X info of the working client to the troubled ARM system. The following differences are obvious and I'm wondering if some of it could lead to the issue I'm seeing:

```
...
-number of extensions:    31
+number of extensions:    28
     BIG-REQUESTS
     Composite
     DAMAGE
     DOUBLE-BUFFER
     DPMS
-    Extended-Visual-Information
+    DRI2
+    DRI3
     GLX
+    Generic Event Extension
     MIT-SCREEN-SAVER
     MIT-SHM
-    MIT-SUNDRY-NONSTANDARD
+    Present
     RANDR
     RECORD
     RENDER
     SECURITY
-    SGI-GLX
     SHAPE
     SYNC
-    TOG-CUP
     X-Resource
-    XC-APPGROUP
     XC-MISC
     XFIXES
-    XFree86-Bigfont
     XFree86-DGA
-    XFree86-Misc
     XFree86-VidModeExtension
     XINERAMA
     XInputExtension
...
-  options:    backing-store NO, save-unders NO
+  options:    backing-store WHEN MAPPED, save-unders NO
...
```

Does anyone have an idea what to try next?

Regards,
Simon

**Comment by uli42** [comment]
- Does it also show if you set gfx.xrender.enabled to true in firefox?
- is this always happening?
- if you are able to reliably replicate the problem you could try running
  ssh -X <server
  nxagent :55 &
  DISPLAY=:55 firefox
and see if the problem persists.
- you could also try to dump the nxagent's internal screen by running
  ssh server
  export DISPLAY=(display id of the nxagent)
  use xclsclients/xwininfo/xwd/whatever
  and check if the dump there is also erroneous.
- run the latest HEAD of nx-libs

Enough ideas? ;-)

Uli

**Comment by realsimix** [comment]
> - Does it also show if you set gfx.xrender.enabled to true in firefox?

Wow, setting `gfx.xrender.enabled` to `true` seems to fix firefox and even making it faster. That's a good hint!

> - is this always happening?

Yes.

> - if you are able to reliably replicate the problem you could try running
>   ssh -X <server
>   nxagent :55 &
>   DISPLAY=:55 firefox
> and see if the problem persists.

The issue doesn't show up in my tests here.

> - you could also try to dump the nxagent's internal screen by running
>   ssh server
>   export DISPLAY=(display id of the nxagent)
>   use xclsclients/xwininfo/xwd/whatever
>   and check if the dump there is also erroneous.

I've checked but the dumps are always fine.

> - run the latest HEAD of nx-libs

Unfortunately I don't have a build environment on ARM for now and only borrowed the binaries from Fedora.

One thing which surprised me is that most programs I tried work fine. What also shows the problem is `gwenview` from KDE or also `kwrite`. Thunderbird also shows the issue as I just found out.

Simon

**Comment by realsimix** [comment]
Well, I've also seen some screen corruption on the base system now so I start to believe there is some deeper problem here not related to NX. On the base system it happened when scrolling through a console that suddenly parts of the underlying screen were visible. Also taking a screenshot was possible here and it shows the partly wrong window content.

One interesting detail: Running the NX session in a window instead of fullscreen makes most of the problem go away.

**Comment by sunweaver** [comment]
> Well, I've also seen some screen corruption on the base system now so I start to believe there is some deeper problem here not related to NX. On the base system it happened when scrolling through a console that suddenly parts of the underlying screen were visible. Also taking a screenshot was possible here and it shows the partly wrong window content.
> 
> One interesting detail: Running the NX session in a window instead of fullscreen makes most of the problem go away.

Is this maybe a display problem on the client computer (and not a problem of the X2Go Server / nxagent session)?

**Comment by realsimix** [comment]
Yes I start to believe the same as I said I saw some screen corruption on the base system as well.

I think it's a problem in Mesa/Panfrost on the RK3399 SOC with its built in Mali-T860 GPU. I found reports of similar issues on the Mesa gitlab tracker and will try a git build of mesa to see if it helps.

I never saw the corruptions until using remote sessions which made me believe it has something to do with nx-libs. Now that I found corruptions outside of the remote sessions it seems like nx-libs is fine and just showed up more of the underlying problem.

**Comment by uli42** [comment]
On Thu, Jun 10, 2021 at 6:00 PM Simon Matter ***@***.***> wrote:
>
> Does it also show if you set gfx.xrender.enabled to true in firefox?
>
> Wow, setting gfx.xrender.enabled to true seems to fix firefox and even making it faster. That's a good hint!

Unfortunately we do not know for how long whe still will have this.
Eventually Firefox will drop it...

> is this always happening?
>
> Yes.

So maybe you can work how to trigger it without firefox, which would
help in tracking in down.

> if you are able to reliably replicate the problem you could try running
> ssh -X <server
> nxagent :55 &
> DISPLAY=:55 firefox
> and see if the problem persists.
>
> The issue doesn't show up in my tests here.


OK, this means, the nx transport or the proxy code might be the culprit.
>
> you could also try to dump the nxagent's internal screen by running
> ssh server
> export DISPLAY=(display id of the nxagent)
> use xclsclients/xwininfo/xwd/whatever
> and check if the dump there is also erroneous.
>
> I've checked but the dumps are always fine.


Points to the same direction as the above.
>
> run the latest HEAD of nx-libs
>
> Unfortunately I don't have a build environment on ARM for now and only borrowed the binaries from Fedora.
>
> One thing which surprised me is that most programs I tried work fine. What also shows the problem is gwenview from KDE or also kwrite.

It solely depends on the graphics operations they are calling.

Uli

**Comment by realsimix** [comment]
> On Thu, Jun 10, 2021 at 6:00 PM Simon Matter ***@***.***> wrote:
>>
>> Does it also show if you set gfx.xrender.enabled to true in firefox?
>>
>> Wow, setting gfx.xrender.enabled to true seems to fix firefox and even
>> making it faster. That's a good hint!
>
> Unfortunately we do not know for how long whe still will have this.
> Eventually Firefox will drop it...

That's sad because it really helps!

>
>> is this always happening?
>>
>> Yes.
>
> So maybe you can work how to trigger it without firefox, which would
> help in tracking in down.
>
>> if you are able to reliably replicate the problem you could try running
>> ssh -X <server
>> nxagent :55 &
>> DISPLAY=:55 firefox
>> and see if the problem persists.
>>
>> The issue doesn't show up in my tests here.
>
>
> OK, this means, the nx transport or the proxy code might be the culprit.
>>
>> you could also try to dump the nxagent's internal screen by running
>> ssh server
>> export DISPLAY=(display id of the nxagent)
>> use xclsclients/xwininfo/xwd/whatever
>> and check if the dump there is also erroneous.
>>
>> I've checked but the dumps are always fine.
>
>
> Points to the same direction as the above.

What I did now is to update mesa to a git version:
Mesa 21.2.0-devel (git-17d7b0bb8f)

With this update, a small error is gone which was when moving a Java
window inside a Java program, it didn't correctly redraw the window
border.

The other problem where some parts of an underlying window are visible in
a window over it are still there. This is in Firefox, Thunderbird,
gwenview and other KDE programs.

I've finally been able to screenshot the issue which can be seen in the
attached file. The black bars usually show the content of the background
window, but not always.

Does it look like an error which could happen in nxagent/nxproxy?

Regards,
Simon

**Comment by realsimix** [comment]
![rk3399-panfrost](https://user-images.githubusercontent.com/31847983/121701532-489a9d00-cad1-11eb-86f5-6dde3704a1b6.png)

**Comment by realsimix** [comment]
I did some tests again and it looks like this:

ssh -X --> Xnest --> XFCE session with Firefox: OK
ssh -X --> nxagent --> XFCE session with Firefox: OK
nxproxy --> nxagent --> XFCE session with Firefox: CORRUPTIONS

Corruptions happens more often when nxagent is in fullscreen mode, but they also happen in smaller windows.

**Comment by realsimix** [comment]
Unfortunately I don't know where to go next to debug this.

Is there any way to find out where the problem is, with nx-libs or the local system?

**Comment by uli42** [comment]
Well, that is a hard one... I never had to debug something like this. The
best way to find out what's causing that is breaking it down somehow. As
you can imagine Firefox will do a gazillion of graphics operations so
finding the broken one is nothing but simple. It would help if you had a
small example program that also triggers the problem.

Maybe this is a caching bug. We could verify by disabling the cache. I must
look first how to do that...

Just to be sure: you are NOT using x2go, right? So how are you starting a
session? What options are you using, what compression algorithm (which
brings up another idea: try to play around with the compression settings.
There's even "none". If that makes a difference we are one step further.)

Uli





Simon Matter ***@***.***> schrieb am Mo., 14. Juni 2021,
13:02:

**Comment by realsimix** [comment]
Hi Uli,

I've tested with settings `LAN` but maybe this still uses lossless compression? I'll investigate.

I also tried to disable GLX and other hardware acceleration stuff on the local X server but with no change.

You're right, we're using our own nxlaunch application to start sessions (not to be confused with some old nxlaunch gui that search engines find).

Basically the tested configuration runs:
Client:
`nxproxy -S nx/nx,nodelay=1,timeout=0,connect=localhost:1685`

Server:
`nxagent -once -dpms -nopersistent -autodpi -display nx/nx,nodelay=1,timeout=0,cache=128M,accept=localhost,link=ADSL:1685 -geometry allscreens -keyboard clone`

Transport is done via SSH.

As you can see, nothing fancy and pretty standard options.

Simon

**Comment by realsimix** [comment]
I've just tried with both options below with no change:

```
cache=0,link=LAN,pack=none
cache=0,link=LOCAL,pack=none-0
```

**Comment by realsimix** [comment]
About how to reproduce: I can also reproduce the problem with Thunderbird but also easily with the KDE program gwenview.

Gwenview starts as a window with gray background. Simply switching the window to fullscreen mode show the errors in the gray background. It looks like some parts are not correctly redrawn. Moving the mouse to another window and then back fixes the errors most of the time.

**Comment by uli42** [comment]
I think you also need to specify images=0 on the nxproxy side and and
it will probably not hurt to also add load=0

**Comment by realsimix** [comment]
Tried with `images=0,load=0` but there is no change.

**Comment by uli42** [comment]
So, what do we know?
- nxproxy is required
- it does not seem to be related to the x-message caching and
therefore not related to the NX differential compression (as you have
specified cache=0 which means "Setting the value to 0 will disable the
memory cache as well as the NX differential compression")
- it does not seem to be related to the image compression (because of
pack=none) or the image cache (because of images=0)

That does not leave us with too many options... Can you please try
- to run "nxagent with -extension GLX"?
- to run nxagent without the allscreen geometry setting?
- with another local window manager? (BTW: what are you using currently?)

Uli

**Comment by realsimix** [comment]
I already tried with GLX disabled in the local X server and it didn't help.
I also tried without geometry setting, switching later to fullscreen and back, without change. As said before, the issue shows up much more in fullscreen mode but I can also reproduce it in window mode.
On the ARM client I'm using KDE and on the server it's XFCE. I also tried with XFCE on the ARM client just to make sure it's not a KDE thing.

But, I finally found something which looks similar to what I see:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4660

Since this is fixed in Mesa/Panfrost HEAD I'll see how I can get it on my box and test it before doing more investigations on the nx-libs side.

Thanks,
Simon

**Comment by uli42** [comment]
On Mon, Jun 14, 2021 at 6:30 PM Simon Matter ***@***.***> wrote:
> I already tried with GLX disabled in the local X server and it didn't help.

Yes, but I asked you to disable GLX in the nxagent.

> I also tried without geometry setting, switching later to fullscreen and back, without change. As said before, the issue shows up much more in fullscreen mode but I can also reproduce it in window mode.
> On the ARM client I'm using KDE and on the server it's XFCE. I also tried with XFCE on the ARM client just to make sure it's not a KDE thing.
>
> But, I finally found something which looks similar to what I see:
>
> https://gitlab.freedesktop.org/mesa/mesa/-/issues/4660
>
> Since this is fixed in Mesa/Panfrost HEAD I'll see how I can get it on my box and test it before doing more investigations on the nx-libs side.

I know Mesa but I don't know what Mesa/Panfrost is. But if is the
driver for your hardware it might worth a try.

Uli

**Comment by realsimix** [comment]
> On Mon, Jun 14, 2021 at 6:30 PM Simon Matter ***@***.***> wrote:
>> I already tried with GLX disabled in the local X server and it didn't
>> help.
>
> Yes, but I asked you to disable GLX in the nxagent.

Oh, sorry, I thought that's the same in the end.

I've tested it now and it doesn't change anything.

>
>> I also tried without geometry setting, switching later to fullscreen and
>> back, without change. As said before, the issue shows up much more in
>> fullscreen mode but I can also reproduce it in window mode.
>> On the ARM client I'm using KDE and on the server it's XFCE. I also
>> tried with XFCE on the ARM client just to make sure it's not a KDE
>> thing.
>>
>> But, I finally found something which looks similar to what I see:
>>
>> https://gitlab.freedesktop.org/mesa/mesa/-/issues/4660
>>
>> Since this is fixed in Mesa/Panfrost HEAD I'll see how I can get it on
>> my box and test it before doing more investigations on the nx-libs side.
>
> I know Mesa but I don't know what Mesa/Panfrost is. But if is the
> driver for your hardware it might worth a try.

I have yet to understand this too. From what I understand Panfrost is the
driver/code which runs on the GPU and provides all the graphics
functionality which only works trough Mesa. Therefore Mesa includes all
the hardware drivers and updating Mesa updates the hardware drivers as
well. At least that's how things are packaged here on Manjaro Linux.

Simon

**Comment by realsimix** [comment]
As mentioned above, this has been a problem in the GPU code of the used hardware and has been fixed there:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4928

There is nothing wrong with nx-libs here, it's just that the errors only showed up when using nx-libs based sessions.

Thanks for all your help debugging this issue.

Regards,
Simon

**Comment by uli42** [comment]
glad to hear that!
