### ISSUE TITLE
/tmp/.X11-unix must be owned by root

### ISSUE THREAD

**Issue by mviereck** [ArcticaProject/nx-libs#1034]
Hello,

I have a quite special setup where `/tmp/.X11-unix` is created by a non-privileged user.
Starting `nxagent` (as a standalone X server for [x11docker](https://github.com/mviereck/x11docker)) results in error:
```
_XSERVTransmkdir: ERROR: Owner of /tmp/.X11-unix must be set to root
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 1
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
```
So nxagent does not create an X unix socket.
Other X servers work well with this folder. Some print a message, but do not fail.

Is it possible to change the error to a harmless message, so nxagent creates the unix socket nonetheless?

**Comment by uli42** [comment]
Iirc the problem is, that this dir must be accessible by all users.
Otherwise there is no way to run multiple nx sessions. So the recommended
setup is to create the dir at system startup.

Uli

mviereck ***@***.***> schrieb am Fr., 14. Jan. 2022, 20:20:

**Comment by mviereck** [comment]
Thank you for your response!
I tried with access for everyone (777 and 1777), but nxagent still failed and insists that the folder must be owned by root.

In my setup it is difficult to provide a root owned folder. nxagent runs in an unprivileged Docker container and gets an unprivileged folder from host for the unix socket. This in turn is shared with another container.
I have some other X servers for this setup, but would like to support nxagent, too. 

nxagent running on host is already used by several x11docker users. 
A new feature that I currently develop provides X servers running in unprivileged containers.

If you could fix this, it would be great. Basically it is just a permission check of `/tmp/.X11-unix` that should not cause nxagent to deny creating a socket.

**Comment by uli42** [comment]
These messages are no special NX code AFAIR, they come from libxtrans. I
must check how other x servers handle that case.

Uli
mviereck ***@***.***> schrieb am So., 16. Jan. 2022, 21:52:

**Comment by uli42** [comment]
Compiling without FAIL_HARD would fix this. This can be achieved like this:

make IMAKE_DEFINES="-DXtransFailSoft=YES"

Nevertheless I don't want to change the default as for normal
environments it really should stay as it currently is. Can you live
with that?

Uli

**Comment by mviereck** [comment]
Thank you very much for figuring that out!

> Can you live with that?

Basically yes; because I provide nxagent in a docker image, I can build nxagent myself during image creation.
I just have to try to build from source. I'll try the build instructions from README.md.

**Comment by mviereck** [comment]
Success! Thanks again!

If of interest, the `Dockerfile` code to compile nxagent with the patch:
```
RUN echo "deb-src http://deb.debian.org/debian bullseye main" >> /etc/apt/sources.list && \
    apt-get update && \
    installpackages="dpkg-dev devscripts $(apt-get build-dep --dry-run nxagent | grep "Inst " | awk '{print $2}')" && \
    apt-get install -y $installpackages && \
    mkdir /nxbuild && \
    cd /nxbuild && \
    apt-get source nxagent && \
    cd nx-libs-3.5.99.26 && \
    sed -i 's/# define XtransFailSoft NO/# define XtransFailSoft YES/' nx-X11/config/cf/X11.rules && \
    debuild -b -uc -us && \
    cd /nxbuild && \
    cp nxagent*.deb / && \
    rm -R /nxbuild && \
    apt-get remove -y --purge $installpackages && \
    apt-get autoremove -y --purge && \
    apt-get clean
```
This uses the package provided by debian, gets the source with `apt-get source nxagent` and builds it with `debbuild`.
The patch itself is done with:
```
    sed -i 's/# define XtransFailSoft NO/# define XtransFailSoft YES/' nx-X11/config/cf/X11.rules
```
Likely the patch should rather be done in file `debian/rules`, but I was not sure how to do this.
