### ISSUE TITLE
user resources not being read

### ISSUE THREAD

**Issue by Hurgotron** [ArcticaProject/nx-libs#1040]
I noticed that the user resources (ie, $HOME/.Xresources-x2go) are not being read on my new Devuan Chimaera instance (should be the same for Debian stable).

xsession-x2go-errors told me that "has_option" command was not found. Upon investigation, it looks like this command, and reading of the option file Xsession.options, used to be defined in /etc/X11/Xsession.d/20x11-common_process-args, but now resides in /etc/X11/Xsession. /etc/x2go/Xsession is a modified copy of /etc/X11/Xsession, but this change was not made.

Copying the relevant lines over from /etc/X11/Xsession made things work again. Patch attached (please bear with me - I'm a sysadmin, not a developer).

[x2gouserresources.txt](https://github.com/ArcticaProject/nx-libs/files/8103219/x2gouserresources.txt)

**Comment by uli42** [comment]
This is a x2go bug not an nx-libs bug. Please open it up there: https://bugs.x2go.org/Reporting.html

Although it may look like arctica and x2go are the same project or run by the same people this is not always the case. I for myself have not much insight into the x2go source or release plans.  I also cannot merge patches or make a release.

Closing here.
