### ISSUE TITLE
compiling nx-libs on OpenBSD -- missing OpenBSD.cf

### ISSUE THREAD

**Issue by sandeep-gh** [ArcticaProject/nx-libs#1043]
I simply cloned this repo, changed the bash path in Makefile and ran gmake. 
The compile fails with error:
```
In file included from Imakefile.c:17:2:
./config/cf/Imake.tmpl:102:2: Include file OpenBSD.cf not found
imake: Exit code 1.
```
Question is how to build/obtain OpenBSD.cf. Does one have to write an Imakefile from scratch?

**Comment by sandeep-gh** [comment]
I copied OpenBSD.cf and other related files from /usr/local/lib/X11/config and that seems to satisfy the compiler. Fingers crossed rest works out :).

**Comment by uli42** [comment]
Can you please provide that file so we can include it?

sandeep-gh ***@***.***> schrieb am Do., 24. März 2022, 07:24:

**Comment by sandeep-gh** [comment]
@uli42 , Please find attached imake config files for OpenBSD
[bsd_imake.zip](https://github.com/ArcticaProject/nx-libs/files/8343731/bsd_imake.zip)
