### ISSUE TITLE
Error -  X2Go Desktop Bindings installation

### ISSUE THREAD

**Issue by rafaelrdealmeida** [ArcticaProject/nx-libs#1050]
Hello,

when running X2Go Desktop Bindings installation commands:

```
sudo apt-get install x2gomatebindings  # if you use MATE/mubuntu
sudo apt-get install x2golxdebindings  # if you use LXDE/lubuntu

```

I'm having the following message:

```
E: Unable to find package x2gomatebindings

```

This happens on both ubuntu 20.04 and 22.04 . Any suggestion on how to resolve this?

best

**Comment by uli42** [comment]
Please open a bug at x2go, this is unrelated to nx.
