### ISSUE TITLE
Which repo to use for x2go?

### ISSUE THREAD

**Issue by Yetoo1** [ArcticaProject/nx-libs#1055]
Is this repo incorporating x2go specific fixes or is it standalone? I am unsure which repo to file bugs against or to pull from as the README.md suggests x2go and other developers stopped nx redistribution and ArcticaProject will consolidate efforts to a single place such as this repo. Despite this https://code.x2go.org/nx-libs is currently ahead in some commits and I see no branches here that mirror those. Guidance on this would be appreciated.

**Comment by uli42** [comment]
Well, the idea is that Arctica is the main repo. Normally the x2go repo
clones that from time to time, but I don't know how the package is handled
there.

We should pull newer the commits from there. I have not been aware that
there are newer ones. Normal flow is to add PRs here which has not been
done - for whatever reason.

**Comment by sunweaver** [comment]
@uli42: I have now pulled @Ionic's changes in x2go/nx-libs#master over to gh/nx-libs#3.6.x.

@Yetoo1 Thanks for noticing this...

**Comment by uli42** [comment]
Thanks!  What about the other PRs?

**Comment by sunweaver** [comment]
To answer the original question: This repo, branch 3.6.x is upstream for X2Go. nx-libs code found at code.x2go.org is downstream. @Ionic: you added patches to the master branch which you hadn't upstreamed, so far. Please let's keep this and the X2Go nx-libs repo in sync by adding new changes here first and then pulling the 3.6.x branch downstream. Thanks.

@uli42 I have looked at some other PRs, will continue after #1045 has finished CI and confirmed that all is green again/still.

**Comment by realsimix** [comment]
Distribution packages are usually stuck at version 3.5.99.26, which is quite old.

I was wondering if it wouldn't make sense to do a release version 3.5.99.27 anytime soon?

**Comment by uli42** [comment]
+1

**Comment by Ionic** [comment]
Sorry, I've had to add a few commits to unbreak builds on newer OpenSuSE versions quickly for X2Go. The changes were merely build-related and I had to get nightly builds working. I slacked on pushing them upstream and was thinking of how to do that anyway without having to rebase the X2Go master branch.

**Comment by sunweaver** [comment]
@Ionic: I now (i.e. yesterday) pushed your changes to the 3.6.x branch, nothing should be needed to be rebase.
