### ISSUE TITLE
 run-nxproxy2nxagent* test scripts yield black window

### ISSUE THREAD

**Issue by Yetoo1** [ArcticaProject/nx-libs#1060]
Running each of of the scripts prefixed with run-nxproxy2nxagent and copying and pasting output as requested by output yields an unchanging black x window. I am unsure if this means that the test failed or not.

**Comment by uli42** [comment]
It means, you are successfully running a session with nxproxy connecting to nxagent (but on the same machine). Communication is using the NX protocol.

You an X server in a window. You can display windows there by running `DISPLAY=:<something> xterm`
