### ISSUE TITLE
running evince crashes X2Go session when host is a 64-bit VMware/KVM virtual machine guest

### ISSUE THREAD

**Issue by stefanbaur** [ArcticaProject/nx-libs#107]
Hi,

I have two X2Go hosts running in virtual machines, one is 64-bit, one is 32-bit.

Both are running Debian Jessie.

Here's the output of dpkg -l | grep x2go on the 64-bit host:

ii  libnx-x11-6:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
client-side library
ii  libnx-xcomposite1:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
Composite extension library
ii  libnx-xdamage1:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
damaged region extension library
ii  libnx-xdmcp6:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
Display Manager Control Protocol library
ii  libnx-xext6:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
miscellaneous extension library
ii  libnx-xfixes3:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
miscellaneous 'fixes' extension library
ii  libnx-xinerama1:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
Xinerama extension library
ii  libnx-xpm4:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
pixmap library
ii  libnx-xrandr2:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
RandR extension library
ii  libnx-xrender1:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
Rendering Extension client library
ii  libnx-xtst6:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
Testing -- Record extension library
ii  libxcomp3:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
compression library
ii  libxcompext3:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
protocol compression extensions library
ii  libxcompshad3:amd64
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        nx-X11
shadowing library
ii  nx-x11-common
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 all          nx-X11
(common files)
ii  nxagent
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        NX agent
ii  nxproxy
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 amd64        NX proxy
ii  x2go-keyring
2012.07.23~jessie~main~17~build1                all          GnuPG keys
of all X2Go developers and the X2Go archive
ii  x2goagent
2:3.5.0.32-0x2go1+git20160126.734+jessie.main.1 all          X2Go agent
ii  x2goclient
4.0.5.1-0x2go1+git20160324.1180+jessie.main.1   amd64        X2Go Client
application (Qt4)
ii  x2goserver
4.0.1.19-0x2go2+git20160126.1064+jessie.main.1  amd64        X2Go server
daemon scripts
ii  x2goserver-extensions
4.0.1.19-0x2go2+git20160126.1064+jessie.main.1  all          X2Go server
daemon scripts (extensions)
ii  x2goserver-xsession
4.0.1.19-0x2go2+git20160126.1064+jessie.main.1  all          X2Go server
daemon scripts (Xsession runner)

Here is the output of dpkg -l | grep evince on the 64-bit host.
ii  evince-common                         3.14.1-2
                  all          Document (PostScript, PDF) viewer -
common files
ii  evince-gtk                            3.14.1-2
                  amd64        Document (PostScript, PDF) viewer (GTK+
version)

I've tried connecting with X2GoClient  4.0.5.1-0x2go1+git20160324.1180+jessie.main.1 from Linux
clients, both 32-bit and 64-bit.

I've also tried the Windows X2GoClient, 4.0.5.0-2015-07-31, on an x64
Windows 7 (the client is a 32-bit application, though).

The result is always the same:
As soon as I try to start evince in published application mode, either
directly from the menu, or via an xterm and typing "evince" there, or by
specifying evince as the single application to run rather than a
published application session, the X2Go session crashes immediately - IF
the host is a 64-bit system running as virtual machine guest in either
VMware Workstation or KVM.

It does not crash IF:
- The host is a 64-bit Linux-VServer instance.
- The host is a 32-bit virtual machine guest in VMware WS or KVM.
- The connection is made using ssh -X rather than X2Go.
- The connection is made using an X2Go connection to a desktop
  environment like LXDE, from which evince is then started.

I am attaching the output of "strace evince >$LOGNAME 2>&1" for one
successful connection (to the 32-bit host) and for three crashes (to the
64-bit host).

Kind Regards,
Stefan Baur
## 

BAUR-ITCS UG (haftungsbeschränkt)
Geschäftsführer: Stefan Baur
Eichenäckerweg 10, 89081 Ulm | Registergericht Ulm, HRB 724364
Fon/Fax 0731 40 34 66-36/-35 | USt-IdNr.: DE268653243

[evince-trace-from-jessie-amd64-client-to-64-bit-host_crash.txt](https://github.com/ArcticaProject/nx-libs/files/194165/evince-trace-from-jessie-amd64-client-to-64-bit-host_crash.txt)
[evince-trace-from-jessie-x86-client-to-64-bit-host_crash.txt](https://github.com/ArcticaProject/nx-libs/files/194166/evince-trace-from-jessie-x86-client-to-64-bit-host_crash.txt)
[evince-trace-from-windows-to-32bit-host_works_fine.txt](https://github.com/ArcticaProject/nx-libs/files/194167/evince-trace-from-windows-to-32bit-host_works_fine.txt)
[evince-trace-from-windows-to-64-bit-host_crash.txt](https://github.com/ArcticaProject/nx-libs/files/194168/evince-trace-from-windows-to-64-bit-host_crash.txt)

**Comment by sunweaver** [comment]
@stefanbaur: can you retest the above issue once nxagent 3.5.99.14 has been released (before the week is over)?

**Comment by stefanbaur** [comment]
I'm not quite sure if it was the same issue I had with Icedove/Thunderbird a while later; the latter one was fixed by setting
X2GO_NXAGENT_DEFAULT_OPTIONS+=" -extension BIG-REQUESTS"
in 
/etc/x2go/x2goagent.options

So to test it again I would have to install a new test system, switch it to heuler or the arctica repo, I guess, and run these tests ... unlikely to happen in the next 3-4 weeks, due to family issues.
Sorry. If it's still helpful if I do these tests in 4 weeks or later, feel free to ping me again then.

**Comment by sunweaver** [comment]
On  Di 27 Feb 2018 10:14:04 CET, Stefan Baur wrote:

> I'm not quite sure if it was the same issue I had with  
> Icedove/Thunderbird a while later; the latter one was fixed by setting
> X2GO_NXAGENT_DEFAULT_OPTIONS+=" -extension BIG-REQUESTS"
> in
> /etc/x2go/x2goagent.options
>
> So to test it again I would have to install a new test system,  
> switch it to heuler or the arctica repo, I guess, and run these  
> tests ... unlikely to happen in the next 3-4 weeks, due to family  
> issues.
> Sorry. If it's still helpful if I do these tests in 4 weeks or  
> later, feel free to ping me again then.

This should really be made the default in x2goserver-x2goagent's  
x2goagent.options:

X2GO_NXAGENT_DEFAULT_OPTIONS+="-extension BIG-REQUESTS"

As big requests are currently really broken in nxcomp [1].

Mike

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766299  
(currently closed by mistake)

-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
as BIG-REQUESTS are no longer broken I assume this can be closed. @stefanbaur  can you still see these crashes nowadays?
