### ISSUE TITLE
nxagent a) hangs for long periods when no client b) overly strict about reconnection

### ISSUE THREAD

**Issue by mbecroft** [ArcticaProject/nx-libs#132]
a) Currently, nxagent has deliberate delays inserted in several places when no client is connected. This is clearly designed to mitigate things like Flash web sites hogging the CPU when no user is connected to a session. However it has the following (and probably other) unintended side-effects:
- Depending on the system configuration, the long delays in responding to X protocol requests can lead to buffers filling up and ssh sessions becoming unresponsive or disconnected while the user is disconnected.
- It is impossible to use a client such as x11vnc to access the nxagent's display while the user is disconnected.
- Unexpected behaviour with any X client software displaying on multiple displays, when the user is disconnected. Example, start emacs in nxagent. make-frame-on display <some other display>. Disconnect from your nxagent session. emacs may become unresponsive even on the non-nxagent display.
- Unexpected behaviour from any X11 client software that has any other semi-real-time I/O requirements (processing, writing log files etc.) while a user is logged out from the nxagent session.

b) Currently, nxagent is excessively pedantic about the displays it will allow itself to be reconnected to. This has even resulted in the situation where it became impossible to reconnect to an nxagent from the original workstation from which it was created! Some of the checks being carried out are necessary, but some of them definitely appear to serve no purpose. Another very silly example is that nxagent refuses to reconnect to an X server that has _more_ pixmap depths than were available on the server where it was created. All of the server capability checks on reconnection need thorough review.

**Comment by mbecroft** [comment]
The attached patch is hack workaround for these issues that got things going for me. use it only as a template to find the relevant sections of code requiring attention.

_I have done:_

a) comment out all deliberate delays in response to X protocol requests with `#ifdef MARIO_ENABLE`

b) Short-circuit several dubious compatibility checks by adding `return 1` (meaning "target X server is compatible") near the top.

_To be done:_

a) replace all instances of deliberate delays in response to nxagent client X protocol requests with a configurable delay (rather than the current fixed delay), and if that delay is configured to 0, then do not even call `usleep()` at all.

b) Closely evaluate the purpose and need of all the reconnection checks and rework these to correctly identify the scenarios where: 1) reconnection can be allowed with no caveats 2) reconnection can be allowed but some resources might not be available leading to non-fatal consequences (e.g. a pixmap depth is not available, but no client is using it), 3) reconnection cannot proceed because to do so would definitely fail immediately.

[nx-delay-reconnect.diff.txt](https://github.com/ArcticaProject/nx-libs/files/294845/nx-delay-reconnect.diff.txt)

**Comment by sunweaver** [comment]
@mbecroft: I assigned Ionic to working on this in the coming week(s).

**Comment by Ionic** [comment]
a.) has been implemented in [feature/configurablesleep branch in Ionic/nx-libs](/Ionic/nx-libs/tree/feature/configurablesleep).

**Comment by sunweaver** [comment]
@Ionic: looks good to me. Please file a PR for that portion of @mbrecroft's proposal. Thanks.

**Comment by Ionic** [comment]
Referencing #143.

**Comment by Ionic** [comment]
Btw, I haven't tested x11vnc, but instead made short tests with a session running `fluxbox`, `urxvt` and `glxgears`. While the framerate was always more or less stable whenever `nxproxy` was connected, the `sleep` option caused following effects:
- when set to 0: a higher FPS rate in suspended state (probably because `nxagent` can run "unbounded" in this case and is not limited by network traffic to the remote proxy)
- decreasing rates with sleep rates higher than 0 (tested with 10, 50, 100)
- at very high rates (especially seen with `UINT_MAX` values while testing the parsing and squashing bugs related to input handling), `nxagent` was (naturally) mostly unusable as waiting for ~4 billion milliseconds every few calls would suggest...
