### ISSUE TITLE
libNX_X11 XErrorDB is missing RANDR 1.3-1.5 stuff

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#153]
See this commit: https://cgit.freedesktop.org/xorg/lib/libX11/commit/src?id=90ef36f6336068183bf9d13ca972202db35b1202

These (and similar commits) are missing in nx-X11/lib/X11/XErrorDB. 

Does this file need to be extended because of the RANDR 1.5 backport? If not: can we remove it?

**Comment by uli42** [comment]
my libNX_X11.so points to a location for the ErrorDB file that does not exist:

```
$ strings /usr/lib/x86_64-linux-gnu/libNX_X11.so.6 | grep -i errordb
/usr/local/lib/nx/X11/XErrorDB
$ ls -l /usr/local/lib/nx/X11/XErrorDB
ls: Zugriff auf /usr/local/lib/nx/X11/XErrorDB nicht möglich: Datei oder Verzeichnis nicht gefunden
```

So either we should ship this file or point to the one from the system. Or get completely rid of it including every function calling it.

**Comment by sunweaver** [comment]
I'd say we should ship it and it should be copied over from latest X.Org. Or we should even point at latest X.org's version of the XerrorDB file.

Our libNX_X11 has to speak to recent X.org servers and should know about all recent error codes.

**Comment by uli42** [comment]
We should find a way to change the path to the system version

**Comment by sunweaver** [comment]
libx11-data: /usr/share/X11/XErrorDB

**Comment by sunweaver** [comment]
We need to fix it here: nx-X11/lib/X11/ErrDes.c:#define ERRORDB "/usr/lib/X11/XErrorDB", I guess.

**Comment by sunweaver** [comment]
and clean it up here:

```
lib/X11/Imakefile:     EDB_DEFINES = -DERRORDB=\"$(LIBDIR)/XErrorDB\"
lib/X11/Imakefile:InstallNonExecFile(XErrorDB,$(LIBDIR))
```

**Comment by sunweaver** [comment]
Simply run a grep on nx-X11/ to find references... I can file a PR for this tomorrow.
