### ISSUE TITLE
backport lots of libX11 fixes beginning ~2006 to libNX_X11

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#157]

**Comment by sunweaver** [comment]
@uli42: Can you take a look into this?

**Comment by uli42** [comment]
Yes, I will
Am 26.06.2016 00:38 schrieb "Mike Gabriel" notifications@github.com:

**Comment by sunweaver** [comment]
@uli42: do you already have a branch with libNX_X11 backports?

**Comment by uli42** [comment]
Yes, but not pushed yet. Maybe this afternoon.

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎23.‎08.‎2016 17:51
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Cc: "Ulrich Sibiller" uli42@gmx.de; "Mention" mention@noreply.github.com
Betreff: Re: [ArcticaProject/nx-libs] backport lots of libX11 fixes beginning~2006 to libNX_X11 (#157)

@uli42: do you already have a branch with libNX_X11 backports?

**Comment by sunweaver** [comment]
This issue will be closed by PR #195, the "merger" shall close this issue with the Git merge of PR #195.

**Comment by uli42** [comment]
Well, #195 updates libX11 to 1.3.4 (from  2010), so there are some
more years left. We can skip the XCB patches for now, but there might
be others as well, I have not checked yet
