### ISSUE TITLE
libX11 segfault when resizing x2go session window

### ISSUE THREAD

**Issue by HolySephi** [ArcticaProject/nx-libs#162]
Server O/S: Ubuntu 14.04

x2goserver version: 4.1.0.0-0~1315~ubuntu14.04.1
nxagent version: 3.5.99.0-0~git20160625.1249+t

Client O/S: Windows 10
X2Goclient Version: 4.0.5.1

Maybe related to #161 

> x2goagent[27755]: segfault at 0 ip 00007f2017001dbb sp 00007fff7cba6320 error 4 in libX11.so.6.3.0[7f2016fc6000+130000]

x2goagent segfaults in libX11.so.6.3.0 when resizing the x2go session window - happens more likely when running ANY application within the desktop like Thunar, Firefox or xterm. Just resizing the desktop (XFCE) results in nxagent segfault described in #161 

Steps to reproduce:
- Connect to the x2goserver as a normal windows (800x600) with XFCE as session
- start any program like Thunar or Firefox
- resize the x2goclient session window a few times - most of the time the segfault occurs on the first resizing attempt.

I am unable to reproduce this with a plain "nxagent :1" service and starting xfce4-session manually - it occurs only with x2goclient.

**Comment by HolySephi** [comment]
~~As stated in #161 i'm unable to reproduce the segfault without the xinerama code (-rrxinerama)~~

Edit: wrong - it just took longer this time - sorry!

**Comment by uli42** [comment]
I can reproduce this with an lxde session, even with a standalone agent: `nxagent -ac :55`. It works when I specify `-norender` in addition. Does this help for you, too?

**Comment by sunweaver** [comment]
@uli42: https://github.com/sunweaver/nx-libs/commit/fd1af6d1288562065e44646e686c2038e8b291ce

**Comment by sunweaver** [comment]
Also closing, same reasoning as given in #163.
