### ISSUE TITLE
Fix/Adapt header guard defines in include files

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#174]
Upstream has prepended  `_X11_` to the header guards (e.g. https://cgit.freedesktop.org/xorg/lib/libX11/commit/include/X11/Xlib.h?id=d0cbf388919364fe6b5b9127f36426eb744090a0). Since we are using more and system libs and includes instead of our own conflicts occur when headers from both worlds are included (which happens indirectly by headers including other headers). Therefore we should use the same header guards.

**Comment by sunweaver** [comment]
@uli42: Will this issue be (fully) closed by any of the commits in PR #195? If so, please close this bug in the specific commit (by adding: Fixes ArcticaProject/nx-libs#174). Thanks.

**Comment by uli42** [comment]
I think so, but will check again.

**Comment by sunweaver** [comment]
Fixed by ef5565f8ed86f05ca20ff1bfc5892fb8a2c557bc. Thus, closing this issue.
