### ISSUE TITLE
general Makefile is missing

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#185]
now:

```
nx-libs$ ls -l
insgesamt 72
drwxrwxr-x 7 uli uli  4096 Jul  9 12:09 debian
drwxrwxr-x 2 uli uli 12288 Jul  9 12:09 nxcomp
drwxrwxr-x 2 uli uli  4096 Jul  9 12:09 nxcompext
drwxrwxr-x 2 uli uli  4096 Jul  9 12:09 nxcompshad
-rw-rw-r-- 1 uli uli 39791 Jul  9 12:09 nx-libs.spec
drwxrwxr-x 2 uli uli  4096 Jul  9 12:09 nxproxy
drwxrwxr-x 9 uli uli  4096 Jul  9 12:09 nx-X11
```

before:

```
nx-libs$ ls -l
insgesamt 348
drwxrwxr-x 2 uli uli   4096 Jul  7 00:48 bin
-rw-rw-r-- 1 uli uli 197814 Jul  7 00:48 ChangeLog
-rw-rw-r-- 1 uli uli  17987 Jul  7 00:48 COPYING
drwxrwxr-x 6 uli uli   4096 Jul  9 00:51 debian
drwxrwxr-x 7 uli uli   4096 Jul  7 00:48 doc
drwxrwxr-x 2 uli uli   4096 Jul  7 00:48 etc
-rwxrwxr-x 1 uli uli    114 Jul  7 00:48 fix-patch-whitespace
-rw-rw-r-- 1 uli uli   1509 Jul  7 00:48 LICENSE
-rw-rw-r-- 1 uli uli   4506 Jul  7 00:48 LICENSE.nxcomp
-rwxrwxr-x 1 uli uli    109 Jul  7 00:48 make-changelog.sh
-rw-rw-r-- 1 uli uli   7175 Jul  7 00:48 Makefile
drwxrwxr-x 3 uli uli  20480 Jul  9 01:20 nxcomp
drwxrwxr-x 3 uli uli   4096 Jul  9 01:22 nxcompext
drwxrwxr-x 4 uli uli   4096 Jul  9 01:22 nxcompshad
-rw-rw-r-- 1 uli uli  20471 Jul  7 00:48 nx-libs.spec
drwxrwxr-x 4 uli uli   4096 Jul  9 01:27 nxproxy
drwxrwxr-x 8 uli uli   4096 Jul  7 01:05 nx-X11
-rw-rw-r-- 1 uli uli   5508 Jul  7 00:48 README.md
lrwxrwxrwx 1 uli uli      9 Jul  7 00:48 README.NX-development -> README.md
-rw-rw-r-- 1 uli uli   1304 Jul  7 00:48 replace.sh
-rwxrwxr-x 1 uli uli   4916 Jul  7 00:48 roll-tarballs.sh
drwxrwxr-x 2 uli uli   4096 Jul  7 00:48 testscripts
-rw-rw-r-- 1 uli uli      9 Jul  7 00:48 VERSION
-rwxrwxr-x 1 uli uli   1159 Jul  7 00:48 version.sh
```

For my tests I was simply calling `make` in the nx-libs dir. The corresponding Makefile is missing now. Is this on purpose? What is the easiest way to build everything now?

**Comment by sunweaver** [comment]
Hi Uli,

On Sat Jul 9 12:14:58 2016 GMT+0200, Ulrich Sibiller wrote:

> now: 
> nx-libs$ ls
> debian  nxcomp  nxcompext  nxcompshad  nx-libs.spec  nxproxy  nx-X11
> 
> before: 
> nx-libs$ ls
> bin        COPYING  doc  fix-patch-whitespace  LICENSE.nxcomp     Makefile  nxcompext   nx-libs.spec  nx-X11     README.NX-development  roll-tarballs.sh  VERSION
> ChangeLog  debian   etc  LICENSE               make-changelog.sh  nxcomp    nxcompshad  nxproxy       README.md  replace.sh             testscripts       version.sh
> 
> For my tests I was simply calling make in the nx-libs dir. The corresponding Makefile is missing now. Is this on purpose? What is the easiest way to build everything now? 

Sounds like you are on the 3.5.0.x branch...

Mike

## 

Sent from my Jolla

**Comment by uli42** [comment]
Doh! - you are right - I forgot to checkout the right branch. Is there a way to annihilate a ticket without traces????
