### ISSUE TITLE
update debian/copyright.in

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#188]
The files in there are no longer in sync with the files we ship.

I have addressed this partly in https://github.com/ArcticaProject/nx-libs/pull/187

**Comment by sunweaver** [comment]
This is basically a duplicate of #2.

Please note, debian/copyright.in is machine generated and I plan doing that before the final 3.6.x release. (Of course, I can update the file for every release). But finalizing the actual debian/copyright will be painful and done before 3.6.0 at the end of August.

Say this, please undo the changes manually done on debian/copyright.in in PR #187.

**Comment by uli42** [comment]
done
