### ISSUE TITLE
remove nomachine reference

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#190]
nxcomp/Loop.cpp contains reference to nomachine:

```
    cerr << "Warning" << ": Consider checking http://www.nomachine.com/ for updates.\n";
```

Should be changed...

**Comment by sunweaver** [comment]
@uli42: good catch, will fix that wit a non-PR push...

**Comment by sunweaver** [comment]
Fixed by https://github.com/ArcticaProject/nx-libs/commit/ed5d920f6659d990408909c4195f4965955b5251. Thus closing (the commit message had a flaw in the "fixes"-statement).
