### ISSUE TITLE
RPM FTBFS: imake: Command not found

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#202]
I am attempting to build 3.5.99.1 on Fedora 23 with the included .spec file.

I am getting this output:
make[2]: Entering directory '/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make -w xmakefile
make[3]: Entering directory '/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11'
imake -I./config/cf  -s xmakefile -DTOPDIR=. -DCURDIR=.
Makefile:76: recipe for target 'xmakefile' failed
make[3]: Leaving directory '/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11'
make[3]: imake: Command not found

[Complete log](http://pastebin.com/w2CdTJwD)

**Comment by uli42** [comment]
You need to install imake. 

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike DePaulo" notifications@github.com
Gesendet: ‎24.‎09.‎2016 17:46
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Betreff: [ArcticaProject/nx-libs] RPM FTBFS: imake: Command not found (#202)

I am attempting to build 3.5.99.1 on Fedora 23 with the included .spec file.
I am getting this output:
make[2]: Entering directory '/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11'
make[2]: warning: jobserver unavailable: using -j1. Add '+' to parent make rule.
make -w xmakefile
make[3]: Entering directory '/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11'
imake -I./config/cf -s xmakefile -DTOPDIR=. -DCURDIR=.
Makefile:76: recipe for target 'xmakefile' failed
make[3]: Leaving directory '/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11'
make[3]: imake: Command not found
Complete log

**Comment by sunweaver** [comment]
@mikedep333: I you add

```
BuildRequires: imake
```

To the top section of the .spec file, does that fix the FTBFS? 

Mike

**Comment by mikedep333** [comment]
That fixes it. The entire F23 build was successful. I will submit a PR shortly.

Also, that should fix it for every RPM-based distro; [they seem to all use the package name "imake".](https://pkgs.org/search/imake)
