### ISSUE TITLE
3.5.99.1 FTBFS on EPEL6

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#204]
After applying the fix for #202, I am getting these errors when attempting to build on the oldest Red Hat family release I tried, EPEL6:

In file included from Screen.c:88:
X11/include/Xrandr_nxagent.h:59: error: redefinition of typedef 'RRProvider'
../../randr/randrstr.h:70: note: previous declaration of 'RRProvider' was here
X11/include/Xrandr_nxagent.h:60: error: redefinition of typedef 'RRMode'
../../randr/randrstr.h:67: note: previous declaration of 'RRMode' was here
make[7]: **\* [Screen.o] Error 1
make[7]: Leaving directory `/builddir/build/BUILD/nx-libs-3.5.99.1/nx-X11/programs/Xserver/hw/nxagent'
make[6]: **\* [hw/nxagent] Error 2

[Full log](https://copr-be.cloud.fedoraproject.org/results/mikedep333/nx-libs-3.6/epel-6-x86_64/00457506-nx-libs/build.log.gz)

Compare to [the successful EPEL7 build log.](https://copr-be.cloud.fedoraproject.org/results/mikedep333/nx-libs-3.6/epel-7-x86_64/00457506-nx-libs/build.log.gz)

**Comment by uli42** [comment]
Does it work when you undo the fix for #200 ?

**Comment by uli42** [comment]
I cannot reproduce this on CentOS 6.7. When simply running `make` in the repo base dir it is compiling fine.

When I use `rpmbuild -ta` I get this:

```
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id /home/usibill/rpmbuild/BUILD/nx-libs-3.5.99.1
extracting debug info from /home/usibill/rpmbuild/BUILDROOT/nx-libs-3.5.99.1-0.0build1.el6.x86_64/usr/lib64/libXcomp.so.3.5.99.1
*** ERROR: No build ID note found in /home/usibill/rpmbuild/BUILDROOT/nx-libs-3.5.99.1-0.0build1.el6.x86_64/usr/lib64/libXcomp.so.3.5.99.1
Fehler: Fehler-Status beim Beenden von /home/usibill/rpmbuild/tmp/rpm-tmp.9Err05 (%install)


Fehler beim Bauen des RPM:
    Fehler-Status beim Beenden von /home/usibill/rpmbuild/tmp/rpm-tmp.9Err05 (%install)
```

According to [this posting](https://www.redhat.com/archives/fedora-packaging/2008-June/msg00011.html) we should extend the spec file.

**Comment by sunweaver** [comment]
On  Mo 26 Sep 2016 11:50:54 CEST, Ulrich Sibiller wrote:

> I cannot reproduce this on CentOS 6.7 when simply running `make` in  
> the repo base dir.
> 
> When I use rpmbuild -ta I get this:
> 
> ```
> + /usr/lib/rpm/find-debuginfo.sh --strict-build-id  
> /home/usibill/rpmbuild/BUILD/nx-libs-3.5.99.1
> extracting debug info from  
> /home/usibill/rpmbuild/BUILDROOT/nx-libs-3.5.99.1-0.0build1.el6.x86_64/usr/lib64/libXcomp.so.3.5.99.1
> *** ERROR: No build ID note found in  
> /home/usibill/rpmbuild/BUILDROOT/nx-libs-3.5.99.1-0.0build1.el6.x86_64/usr/lib64/libXcomp.so.3.5.99.1
> Fehler: Fehler-Status beim Beenden von  
> /home/usibill/rpmbuild/tmp/rpm-tmp.9Err05 (%install)
> 
> 
> Fehler beim Bauen des RPM:
>     Fehler-Status beim Beenden von  
> /home/usibill/rpmbuild/tmp/rpm-tmp.9Err05 (%install)
> ```
> 
> According to [this  
> posting](https://www.redhat.com/archives/fedora-packaging/2008-June/msg00011.html) we should extend the spec  
> file.

Looks good to me. Please propose a (tested) PR.

Thanks,

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Strangely I cannot reproduce my problem. Instead I see the initial problem. The fix is to remove this line from `nx-X11/programs/Xserver/hw/nxagent/Screen.c`:

```
#include "X11/include/Xrandr_nxagent.h"
```

However, I must check again why this problem does not show on Ubuntu.

**Comment by uli42** [comment]
This error does not happen in Ubuntu 14.04 with gcc 4.8.4 while it happens with RHEL6's gcc 4.4.7

According to
https://bugzilla.redhat.com/show_bug.cgi?id=767538

this duplicate typedef is not allowed in C89 and C99 but newer gccs have an extension allowing it for identical typedefs. I can see that error on Ubuntu, too, when running `gcc -Wpedantic` 

While removing the include line (see previous comment) helps in this case we should really avoid the duplicate typedef somehow (without changing files coming from upstream). Any suggestions?
