### ISSUE TITLE
randrproto.h references X11/ not nx-X11 - why?

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#205]
nx-X11/include/extensions/randrproto.h includes randr.h - but from the X11 namespace, not the nx-X11 namespace. #200 changed behaviour regarding X11/.. paths and we have randr.h in the nx-X11 namespace, too and that one will be taken now.

So the question arises: Is that a bug/mistake/flaw or is this on purpose?

`#include <X11/extensions/randr.h>`

**Comment by sunweaver** [comment]
On  Mo 26 Sep 2016 10:53:45 CEST, Ulrich Sibiller wrote:

> nx-X11/include/extensions/randrproto.h includes randr.h - but from  
> the X11 namespace, not the nx-X11 namespace. #200 changed behaviour  
> regarding X11/.. paths and we have randr.h in the nx-X11 namespace,  
> too and that one will be taken now.
> 
> So the question arises: Is that a bug/mistake/flaw or is this on purpose?
> 
> `#include <X11/extensions/randr.h>`

I'll need to look into this in detail. I'll get back to you with some  
thought the coming week.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Same for `nx-X11/include/extensions/damageproto.h`

```
#include <X11/Xmd.h>
#include <X11/extensions/xfixesproto.h>
#include <X11/extensions/damagewire.h>
```
