### ISSUE TITLE
nxproxy host argument parsing is broken

### ISSUE THREAD

**Issue by vatral** [ArcticaProject/nx-libs#207]
Revision c6e95651  appears to have introduced the change.

This commandline used to work, but now throws an error:

```
 /usr/bin/nxproxy -S localhost:40

Loop: PANIC! Error in environment option 'localhost'. No value found.
Error: Error in environment option 'localhost'. No value found.
```

**Comment by sunweaver** [comment]
On  Mo 26 Sep 2016 13:06:44 CEST, Vadim Troshchinskiy wrote:

> Revision c6e95651  appears to have introduced the change.
> 
> This commandline used to work, but now throws an error:
> 
> ```
>  /usr/bin/nxproxy -S localhost:40
> 
> Loop: PANIC! Error in environment option 'localhost'. No value found.
> Error: Error in environment option 'localhost'. No value found.
> ```

I'll look into this the coming week. Thanks for discovering it and  
reporting it.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
