### ISSUE TITLE
Security advisory from X.org

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#213]
https://lists.freedesktop.org/archives/xorg/2016-October/058344.html

Thanks to our cleanup efforts we are only (directly) affected by one of the mentioned problems (in libX11) and should apply the corresponding fix.

**Comment by sunweaver** [comment]
@uli42: can you add fixing this issue to your list? Thanks.

**Comment by uli42** [comment]
```
libX11 - insufficient validation of data from the X server
     can cause out of boundary memory read (XGetImage())
     or write (XListFonts()).
     Affected versions libX11 <= 1.6.3
```

-> we are at 1.6.4
