### ISSUE TITLE
Fix "‘XKeycodeToKeysym’ is deprecated"

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#229]
There are several places in hw/nxagent that warn about a deprecated function call:

```
Events.c: In function ‘nxagentDispatchEvents’:
Events.c:1104:9: warning: ‘XKeycodeToKeysym’ is deprecated (declared at ../../../../exports/include/nx-X11/Xlib.h:1688) [-Wdeprecated-declarations]
         keysym = XKeycodeToKeysym(nxagentDisplay, X.xkey.keycode, 0);
         ^
Keystroke.c: In function ‘find_keystroke’:
Keystroke.c:409:3: warning: ‘XKeycodeToKeysym’ is deprecated (declared at ../../../../exports/include/nx-X11/Xlib.h:1688) [-Wdeprecated-declarations]
   KeySym keysym = XKeycodeToKeysym(nxagentDisplay, X->keycode, 0);
   ^
Keystroke.c: In function ‘nxagentCheckSpecialKeystroke’:
Keystroke.c:443:3: warning: ‘XKeycodeToKeysym’ is deprecated (declared at ../../../../exports/include/nx-X11/Xlib.h:1688) [-Wdeprecated-declarations]
   sym = XKeycodeToKeysym(nxagentDisplay, X -> keycode, index);
   ^
```

According to http://stackoverflow.com/questions/9838385/replace-of-xkeycodetokeysym these calls should be replaced by `XkbKeycodeToKeysym`.

**Comment by uli42** [comment]
Not sure that my previous changes are correct, since Jeremy Huddleston mentions XGetKeyboardMapping, not XkbKeycodeToKeysym: https://lists.freedesktop.org/archives/xorg-devel/2011-October/026193.html

**Comment by uli42** [comment]
I have removed those changes from my #230 pr for now and put my changes to a separate branch:  https://github.com/uli42/nx-libs/tree/pr/fix_keycode_to_keysym

Need to discuss the right solution.

**Comment by sunweaver** [comment]
@uli42: your approach seems correct: http://stackoverflow.com/questions/9838385/replace-of-xkeycodetokeysym#22418839

I have looked through the pile of macros in XKBstr.h and it seems that with some detours, XkbKeycodeToKeysym does what we expect from it. What is meant by XGetKeyboardMapping is that libX11 does not ship the keysyms statically any longer, but that dpy->syms gets populated via XGetKeyboardMapping by requesting the Xserver for its keymap. Once dpy->syms has been populated, it is accessible via e.g. XkbKeycodeToKeysym.

**Comment by sunweaver** [comment]
Don't forget to add a fixes statement to the commit solving this issue before filing the PR. Thanks.

**Comment by uli42** [comment]
What really made me unsure about this is the conversion of the last
(two) parameter(s):

The stackoverflow post above states that

 idx = group_index \* key_width + shift_level

But I only see code where 0 is taken for the group parameter. I think
you'd need to determine key_width (probably from xkb structure) and
then to some div/mod calculation to do it right.

**Comment by sunweaver** [comment]
So we should go this path then? I guess, we should.

```
keysym = XKeycodeToKeysym(dpy,xe->xkey.keycode,0)
```

----> 

```
{
    int keysyms_per_keycode_return;
    KeySym *keysym = XGetKeyboardMapping(dpy,
        xe->xkey.keycode,
        1,
        &keysyms_per_keycode_return);

    /* do something with keysym[0] */

    XFree(keysym);
}
```

**Comment by sunweaver** [comment]
Reference, related to this: http://bugs.x2go.org/695

**Comment by sunweaver** [comment]
I guess, we can straight away adopt the required code section from X.org's Xnest. I will do this, if I don't get any vetos.

**Comment by uli42** [comment]
No veto, but I have not found anything like that in Xnest!?
