### ISSUE TITLE
No nightlies for RPM-based distros

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#231]
https://jenkins.arctica-project.org/

No nightly builds for nx-libs for rpm based distros available have been built. Why?

**Comment by sunweaver** [comment]
Yeah. I can add test builds to Jenkins, but don't have enough time to set up a range of RPM repos. Putting that on my list, but with lo prio for now.

**Comment by sunweaver** [comment]
writing the above... consider this as an RFH (request for help)... @Ionic?

**Comment by uli42** [comment]
Having never worked with jenkins, so maybe a dumb question: Why do you
need to setup a range of repos? I my (maybe too simple) imagination of
jenkins you need an enviroment with the required devel packages
installed and can then build the rpms. Am I wrong? I think a manual
download is acceptable for nightlies, so again no repo needed.

**Comment by sunweaver** [comment]
Hi Ulrich,

On  Mi 19 Okt 2016 09:06:46 CEST, Ulrich Sibiller wrote:

> Having never worked with jenkins, so maybe a dumb question: Why do you
> need to setup a range of repos? I my (maybe too simple) imagination of
> jenkins you need an enviroment with the required devel packages
> installed and can then build the rpms. Am I wrong? I think a manual
> download is acceptable for nightlies, so again no repo needed.
> 
> On Tue, Oct 18, 2016 at 7:34 PM, Mike Gabriel  
> notifications@github.com wrote:
> 
> > writing the above... consider this as an RFH (request for help)... @Ionic?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.

I'll see to this... Let's start with test builds without binary  
uploads to $SOMEWHERE for now... So we have the CI part covered.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
agreed

**Comment by sunweaver** [comment]
@uli42: I'd say this is covered now by jenkins.x2go.org. On the jenkins.arctica-project.org, I will stay with DEB-only builds, as it is much easier to maintain.
