### ISSUE TITLE
harmonize XKB defaults

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#238]
XKB_BASE_DIRECTORY gets defined via the makefile:

```
nx-X11/programs/Xserver/xkb/Imakefile:XKB_DEFINES = -DXKB_BASE_DIRECTORY=\"$(LIBDIR)/xkb\" $(XKB_DISABLE)
```

Some source files check for that define and set a default otherwise. Because we set it in the makefile it does not matter that there are different defaults in the source files.  IMHO it should be that same everywhere nevertheless. 

Also, I think we should drop NX_XKB_BASE_DIRECTORY and use XKB_BASE_DIRECTORY everywhere. 

```
nx-X11/programs/Xserver/hw/nxagent/Keyboard.c:#ifndef XKB_BASE_DIRECTORY
nx-X11/programs/Xserver/hw/nxagent/Keyboard.c:#define XKB_BASE_DIRECTORY   "/usr/share/X11/xkb"
nx-X11/programs/Xserver/xkb/xkbInit.c:#ifndef XKB_BASE_DIRECTORY
nx-X11/programs/Xserver/xkb/xkbInit.c:#define  XKB_BASE_DIRECTORY      "/usr/lib/X11/xkb"
nx-X11/programs/Xserver/xkb/xkbInit.c:#define  XKB_BIN_DIRECTORY       XKB_BASE_DIRECTORY
nx-X11/programs/Xserver/xkb/ddxLoad.c:#define NX_XKB_BASE_DIRECTORY            "/usr/lib/X11/xkb"
```

**Comment by sunweaver** [comment]
and... we define it as XKB_BASE_DIRECTORY=\"$(LIBDIR)/xkb\"...

Whereas X.org has it in DATADIR, meanwhile... So we should switch over to that.

**Comment by sunweaver** [comment]
I just compared X.org approach with our (old X.org) approach. My suggestion here is:
- drop XKB_ALTERNATE_BASE_DIR.
- set the default XKB_BASE_DIR to /usr/local/share/X11/xkb.
- come-up with one or more include file(s) where _all_ those hard-coded paths get defined
- package maintainers must patch that file when they need different defaults (very likely)
- move more and more definitions into that include file...
- once we move over to autotools, this can be dropped

X.org has xorg-config.h.in, xkb-config.h.in. IMHO we could use filenames like that (e.g., xorg-config-static.h, xkb-config-static.h).

We also need one for nx'ish stuff (nx-config-static.h). All those files should go into Xserver/include, I guess.

How about that?

**Comment by sunweaver** [comment]
Note, that there are also defaults for XKB rules, model, etc. ...

**Comment by uli42** [comment]
We could create those new include files using autotools right now!

**Comment by sunweaver** [comment]
I am a bit reluctant doing the autotools step before 3.6.0. Part of that step will be splitting up the code in nx-libs into these individual Git repos...

  nxcomp
  libNX_X11
  nxcompext
  nxcompshad
  nxproxy
  nxagent

**Comment by uli42** [comment]
at least nxcompext is no longer valid in that list

**Comment by sunweaver** [comment]
actually, we are starting with autotooling nx-libs this month, first candidate is libNX_X11...

**Comment by uli42** [comment]
We are setting these variables in the makefiles now, so closing this.

**Comment by sunweaver** [comment]
On  Sa 18 Jan 2020 11:45:46 CET, Ulrich Sibiller wrote:

> We are setting these variables in the makefiles now, so closing this.

It's always good to reference a bug closure with a concrete commit  
hash (or at least a tag).

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
This was changed over a couple of commits, e.g. 11a1f31d70c189bf6c5f4420f196468267755a0d, f23189e7392254c9458bf76504920cb868360e40, 4ed8145f7be80f162970e25cf960aa7d24b3dafb
