### ISSUE TITLE
remove XFree86LOADER

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#246]
Currently we use this define: `-UXFree86LOADER`

Which means `xf86_ansic.h` and therefore `xf86_libc.h` are never included and can be removed. To be really clean here we should backport this upstream commit: https://cgit.freedesktop.org/xorg/xserver/commit/?id=c3d14036729fd186d4ec7ca1de603e1f2d174e2f

**Comment by uli42** [comment]
I have a branch that removes the xfree86 dir completely. This is working. However, the XFree86LOADER define stuff still should be backported. Here my branch: https://github.com/uli42/nx-libs/tree/pr/remove_xf86

**Comment by sunweaver** [comment]
Please file remove_xf86 as a PR now. I will backport the commit referenced above. Make sure you close this issue with one commit in your PR.
