### ISSUE TITLE
revisit keyboard blocking/ignoring options

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#257]
nxagent knows these command line options:

```
-noignore              don't ignore pointer and keyboard configuration changes mandated by clients
-nokbreset             don't reset keyboard device if the session is resumed
-noxkblock             always allow applications to change layout through XKEYBOARD
```

Their names indicate that blocking/ignoring is active by default. In all the time I have been using NX I never have needed them and could happily change keyboard settings within the session (always via setxkbmap). While playing around with keyboard stuff last week I came across one case where I needed `-noignore` and `-noxkblock` (but that was a modified, buggy source code). 

We should check when/if they work and fix them. I think especially the XKB stuff is not working as expected.

**Comment by sunweaver** [comment]
@uli42: I wonder if we should postpone working on this for 3.7.x or a later 3.6.x point release. Comments? Feedback?

**Comment by uli42** [comment]
Yes, but changes here will probably change the default behaviour. So introducing that for 3.6 might be an advantage because x2go and maybe others will have to be adapted anyway (xinerama!)

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎30.‎10.‎2016 18:25
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Cc: "Ulrich Sibiller" uli42@gmx.de; "Mention" mention@noreply.github.com
Betreff: Re: [ArcticaProject/nx-libs] revisit keyboard blocking/ignoringoptions (#257)

@uli42: I wonder if we should postpone working on this for 3.7.x or a later 3.6.x point release. Comments? Feedback?

**Comment by sunweaver** [comment]
Hi Ulrich,

On  So 30 Okt 2016 21:06:32 CET, Ulrich Sibiller wrote:

> Yes, but changes here will probably change the default behaviour. So  
> introducing that for 3.6 might be an advantage because x2go and  
> maybe others will have to be adapted anyway (xinerama!)
> 
> Vom Smartphone gesendet.
> 
> ----- Ursprüngliche Nachricht -----
> Von: "Mike Gabriel" notifications@github.com
> Gesendet: ‎30.‎10.‎2016 18:25
> An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
> Cc: "Ulrich Sibiller" uli42@gmx.de; "Mention" mention@noreply.github.com
> Betreff: Re: [ArcticaProject/nx-libs] revisit keyboard  
> blocking/ignoringoptions (#257)
> 
> @uli42: I wonder if we should postpone working on this for 3.7.x or  
> a later 3.6.x point release. Comments? Feedback?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Ok. Leaving the 3.6.x milestone for this.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
