### ISSUE TITLE
Remove install-sh  and mkinstalldirs

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#261]
`nx{comp{,ext,shad},proxy}` all contain `install-sh` and `mkinstalldir`. Both should not be part of the repo but come with autotools.

**Comment by sunweaver** [comment]
@uli42: Are you working on this already?

**Comment by sunweaver** [comment]
@uli42: I have assigned myself to this for now. Veto, if you are already on it.

**Comment by uli42** [comment]
No

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎30.‎10.‎2016 18:20
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Cc: "Ulrich Sibiller" uli42@gmx.de; "Mention" mention@noreply.github.com
Betreff: Re: [ArcticaProject/nx-libs] Remove install-sh and mkinstalldirs(#261)

@uli42: Are you working on this already?

**Comment by uli42** [comment]
isn't this obsolete now?

**Comment by sunweaver** [comment]
yes, this issue got fixed by #473, #474, #480 and #498. Thus, closing...
