### ISSUE TITLE
Bug? "Xlib: resource ID allocation space exhausted!"

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#269]
I had started an LXDE session last night (x2go client connected to localhost). My laptop went to standby. When I reactivated it just a few minutes ago I got a message from x2goclient telling me the session had been terminated (this is x2go's way telling me that the connection had been interrupted, I guess). 

Looking at the session log I saw a message that I have never seen before: "Xlib: resource ID allocation space exhausted!". I guess, there's a bug somewhere in libX11!

```
Session: Session resumed at 'Mon Oct 31 03:22:39 2016'.
Info: Screen [0] resized to geometry [1350x859] fullscreen [0].
Info: Screen [0] resized to geometry [1350x859] fullscreen [0].
Info: Screen [0] resized to geometry [1350x859] fullscreen [0].
Info: Screen [0] resized to geometry [1350x859] fullscreen [0].
Error: No data received from remote proxy within 39263 seconds.
Session: Display failure detected at 'Mon Oct 31 15:14:28 2016'.
Session: Suspending session at 'Mon Oct 31 15:14:28 2016'.
Session: Session suspended at 'Mon Oct 31 15:14:28 2016'.
Xlib: resource ID allocation space exhausted!
```

BTW: the session is still running and reconnect is possible.

**Comment by uli42** [comment]
It might be that I had a low memory situation when that happened. I have not seen it again.

**Comment by sunweaver** [comment]
Feel free to reopen this issues, if it occurs again. Closing for now.
