### ISSUE TITLE
VERSION files/symlinks missing in release tarball

### ISSUE THREAD

**Issue by opoplawski** [ArcticaProject/nx-libs#27]
gcc -o nxagent -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fno-strict-aliasing -ansi -Wall -Wpointer-arith -Wundef     -L../../exports/lib   hw/nxagent/miinitext.o                   hw/nxagent/NXwindow.o                    hw/nxagent/NXevents.o                    hw/nxagent/NXproperty.o                  hw/nxagent/NXdixfonts.o                  hw/nxagent/NXglyphcurs.o                 hw/nxagent/NXdispatch.o                  hw/nxagent/NXrender.o                    hw/nxagent/NXglyph.o                     hw/nxagent/NXpicture.o                   hw/nxagent/NXextension.o                 hw/nxagent/NXglxext.o                    hw/nxagent/NXxvdisp.o                    hw/nxagent/NXmiglyph.o                   hw/nxagent/NXmiexpose.o                  hw/nxagent/NXresource.o                  hw/nxagent/NXmiwindow.o                  hw/nxagent/NXdamage.o           dix/libdix.a os/libos.a   hw/nxagent/libnxagent.a fb/libfb.a composite/libcomposite.a damageext/libdamage.a miext/damage/libdamage.a xfixes/libxfixes.a miext/cw/libcw.a                Xext/libext.a xkb/libxkb.a os/libos.a  Xi/libxinput.a                   dbe/libdbe.a record/librecord.a  XTrap/libxtrap.a GL/glx/libglx.a                GL/mesa/GLcore/libGLcore.a                 randr/librandr.a render/librender.a  mi/libmi.a composite/libcomposite.a damageext/libdamage.a miext/damage/libdamage.a xfixes/libxfixes.a miext/cw/libcw.a                 Xext/libext.a xkb/libxkb.a os/libos.a  Xi/libxinput.a                   dbe/libdbe.a record/librecord.a  XTrap/libxtrap.a GL/glx/libglx.a                GL/mesa/GLcore/libGLcore.a                 randr/librandr.a render/librender.a hw/nxagent/libnxagent.a mi/libmi.a      -L../../exports/lib   -lNX_Xext -lNX_X11  -lm                      -lXpm -L ../../../nxcomp -L ../../../nxcompext -L ../../../nxcompshad                 -lXcomp -lXcompext -lXcompshad -lNX_Xrender -lNX_X11 -lNX_Xext -lNX_Xfixes -lXfont                 -L../../../nx-X11/exports/lib -lNX_Xtst -lNX_Xrandr -lNX_Xcomposite -lNX_Xinerama -lXdmcp `pkg-config --libs libxml-2.0` -Wl,-rpath-link,../../exports/lib
/bin/ld: ../../exports/lib/libNX_X11.so: undefined reference to symbol 'deflate'
/usr/lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by sunweaver** [comment]
For better understanding of the reported issue, check [1].

[1] https://fedoraproject.org/wiki/UnderstandingDSOLinkChange

**Comment by sunweaver** [comment]
I looked at the nx-X11/lib/X11 code more closely now. As far as I can see, the 'deflate' symbol does not get used in there directly.

The only places where deflate from zlib.h gets used are in nxcomp (Z.cpp, Transport.cpp) and nxcompext  (Z.c). 

libNX_X11is linked against libXcomp.so.3 and libXcomp.so.3 is linked (as expected) against libz.so.1.

"""
[mike@minobo nx-libs (3.6.x)]$ ldd /usr/lib/x86_64-linux-gnu/libNX_X11.so
    linux-vdso.so.1 (0x00007ffe65c09000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f58ee5d3000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f58ee3ce000)
    libXcomp.so.3 => /usr/lib/x86_64-linux-gnu/libXcomp.so.3 (0x00007f58ee0db000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f58edd32000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f58eeb3f000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f58edb0b000)
    libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007f58ed8b3000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f58ed698000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f58ed38d000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f58ed08b000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f58ece75000)
[mike@minobo nx-libs (3.6.x)]$ ldd /usr/lib/x86_64-linux-gnu/libXcompext.so
    linux-vdso.so.1 (0x00007fff29cf6000)
    libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007fef81df2000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fef81bcb000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fef819af000)
    libNX_X11.so.6 => /usr/lib/x86_64-linux-gnu/libNX_X11.so.6 (0x00007fef81686000)
    libXcomp.so.3 => /usr/lib/x86_64-linux-gnu/libXcomp.so.3 (0x00007fef81394000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fef81088000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fef80d87000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fef80b71000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef807c7000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fef805c3000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fef803be000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fef8229a000)
[mike@minobo nx-libs (3.6.x)]$ ldd /usr/lib/x86_64-linux-gnu/libXcomp.so
    linux-vdso.so.1 (0x00007fff2cec2000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007faa813cc000)
    libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007faa81175000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007faa80f59000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faa80c4e000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faa8094d000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faa80736000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faa8038d000)
    /lib64/ld-linux-x86-64.so.2 (0x00007faa81924000)
"""

It would be easy to add a -lz either to nx-X11/programs/Xserver/Imakefile (where nxagent gets built) or to nx-X11/config/cf/libLnx.tmpl (i.e., to the SharedX11Reqs variable in libLnx.tmpl).

However, I would actually prefer understanding the exact cause of this issue. Also, I cannot reproduce this issue on Debian unstable.

@opoplawski: could you give a rough instruction on how you build the nx-libs package when that error occurs? Thanks.

**Comment by opoplawski** [comment]
libNX_X11.so is create as follows:

```
+ gcc -o ./libNX_X11.so.6.2~ -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-soname,libNX_X11.so.6 Context.o Depths.o ParseCmd.o Quarks.o AllCells.o AllPlanes.o AllowEv.o AutoRep.o Backgnd.o BdrWidth.o Bell.o Border.o ChAccCon.o ChClMode.o ChActPGb.o ChCmap.o ChGC.o ChKeyCon.o ChPntCon.o ChProp.o ChSaveSet.o ChWAttrs.o ChWindow.o ChkIfEv.o ChkMaskEv.o ChkWinEv.o ChkTypEv.o ChkTypWEv.o CirWin.o CirWinDn.o CirWinUp.o ClDisplay.o Clear.o ClearArea.o ConfWind.o ConnDis.o ConvSel.o CopyArea.o CopyCmap.o CopyGC.o CopyPlane.o CrBFData.o CrCmap.o CrCursor.o CrGC.o CrGlCur.o CrPFBData.o CrPixmap.o CrWindow.o Cursor.o DefCursor.o DelProp.o DestSubs.o DestWind.o DisName.o DrArc.o DrArcs.o DrLine.o DrLines.o DrPoint.o DrPoints.o DrRect.o DrRects.o DrSegs.o ErrDes.o ErrHndlr.o EvToWire.o FetchName.o FillArc.o FillArcs.o FillPoly.o FillRct.o FillRcts.o Flush.o Font.o FontNames.o FontInfo.o FreeCmap.o FreeCols.o FreeCurs.o FreeEData.o FreeGC.o FreePix.o FSSaver.o GCMisc.o Geom.o GetAtomNm.o GetColor.o GetDflt.o GetFPath.o GetFProp.o GetGeom.o GetHColor.o GetHints.o GetIFocus.o GetImage.o GetKCnt.o GetMoEv.o GetPCnt.o GetPntMap.o GetProp.o GetSOwner.o GetSSaver.o GetStCmap.o GetWAttrs.o GrButton.o GrKey.o GrKeybd.o GrPointer.o GrServer.o Host.o IfEvent.o ImUtil.o ImText.o ImText16.o InitExt.o InsCmap.o IntAtom.o KeyBind.o KeysymStr.o KillCl.o LiHosts.o LiICmaps.o LiProps.o ListExt.o LoadFont.o LookupCol.o LowerWin.o Macros.o MapRaised.o MapSubs.o MapWindow.o MaskEvent.o Misc.o ModMap.o MoveWin.o NextEvent.o OpenDis.o ParseCol.o ParseGeom.o PeekEvent.o PeekIfEv.o Pending.o PmapBgnd.o PmapBord.o PolyReg.o PolyTxt.o PolyTxt16.o PutBEvent.o PutImage.o QuBest.o QuColor.o QuColors.o QuCurShp.o QuExt.o QuKeybd.o QuPntr.o QuStipShp.o QuTextE16.o QuTextExt.o QuTileShp.o QuTree.o RaiseWin.o RdBitF.o RecolorC.o ReconfWin.o Region.o RepWindow.o RestackWs.o RotProp.o ScrResStr.o SelInput.o SendEvent.o SetBack.o SetCRects.o SetClMask.o SetClOrig.o SetDashes.o SetFPath.o SetFont.o SetFore.o SetFunc.o SetHints.o SetIFocus.o SetLStyle.o SetPMask.o SetPntMap.o SetSOwner.o SetSSaver.o SetState.o SetStip.o SetStCmap.o SetTile.o SetTSOrig.o StBytes.o StColor.o StColors.o StNColor.o StName.o StrKeysym.o Sync.o Synchro.o Text.o Text16.o TextExt.o TextExt16.o TrCoords.o UndefCurs.o UngrabBut.o UngrabKbd.o UngrabKey.o UngrabPtr.o UngrabSvr.o UninsCmap.o UnldFont.o UnmapSubs.o UnmapWin.o VisUtil.o WarpPtr.o WinEvent.o Window.o WrBitF.o XlibAsync.o XlibInt.o Xrm.o evtomask.o globals.o GetGCVals.o GetNrmHint.o GetRGBCMap.o GetTxtProp.o GetWMCMapW.o GetWMProto.o Iconify.o PixFormats.o PropAlloc.o ReconfWM.o SetNrmHint.o SetRGBCMap.o SetTxtProp.o SetWMCMapW.o SetWMProto.o StrToText.o TextToStr.o Withdraw.o WMGeom.o WMProps.o AuDispose.o AuGetBest.o AuFileName.o AuRead.o Lab.o LabGcC.o LabGcL.o LabGcLC.o LabMnL.o LabMxC.o LabMxL.o LabMxLC.o LabWpAj.o Luv.o LuvGcC.o LuvGcL.o LuvGcLC.o LuvMnL.o LuvMxC.o LuvMxL.o LuvMxLC.o LuvWpAj.o XYZ.o uvY.o xyY.o HVC.o HVCGcC.o HVCGcV.o HVCGcVC.o HVCMnV.o HVCMxC.o HVCMxV.o HVCMxVC.o HVCMxVs.o HVCWpAj.o UNDEFINED.o AddDIC.o AddSF.o cmsAllNCol.o cmsAllCol.o CCC.o cmsCmap.o cmsColNm.o CvColW.o CvCols.o cmsGlobls.o IdOfPr.o cmsInt.o LRGB.o cmsLkCol.o cmsMath.o OfCCC.o PrOfId.o cmsProp.o QBlack.o QBlue.o QGreen.o QRed.o QWhite.o QuCol.o QuCols.o SetCCC.o SetGetCols.o StCol.o StCols.o cmsTrig.o XRGB.o FSWrap.o ICWrap.o IMWrap.o OCWrap.o OMWrap.o lcWrap.o mbWMProps.o utf8WMProps.o mbWrap.o wcWrap.o utf8Wrap.o FilterEv.o RegstFlt.o locking.o LockDis.o x11trans.o ximtrans.o XKB.o XKBBind.o XKBCompat.o XKBCtrls.o XKBCvt.o XKBGetMap.o XKBGetByName.o XKBNames.o XKBRdBuf.o XKBSetMap.o XKBUse.o XKBleds.o XKBBell.o XKBGeom.o XKBSetGeom.o XKBExtDev.o XKBList.o XKBMisc.o XKBMAlloc.o XKBGAlloc.o XKBAlloc.o SetLocale.o imConv.o imKStoUCS.o lcCT.o lcCharSet.o lcConv.o lcDB.o lcDefConv.o lcFile.o lcGeneric.o lcInit.o lcPrTxt.o lcPubWrap.o lcPublic.o lcRM.o lcStd.o lcTxtPr.o lcUtil.o lcUTF8.o imCallbk.o imDefFlt.o imDefIc.o imDefIm.o imDefLkup.o imDispch.o imEvToWire.o imExten.o imImSw.o imInsClbk.o imInt.o imLcFlt.o imLcGIc.o imLcIc.o imLcIm.o imLcLkup.o imLcPrs.o imLcSIc.o imRm.o imRmAttr.o imThaiFlt.o imThaiIc.o imThaiIm.o imTrX.o imTransR.o imTrans.o lcEuc.o lcGenConv.o lcJis.o lcSjis.o lcUTF8Load.o omDefault.o omGeneric.o omImText.o omText.o omTextEsc.o omTextExt.o omTextPer.o omXChar.o -L../../exports/lib -ldl -lXdmcp -L../../../nxcomp -lXcomp -lc
```

libXcomp.a is a static library containing the deflate symbol reference.  I think the .a essentially gets imported wholesale.

**Comment by sunweaver** [comment]
Linking libXcomp.a statically into libNX_X11 is bogus, actually. As it is dynamically linked into nxagent, it should also be dynamically linked into libNX_X11 IMHO.

I will look into this next week.

**Comment by sunweaver** [comment]
@orionp: I have looked into this once more. Question: Why do you think that libXcomp.a is used (and not libXcomp.so)?

**Comment by orionp** [comment]
@sunweaver Hmm... I don't think you intended to tag me, since I've never looked at this project. Perhaps another Orion?

**Comment by Ionic** [comment]
Sorry, he meant @opoplawski. You can unsubscribe if you want to.

**Comment by orionp** [comment]
I suspected that was the case; no worries!

**Comment by sunweaver** [comment]
Ouch!

@opoplawski: see above...

**Comment by opoplawski** [comment]
Oh, that's funny.  I'm orionp on irc to make it more confusing.

**Comment by Ionic** [comment]
I don't think `libXcomp` is statically linked into `libNX_X11`? At least I can see `libXcomp` being referenced as a dynamic library on my Gentoo and CentOS system.

**Comment by sunweaver** [comment]
@Ionic: yes, same here...

**Comment by opoplawski** [comment]
Okay, I think I've figured out the issue.  I was using:

./debian/roll-tarball.sh HEAD server

to build a tarball and then building the rpm from that.  In that tarball though I'm missing the VERSION files in the various nx dirs (nx-libs is my git checkout, nx-libs-HEAD the tarball contents):

./nx-libs/VERSION
./nx-libs/nxcompshad/VERSION
./nx-libs/nxcompext/VERSION
./nx-libs/nxcomp/VERSION
./nx-libs/nxproxy/VERSION
./nx-libs-HEAD/VERSION

This then screws up building the .so files since VERSION/LIBVERSION are then empty and we get:

libXcomp.so.  -> libXcomp.so.

i.e. non-existent recursive link.  I suspect ce531230f148a8c586a6e29c340e2db03d7bd3bb is the origin of this change.

If I just run make in the git checkout then this builds okay, although I do see:

```
make[3]: Leaving directory '/export/home/orion/fedora/nx-libs/nx-libs/nx-X11'

Mon Jul 13 19:23:41 MDT 2015

cc: error: ./config/util/printver.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
Makefile:46: recipe for target 'World' failed
make[2]: [World] Error 1 (ignored)
Full build of Release 6.9 complete.

make[2]: Leaving directory '/export/home/orion/fedora/nx-libs/nx-libs/nx-X11'
```

**Comment by opoplawski** [comment]
Looks good, thanks.
