### ISSUE TITLE
RHEL: add font dependency

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#285]
On RHEL6 and 7  `xorg-x11-fonts-misc` is required. Otherwise nxagent will nor work and exit with `could not open default font fixed`

**Comment by sunweaver** [comment]
@opoplawski: does the above also apply to Fedora builds? Can you confirm the above? Thanks for feedback.

**Comment by opoplawski** [comment]
We currently carry the xorg-x1-fonts-misc dependency in the x2goserver package.  Perhaps it is more accurate to carry it in the nxagent package as it is the nxagent code the refers to "fixed" as the backup font name.  But yes, this would apply to current Fedora as well.
