### ISSUE TITLE
RHEL7: dangling link

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#286]
I built rpms on RHEL7 and installed them and found this:

```
# ls -l /usr/lib64/nx-X11/
total 0
lrwxrwxrwx 1 root root 15 Nov 15 10:15 libX11.so -> ../libNX_X11.so
lrwxrwxrwx 1 root root 19 Nov 15 10:15 libX11.so.6.2 -> ../libNX_X11.so.6.2*
```

The first link to `../libNX_X11.so` is dangling as the plain lib file is simply not there:
```
# ls -l /usr/lib64/libNX*
lrwxrwxrwx 1 root root      16 Nov 15 10:15 /usr/lib64/libNX_X11.so.6 -> libNX_X11.so.6.2*
-rwxr-xr-x 1 root root 1334024 Nov 15 10:08 /usr/lib64/libNX_X11.so.6.2*
```
The RPM does not contain it:
```
# rpm -qlp libNX_X11-6-3.5.99.2-0.0build1.el7.centos.x86_64.rpm
/usr/lib64/libNX_X11.so.6
/usr/lib64/libNX_X11.so.6.2
```

**Comment by sunweaver** [comment]
The dangling symlink is not the real issue.

libNX_X11.so is only required when building something against libNX_X11. In Debian packaging libNX_X11.so is a file in libnx-x11-dev. so should it be in the .spec file, I guess.

I will fix this issue by removing the libX11.so symlink to libNX_X11.so entirely. Not needed at runtime.
