### ISSUE TITLE
Remove libNX_Xext - use system's libXext

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#33]
There's no special NX code in there, the code is almost identical to the one of X.Org 7.0 (see http://cgit.freedesktop.org/xorg/lib/libXext/tree/src?id=XORG-7_0):

```
$ diff Xext-nx Xext_xorg_7.0/src/
Only in Xext_xorg_7.0/src/: .cvsignore
Only in Xext-nx: Imakefile
Only in Xext_xorg_7.0/src/: Makefile.am
diff Xext-nx/XShm.c Xext_xorg_7.0/src/XShm.c
1c1
< /* $XdotOrg: xc/lib/Xext/XShm.c,v 1.5 2005/07/30 21:07:25 alanc Exp $ */

---
> /* $XdotOrg: $ */
Only in Xext-nx: Xext-def.cpp
```

**Comment by sunweaver** [comment]
@uli42: I have been playing with libXtst already and dropping it did not work right away on the first attempt. Need to investigate again. I think it was related to lib(NX_)Xtst being heavily intertwined with lib(NX_)Xext.

**Comment by sunweaver** [comment]
See https://github.com/ArcticaProject/nx-libs/issues/32#issuecomment-114019947 for some infos on hurdles concerning this request.

**Comment by uli42** [comment]
has been done at other places
