### ISSUE TITLE
drop (DE)ALLOCATE_LOCAL

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#358]
These macros are heavily used. However, as I need to clear the allocated memory somehow at some places they get into the way (memset does not work) and there's no ALLOCATE_LOCAL_CLEAR or something.

Xorg upstream has replaced them by xalloc and later by malloc so we should probably do that, too:

```
commit 934281126f6c602fa4bd0c2e29d8c9f44fe532b8
Author: Daniel Stone <daniel@fooishbar.org>
Date:   Mon Nov 5 14:18:22 2007 +0000

    Xext: Remove usage of alloca
    
    Replace with heap allocations.
```

```
commit 3f3ff971ecff9936cebafc813af9193b97bba89c
Author: Mikhail Gusarov <dottedmag@dottedmag.net>
Date:   Thu May 6 01:44:06 2010 +0700

    Replace X-allocation functions with their C89 counterparts
    
    The only remaining X-functions used in server are XNF*, the rest is converted to
    plain alloc/calloc/realloc/free/strdup.
    
    X* functions are still exported from server and x* macros are still defined in
    header file, so both ABI and API are not affected by this change.
    
    Signed-off-by: Mikhail Gusarov <dottedmag@dottedmag.net>
    Reviewed-by: Peter Hutterer <peter.hutterer@who-t.net>
```

**Comment by sunweaver** [comment]
Hi Uli,

On Sat Feb 25 16:24:10 2017 GMT+0100, Ulrich Sibiller wrote:
> These macros are heavily used. However, as I need to clear the allocated memory somehow at some places they get into the way (memset does not work) and there's no ALLOCATE_LOCAL_CLEAR or something.
> Xorg upstream has replaced them by xalloc and later by malloc so we should probably do that, too:
> commit 934281126f6c602fa4bd0c2e29d8c9f44fe532b8
> Author: Daniel Stone <daniel@fooishbar.org>
> Date:   Mon Nov 5 14:18:22 2007 +0000
> 
>     Xext: Remove usage of alloca
>     
>     Replace with heap allocations.
> 
> commit 3f3ff971ecff9936cebafc813af9193b97bba89c
> Author: Mikhail Gusarov <dottedmag@dottedmag.net>
> Date:   Thu May 6 01:44:06 2010 +0700
> 
>     Replace X-allocation functions with their C89 counterparts
>     
>     The only remaining X-functions used in server are XNF*, the rest is converted to
>     plain alloc/calloc/realloc/free/strdup.
>     
>     X* functions are still exported from server and x* macros are still defined in
>     header file, so both ABI and API are not affected by this change.
>     
>     Signed-off-by: Mikhail Gusarov <dottedmag@dottedmag.net>
>     Reviewed-by: Peter Hutterer <peter.hutterer@who-t.net>

I have stumbled over those, too, recently. Ack'ed from my side.

Mike
-- 
Sent from my Fairphone (running Sailfish OS)...
