### ISSUE TITLE
remove mibank

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#366]
commit ffaae7c0c69a51a53a76146c79f3630ae197a443
Author: Adam Jackson <ajax@redhat.com>
Date:   Mon Apr 26 20:11:31 2010 -0700

    Remove mibank support
    
    Banked framebuffers are so 1990.  As of 7.4 the only drivers remaining
    that used this were chips, neomagic, trident, and vesa.  vesa only used
    it when not using shadowfb, which is broadly undesirable anyway, and no
    longer uses it at all as of 2.3.0.  neomagic never used it by default,
    and support for it is gone in git master.  The other two effectively
    only ever used it for ISA chips; since ISA support is now gone from
    the server, they have been modified to only compile mibank support when
    ISA support is available.
    
    Signed-off-by: Adam Jackson <ajax@redhat.com>
    Reviewed-by: Keith Packard <keithp@keithp.com>
    Signed-off-by: Keith Packard <keithp@keithp.com>

**Comment by Ionic** [comment]
Wait for April. Already done as part of my RENDER stuff, I guess I could try to cherry-pick it: https://github.com/Ionic/nx-libs/commit/bf3c6419dd011f6982c4f492132e33d6a13ff5e9
