### ISSUE TITLE
keyboad type=auto in x2goclient results in en layout and errors

### ISSUE THREAD

**Issue by HolySephi** [ArcticaProject/nx-libs#368]
Setting keyboard type=auto in x2goclient results in en layout and not the clients layout (german in my case).

Tested on Windows 10 (4.0.5.2) and Ubunut 16.04 (4.1.0.1-0\~1587\~ubuntu16.04.1)

Setting type=pc105/de results correctly in a german layout

The content of the "keyboard" file in the session-directory of the user on the server is with both type-settings the same:
<pre>rules="xorg"
model="pc105"
layout="de"
variant=","
options="grab:break_actions"</pre>

connecting with type=auto results in an error in the "clients" file in the same directory as the "keyboard" file on the server:

<pre>The XKEYBOARD keymap compiler (xkbcomp) reports:
> Error:            Can't find file "null" for symbols include
>                   Exiting
>                   Abandoning symbols file "default"
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Freeing resource id=18F which isn't there.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Freeing resource id=18F which isn't there.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Freeing resource id=18F which isn't there.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server</pre>

There is one of theses errors per connect with type=auto, connecting with type=pc105/de does not create an error message there.

**Comment by uli42** [comment]
Can you please try to remove the comma from the variant line?

**Comment by uli42** [comment]
This file can be tested directy by using `setxkbmap -config <filename>`. And it produces no errors here on Ubuntu 14.04.

**Comment by Ionic** [comment]
Probably getting added here: https://github.com/ArcticaProject/nx-libs/pull/243/files#diff-f2e2356dadc8ce16e75b2502ef174249R1842 (because `variant` was NULL/not passed.)

**Comment by Ionic** [comment]
Back then, I assumed you had a reason for replacing empty parts with a comma so I didn't ask... but given this bug: can you elaborate on why that is necessary? If not, we probably should revert to the old behavior of passing an empty string instead?

**Comment by Ionic** [comment]
Ah, nevermind, that's detailed in ArcticaProject/nx-libs#239

**Comment by uli42** [comment]
I cannot provoke this, with and without the comma.

**Comment by Ionic** [comment]
I think the comma is fine for the `options` part, but not any other, like the layout. Layouts *can* be a comma-separated list, but that is just separating multiple layouts (which can be switched at run time. Most desktop environments provide configurable key bindings for that.)

**Comment by Ionic** [comment]
For other settings, inserting a plain comma might just flat out fail... for instance it doesn't make too much sense to have multiple models or rules. I guess we should look that up in X.Org code directly and try to understand what is legit and what not.

**Comment by uli42** [comment]
Sephi,

`/usr/share/X11/xkb/rules/` is looking like this on my system:
```
insgesamt 628
-rw-r--r-- 1 root root  43517 Jan 15  2014 base
-rw-r--r-- 1 root root  22569 Jan 15  2014 base.extras.xml
-rw-r--r-- 1 root root  41559 Jan 15  2014 base.lst
-rw-r--r-- 1 root root 199674 Jan 15  2014 base.xml
-rw-r--r-- 1 root root  41060 Jan 15  2014 evdev
-rw-r--r-- 1 root root  22569 Jan 15  2014 evdev.extras.xml
-rw-r--r-- 1 root root  41559 Jan 15  2014 evdev.lst
-rw-r--r-- 1 root root 199674 Jan 15  2014 evdev.xml
-rw-r--r-- 1 root root     91 Jan 15  2014 README
lrwxrwxrwx 1 root root      4 Jul 21  2014 xfree86 -> base
lrwxrwxrwx 1 root root      8 Jul 21  2014 xfree86.lst -> base.lst
lrwxrwxrwx 1 root root      8 Jul 21  2014 xfree86.xml -> base.xml
-rw-r--r-- 1 root root    743 Jan 15  2014 xfree98
-rw-r--r-- 1 root root   1126 Jan 15  2014 xkb.dtd
lrwxrwxrwx 1 root root      4 Jul 21  2014 xorg -> base
lrwxrwxrwx 1 root root      8 Jul 21  2014 xorg.lst -> base.lst
lrwxrwxrwx 1 root root      8 Jul 21  2014 xorg.xml -> base.xml
```

Do you have the `xfree86*` links on your system? (maybe the path is different on your system, too)

**Comment by uli42** [comment]
@Ionic: About inserting a comma (citing from #239): _http://unix.stackexchange.com/questions/167131/how-to-use-the-config-option-of-setxkbmap indicates that empty options will not reset the current setting and you need to add a single comma to achieve that._ 

So a comma should be allowed everywhere to reset to default.

**Comment by uli42** [comment]
@HolySephi: some of the lines I see in your output are only visible with TEST eabled in `./hw/nxagent/NXresource.c`. So this is a self compiled version. Then it should not be a big thing to add `#define DEBUG_CMD` somwehre at top of `xkb/ddxList.c` and `xkb/ddxList.c` an recompile once again.

**Comment by uli42** [comment]
<s>@Sunweaver: There seems to be something wrong with the releases:

> (22:19:56) Sephi: uli421: no i did not compile it by myself
> (22:20:14) Sephi: installed it from the ubuntu release
> (22:20:26) Sephi: packages.project-arctica.org/ubuntu
> (22:29:09) arctica@freenode: interesting! Then the Ubuntu release was compiled wrong! "Freeing resource id=18F which isn't there." is clearly surrounded by #ifdef TEST
</s>

Update: The was simply wrong, so I marked it accordingly

**Comment by uli42** [comment]
I could debug a bit:
1. in case of leaving the keyboard to "auto" in x2goclient the options file created by x2go contains `kbtype=null/null` 
2. with TEST and DEBUG enabled in Keyboard.c I get this
```
nxagentCheckXkbBaseDirectory: XkbBaseDirectory variable [/usr/share/X11/xkb].
nxagentKeyboardProc: Using XKB extension.
nxagentKeyboardProc: nxagentKeyboard is [null/null].
nxagentXkbGetRules: XkbBaseDirectory [/usr/share/X11/xkb].
nxagentKeyboardProc: Using keyboard model [null] with layout [null].
nxagentKeyboardProc: XkbInitialMap [NULL]
nxagentKeyboardProc: Init XKB extension.
nxagentKeycodeConversionSetup: Remote: [rules='evdev',model='pc105',layout='de,de,us',variant='nodeadkeys,,',options=''].
keyboard file created
nxagentKeycodeConversionSetup: Activating KeyCode conversion.
nxagentKeyboardProc: nxagentXkbConfigFilePath [/etc/x2go/x2goagent.keyboard].
nxagentKeyboardProc: No config file, going to set rules and init device.
nxagentKeyboardProc: Going to set rules and init device: [rules='xfree86',model='null',layout='null',variants='(null)',options='(null)'].
```
What we can see here is that the code is able to determine the clientside keyboard setting (evdev, pc105,...) and writes them to the keyboard file. But when the code detects that the global keyboard config file is missing it falls back to setting a broken mixed up keyboard config: `rules='xfree86',model='null',layout='null',variants='(null)',options='(null)'].`

There's room for improvement:
1. "null/null" should be treated as "use autoconfiguration"
2. if we manage to create a keyboard file we can use it instead of falling back to defaults

**Comment by Ionic** [comment]
>@Sunweaver: There seems to be something wrong with the releases:
>
>>    (22:19:56) Sephi: uli421: no i did not compile it by myself
>>    (22:20:14) Sephi: installed it from the ubuntu release
>>    (22:20:26) Sephi: packages.project-arctica.org/ubuntu
>>   (22:29:09) arctica@freenode: interesting! Then the Ubuntu release was compiled wrong! "Freeing resource id=18F which isn't there." is clearly surrounded by #ifdef TEST

No, it's not, you must have gotten confused by the `#ifdef TEST` block above. The output in question isn't guarded, check here: https://github.com/ArcticaProject/nx-libs/blob/6144b615dd7ae2acd786aaa08f66c9743870b709/nx-X11/programs/Xserver/hw/nxagent/NXresource.c#L331

**Comment by uli42** [comment]
Ionic: you are right! I'll edit the comment.

**Comment by Ionic** [comment]
Turned out this is not an issue with Arctica's nxagent, but how x2goserver starts/resumes a session. (More specifically, x2goserver was not prepared to accept quoted input.) Closing this report.

We still got some interesting ideas out of it.
