### ISSUE TITLE
nx path has double entries

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#370]
1. run `nxagent -ac :66`
2. run `xterm -display :66` (no window manager required)
3. try to close the nxagent window

As there's at least one client nxagent tries to display a request window using the nxclient binary, which isn't there.

Output:

```
NXTransDialog: WARNING! Couldn't start '/usr/NX/bin/nxclient'. Error is 2 'No such file or directory'.
Warning: Couldn't start '/usr/NX/bin/nxclient'. Error is 2 'No such file or directory'.
NXTransDialog: WARNING! Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
Warning: Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
NXTransDialog: WARNING! Couldn't start 'nxclient'. Error is 2 'No such file or directory'.
Warning: Couldn't start 'nxclient'. Error is 2 'No such file or directory'.
NXTransDialog: WARNING! Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
Warning: Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
```

The last two warnings contain `/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin` twice.

Also, why do we have eight warnings for the same problem here?

**Comment by sunweaver** [comment]
Hi,

On Thu Mar 2 18:58:30 2017 GMT+0100, Ulrich Sibiller wrote:
> run nxagent -ac :66
> run xterm -display :66 (no window manager required)
> try to close the nxagent window
> As there's at least one client nxagent tries to display request window using the nxclient binary, which isn't there.
> Output:
> NXTransDialog: WARNING! Couldn't start '/usr/NX/bin/nxclient'. Error is 2 'No such file or directory'.
> Warning: Couldn't start '/usr/NX/bin/nxclient'. Error is 2 'No such file or directory'.
> NXTransDialog: WARNING! Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
> Warning: Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
> NXTransDialog: WARNING! Couldn't start 'nxclient'. Error is 2 'No such file or directory'.
> Warning: Couldn't start 'nxclient'. Error is 2 'No such file or directory'.
> NXTransDialog: WARNING! Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
> Warning: Trying with path '/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'.
> 
> The last two warnings contain /usr/NX/bin:/opt/NX/bin:/usr/local/NX/bin twice.
> Also, why do we have four warnings for the same problem here? 

I am trying to shed light onto the callback mess with https://github.com/ArcticaProject/nx-libs/pull/320.

We basically need an external executable that acts as a callback dispatcher.

Mike

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by sunweaver** [comment]
@uli42: I just tested this. This only happens if nxclient can neither be found at /usr/NX/bin/nxclient nor in $PATH. The path string is duplicated and printed to screen. The complete code (NXTransDialog, NXTransClient) is bogus. Needs work.
