### ISSUE TITLE
Keyboard issues (x2go 1151)

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#377]
X2go bug 1151 (http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1151):

When using Arctica repo (deb http://packages.arctica-project.org/ubuntu xenial main) with libnx 3.5.99.4 (and previous)
if you suspend a session where your keyboard mapping was azerty - FR for example, when you resume the session, the keyboard mapping becomes qwerty - US.

I suppose US keymap is the default one but it seems restoring the session doesn't retain this environment setting while it works as expected with X2Goserver without Arctica.

**Comment by Ionic** [comment]
Duplicate of #368.
