### ISSUE TITLE
Keystroke.c: can't differentiate between ctrl-alt + <letter> and ctrl-alt-shift + <letter>

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#395]
I stumbled over the key combinations for fullscreen switching...

  ctrl-alt-shift-f (fullscreen on one head, if the client-system is a multi-head system)
  ctrl-alt f (fullscreen on all heads, if the client-system is a multi-head system)

when pressing the key cominations, we always end up in nxagentSwitchAllScreens (and not in nxagentSwitchFullscreen for the first key combination).

**Comment by sunweaver** [comment]
@uli42:

I am pretty sure that the issue underneath this bug is in this line https://github.com/ArcticaProject/nx-libs/blob/3.6.x/nx-X11/programs/Xserver/hw/nxagent/Keystroke.c#L161.

My approach here is something like:

```
  fprintf(stderr, "STATE: %x\n", state);
  fprintf(stderr, "MASK: %x\n", mask);
  fprintf(stderr, "STATE & all_masks: %x\n", state & ( Mod1Mask | Mod2Mask | Mod3Mask | Mod4Mask | ControlMask | ShiftMask | LockMask ));

  /* all modifiers except meta/alt have to match exactly, extra bits are evil */
  if ((state & ( Mod1Mask | Mod2Mask | Mod3Mask | Mod4Mask | ControlMask | ShiftMask | LockMask )) != mask) {
    ret = False;
  }
```

Neither am I sure that this code section (a bit below is correct):

```
      if (strcmp((char *)attr->name, "Mod1") == 0)    { newkm.modifierMask |= Mod1Mask; }
      else if (strcmp((char *)attr->name, "Mod2") == 0)    { newkm.modifierMask |= Mod2Mask; }
      else if (strcmp((char *)attr->name, "Mod3") == 0)    { newkm.modifierMask |= Mod3Mask; }
      else if (strcmp((char *)attr->name, "Mod4") == 0)    { newkm.modifierMask |= Mod4Mask; }
      else if (strcmp((char *)attr->name, "Control") == 0) { newkm.modifierMask |= ControlMask; }
      else if (strcmp((char *)attr->name, "Shift") == 0)   { newkm.modifierMask |= ShiftMask; }
      else if (strcmp((char *)attr->name, "Lock") == 0)    { newkm.modifierMask |= LockMask;  }
      else if (strcmp((char *)attr->name, "AltMeta") == 0) { newkm.modifierAltMeta = True; }
```

To me it feels like the "elses" here should be dropped.

However, time is running short here to go any deeper. Maybe you have a clue, as you have stared at the code for much longer than me.

**Comment by uli42** [comment]
the else cascade is correct since it depends on string comparison.
