### ISSUE TITLE
nxagent: special keystrokes don't work if NUM or CAPS lock are "on"

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#397]
@uli42: I noticed another issue. If you have NUM lock (Mod2Mask) or CAPS lock (LockMask) on, then our special keystrokes get ignored. The below patch fixes that. Shall I file a PR for that? Any other solution proposal?

I seriously think that we should exclude NUM and CAPS lock from the modifiers' list in Keystroke.c.

```
diff --git a/nx-X11/programs/Xserver/hw/nxagent/Keystroke.c b/nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
index d12b459..1ec52bb 100644
--- a/nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
+++ b/nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
@@ -150,7 +150,7 @@ static Bool modifier_matches(unsigned int mask, int compare_alt_meta, unsigned i
   }
 
   /* all modifiers except meta/alt have to match exactly, extra bits are evil */
-  if (mask != state) {
+  if ((mask | Mod2Mask | LockMask) != (state | Mod2Mask | LockMask)) {
     ret = False;
   }
 
@@ -207,13 +207,11 @@ static Bool read_binding_from_xmlnode(xmlNode *node, struct nxagentSpecialKeystr
         continue;
 
            if (strcmp((char *)attr->name, "Mod1") == 0)    { newkm.modifierMask |= Mod1Mask; }
-      else if (strcmp((char *)attr->name, "Mod2") == 0)    { newkm.modifierMask |= Mod2Mask; }
       else if (strcmp((char *)attr->name, "Mod3") == 0)    { newkm.modifierMask |= Mod3Mask; }
       else if (strcmp((char *)attr->name, "Mod4") == 0)    { newkm.modifierMask |= Mod4Mask; }
       else if (strcmp((char *)attr->name, "Mod5") == 0)    { newkm.modifierMask |= Mod5Mask; }
       else if (strcmp((char *)attr->name, "Control") == 0) { newkm.modifierMask |= ControlMask; }
       else if (strcmp((char *)attr->name, "Shift") == 0)   { newkm.modifierMask |= ShiftMask; }
-      else if (strcmp((char *)attr->name, "Lock") == 0)    { newkm.modifierMask |= LockMask;  }
       else if (strcmp((char *)attr->name, "AltMeta") == 0) { newkm.modifierAltMeta = True; }
     }
   }
```

**Comment by uli42** [comment]
I'd say it works as intended.

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" <notifications@github.com>
Gesendet: ‎15.‎03.‎2017 10:55
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [ArcticaProject/nx-libs] nxagent: special keystrokes don't work ifNUM or CAPS lock are "on" (#397)

**Comment by sunweaver** [comment]
Does my patch work as intended? Or the Keystroke.c code as of now. Intuitively, NUM lock is not a modifier key like Shift is, or like control is. Same with CAPS lock.

What do you see as best usable here?

On Wednesday, March 15, 2017, Ulrich Sibiller wrote:
> I'd say it works as intended.
> 
> Vom Smartphone gesendet.
> 
> ----- Ursprüngliche Nachricht -----
> Von: "Mike Gabriel" <notifications@github.com>
> Gesendet: ‎15.‎03.‎2017 10:55
> An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
> Cc: "Subscribed" <subscribed@noreply.github.com>
> Betreff: [ArcticaProject/nx-libs] nxagent: special keystrokes don't work ifNUM or CAPS lock are "on" (#397)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread. 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by uli42** [comment]
I mean the normal behaviour without your patch works at it is supposed to work.

CapsLock and NumLock are normal modifiers in X11, see xmodmap output:
```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
-> lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
-> mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

As we are currently supporting all these modifiers there's no reason for a special treatment of these keys. Otherwise you'd lose these two modifers in keystrokes.cfg. 

Regarding your patch: capslock is lock, I think we can rely on that. But Numlock is Mod2 so it is not guaranteed it will be like this everywhere. So we's need to analyze the setting on the client side to determine what keys have to be treated how. There's similar code for AltMeta recognition in Keyboard.c which I also not really like. We could have the same functionality by specifing Mod1 in the config and dropping all that AltMeta handling. So I would not like to introduce that for NumLock and CapsLock.

**Comment by sunweaver** [comment]
Maybe I have not been clear on the trouble this issue can cause regarding usability. On my keyboards the modifier CAPS is alway on when activated on the keyboard. That means, with CAPS locked, all special keystrokes are disabled.

Same with NUM lock. If the NUM lock LED is on, no special keystrokes are available.

Users have to disable NUM lock and CAPS lock, before they can use keystrokes.

I looked around a bit in nxagent's Keyboard.c. It seems that nxagent "knows" if CAPS or NUM are locked. Also, nxagent "knows" the keycodes of those two keys. However, for NUM lock, how can we know to what modifier (modX) NUM is attached to.

I'd vote for dropping CAPS and NUM from the available modifiers in keystrokes.cfg. From a usability's point of view, using those two as stroke modifiers makes +/- no sense at all. (IMHO).

**Comment by uli42** [comment]
On Fri, Mar 17, 2017 at 10:37 AM, Mike Gabriel <notifications@github.com> wrote:
> Maybe I have not been clear on the trouble this issue can cause regarding usability. On my keyboards the modifier CAPS is alway on when activated on the keyboard. That means, with CAPS locked, all special keystrokes are disabled.

Yes, you have been clear.

> I'd vote for dropping CAPS and NUM from the available modifiers in keystrokes.cfg. From a usability's point of view, using those two as stroke modifiers makes +/- no sense at all. (IMHO).

We currently have complete xkb support. That is just how xkb works.
Dropping some of the support will break this and some things will not
be configurable anymore (e.g. there are people who see no sense in
having a CAPS key and like to use it otherwise. )

But I agree that using CAPS and NUMLOCK as modifiers is somewhat
strange as these keys toggle the LEDs and are also synched to the
remote side.

How about this approach: We could ignore CAPS and NUMLOCK as long as
noone is specifiying them in their keystrokes.cfg.

**Comment by sunweaver** [comment]
On  Fr 17 Mär 2017 10:51:25 CET, Ulrich Sibiller wrote:

> How about this approach: We could ignore CAPS and NUMLOCK as long as
> noone is specifiying them in their keystrokes.cfg.

Nice! Can you put that on your list? Or shall I?

Mike

-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
That has nothing to do with my list (which is for autograb/inputlock). So I'll leave it just here  ;-)

**Comment by uli42** [comment]
Oh my... Now I have implemented two versions (example for CapsLock, for Numlock the same applies):
a) if _any_ keystroke contains CapsLock CapsLock will always be taken into account when comparing keystrokes. If no keystroke contains CapsLock it is ignored so all keystrokes will work wether CapsLock is on or not.
b) if a configured keystroke contains CapsLock it is checked (keystroke will only work with CapsLock on). For all other keystrokes we completely ignore it so they'll work wether CapsLock is on or not.

I like b) better but this way there's no way to configure a keystroke that does _only_ work when CapsLock is off. Also it must be ensured that keystrokes that only differ in CapsLock are in the correct order.

**Comment by sunweaver** [comment]
@uli42: Very nice. I tend to preferring b), as well.
