### ISSUE TITLE
MNX_TCPCONN left over in nx-X11/lib/X11/ConnDis.c

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#399]
@Ionic noted in #376:

> Making a note: MNX_TCPCONN left over in nx-X11/lib/X11/ConnDis.c. It doesn't fit in with the Xserver/os changes, but we probably want to remove it outside of this PR as well.

**Comment by uli42** [comment]
ConnDis will be obsolete once we manage to switch over to xcb.
