### ISSUE TITLE
On-screen KBD support (was: drop nxkdb?)

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#405]
In `Events.c` and `Keystroke.c` there's some code that is used to show an onscreen keyboard (search for "startKbd"). This triggers running a binary called `nxkdb`. As we are not providing that we could also drop the corresponding code.

**Comment by sunweaver** [comment]
This is interesting... Why not attach a well-known (configurable) on-screen keyboard to it?

**Comment by uli42** [comment]
I don't know any. We'd need to supply it, then, too.

**Comment by sunweaver** [comment]
On  Mi 22 Mär 2017 11:09:31 CET, Ulrich Sibiller wrote:

> I don't know any. We'd need to supply it, then, too.
>

e.g. ...

apt-get install onboard

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Probably a script that takes care of the onboard keyboard would be right thing to do here.

**Comment by sunweaver** [comment]
I have reconsidered this. Most implementations of On-Screen Keyboards use some DBus or other session-specific IPC or what-not-other feature that require the keyboard application to be launched inside the Xsession context.

Thus, I'd rather say, let's remove the nxkbd stuff and hand onscreen keyboarding over to the Xsession's desktop environment.

Everyone agreeing?
