### ISSUE TITLE
nxagent: make nx/nx options available on cli

### ISSUE THREAD

**Issue by mviereck** [ArcticaProject/nx-libs#430]
Hello!
I found nxagent in debians "experimental" repositories and I'm using it as nested X server like Xephyr (local usage only without any networking setup and without nxproxy).
Especially I like the rootless mode that is not possible with Xephyr.

I want to use further options like fullscreen, clipboard, geometry and resize. Those are provided with nxproxy and a strange way using DISPLAY. (I did not get it to work with DISPLAY, though.)

My feature request: A possibility to set those options on startup of nxagent with cli options. Only one option to specify an options file would fulfill my needs. Another possibiliy would be to set an environment variable containing nx/nx options.

Thanks!

**Comment by uli42** [comment]
AFAIK this is already possible. I cannot check this right now but man nxagent might help.

Uli


Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "mviereck" <notifications@github.com>
Gesendet: ‎16.‎04.‎2017 21:11
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [ArcticaProject/nx-libs] nxagent: make nx/nx options available on cli(#430)

Hello!
I found nxagent in debians "experimental" repositories and I'm using it as nested X server like Xephyr (local usage only without any networking setup and without nxproxy).
Especially I like the rootless mode that is not possible with Xephyr.
I want to use further options like fullscreen, clipboard, geometry and resize. Those are provided with nxproxy and a strange way using DISPLAY. (I did not get it to work with DISPLAY, though.)
My feature request: A possibility to set those options on startup of nxagent with cli options. Only one option to specify an options file would fulfill my needs.
Thanks!

**Comment by mviereck** [comment]
The man page tells me I can specify an option file with DISPLAY, but does not provide a cli option for this.

**Comment by uli42** [comment]
On Mon, Apr 17, 2017 at 5:39 PM, mviereck <notifications@github.com> wrote:
> The man page tells me I can specify an option file with DISPLAY, but does
> not provide cli option for this.

See line 410 here:
https://github.com/ArcticaProject/nx-libs/blob/3.6.x/nx-X11/programs/Xserver/hw/nxagent/man/nxagent.1

So if you have 3.5.99.5 you should have that in your man page.

Uli

**Comment by uli42** [comment]
On Mon, Apr 17, 2017 at 10:21 PM, Ulrich Sibiller <uli42@gmx.de> wrote:
> On Mon, Apr 17, 2017 at 5:39 PM, mviereck <notifications@github.com> wrote:
>> The man page tells me I can specify an option file with DISPLAY, but does
>> not provide cli option for this.
>
> See line 410 here:
> https://github.com/ArcticaProject/nx-libs/blob/3.6.x/nx-X11/programs/Xserver/hw/nxagent/man/nxagent.1
>
> So if you have 3.5.99.5 you should have that in your man page.

Sorry, I'll take that back. This does not work for your use case.
Should be changed...

Uli

**Comment by mviereck** [comment]
Thanks for looking at this.
I just figured out how to set those options with setting nx/nx in DISPLAY for nxagent, and starting nxclient afterwards within a few seconds before nxagent stops with a failure message. This behaviour along with no visible window was irritating me before I understood how to use nxclient. 

But there seems to be no possibility to use this options with nxagent as a standalone nested server. Would still be nice if this will be possible in future. But don't hurry, it's just my special use case. :-)

**Comment by uli42** [comment]
On Mon, Apr 17, 2017 at 10:37 PM, Ulrich Sibiller <uli42@gmx.de> wrote:
> On Mon, Apr 17, 2017 at 10:21 PM, Ulrich Sibiller <uli42@gmx.de> wrote:
>> On Mon, Apr 17, 2017 at 5:39 PM, mviereck <notifications@github.com> wrote:
>>> The man page tells me I can specify an option file with DISPLAY, but does
>>> not provide cli option for this.
>>
>> See line 410 here:
>> https://github.com/ArcticaProject/nx-libs/blob/3.6.x/nx-X11/programs/Xserver/hw/nxagent/man/nxagent.1
>>
>> So if you have 3.5.99.5 you should have that in your man page.
>
> Sorry, I'll take that back. This does not work for your use case.
> Should be changed...

Finally I have scanned the source. What you want can be done line this:
echo nx/nx,client=linux$DISPLAY >/tmp/opt
nxagent -options /tmp/opt :66

I have improved the manpage for the next release.

Uli

**Comment by uli42** [comment]
On Mon, Apr 17, 2017 at 10:56 PM, mviereck <notifications@github.com> wrote:
>
> Thanks for looking at this.
> I just figured out how to set those options with setting nx/nx in DISPLAY for nxagent, and starting nxclient afterwards within a few seconds before nxagent stops with a failure message. This behaviour along with no visible window was irritating me before I understood how to use nxclient.

What exactly are you referring to as "nxclient"? Nomachine originally
shipped a (closed source) binary of that name that was responsible for
displaying dialogs inside the session. We do not have that in nx-libs
(yet).

Uli

**Comment by mviereck** [comment]
> What exactly are you referring to as "nxclient"? 

Sorry, my fault. I mean "nxproxy"

>Finally I have scanned the source. What you want can be done line this: echo nx/nx,client=linux$DISPLAY >/tmp/opt nxagent -options /tmp/opt :66 I have improved the manpage for the next release.

Great, much thanks!
I tried out some options; so far I found:
 - `geometry=800x600` works fine
 - `fullscreen=1` works fine
 - `clipboard=none` works fine
 - `rootless=1` no effect (but cli switch `-R` works fine)
 - `resize=0` no effect
 - `keyboard=anynonsense` sets my keyboard layout to de/german, arrow keys work fine, AltGr does not work.

This works regardless if I use `$DISPLAY`, `:66` or any other display number. Also it works without any display number, showing a harmless "_Warning: Option file doesn't contain a port specification."_
Also, I can leave away `nx/nx`. The echo command needs "".
Works: `echo "geometry=800x600,clipboard=none" > /tmp/opt  && nxagent -options /tmp/opt :66`

So far, the most important options (for me) are available this way. (The keyboard layout is a story for itself ...)
Thanks!
Martin

**Comment by uli42** [comment]
On Tue, Apr 18, 2017 at 1:49 AM, mviereck <notifications@github.com> wrote:
> geometry=800x600 works fine
> fullscreen=1 works fine
> clipboard=none works fine
> rootless=1 no effect (but cli switch -R works fine)

This is not really surprising. However, maybe there's potential for improvement.

> resize=0 no effect

Hm, resize specifies if you are in desktop resize mode. This can be
toggled using a keystroke (ctrl-alt-r iirc). It is irrelevant for
rootless sessions.

> keyboard=anynonsense sets my keyboard layout to de/german, arrow keys work
> fine, AltGr does not work.

What about "keyboard=query"?

> This works regardless if I use $DISPLAY, :66 or any other display number.
> Also it works without any display number, showing a harmless "Warning:
> Option file doesn't contain a port specification."

Maybe we can improve that, too.

> Also, I can leave away nx/nx. The echo command needs "".

As long as you are not using any special shell characters there's no
need to quote that.

> Works: echo "geometry=800x600,clipboard=none" > /tmp/opt && nxagent -options
> /tmp/opt :66
>
> So far, the most important options (for me) are available this way. (The
> keyboard layout is a story for itself ...)

Yes. Keyboard has been a problem in NX from the beginning. However, I
have some improvements in mind:
https://github.com/ArcticaProject/nx-libs/issues/373

Uli

**Comment by mviereck** [comment]
>>keyboard=anynonsense sets my keyboard layout to de/german, arrow keys work fine, AltGr does not work.

> What about "keyboard=query"?

It does not change the keyboard layout, it stays to be "us"

**Comment by uli42** [comment]
Maybe introduce a further commandline option to directly pass a string, e.g.`-optstring=clipboard=none` Or check if the value of `-options` starts with `nx/nx` and treat that as string. This way you could come around creating a (temporary) options file

**Comment by uli42** [comment]
implemented via 3f7b3001988bf921e6cd860f03a6256b1451ee3d and 76ce623abfd61c71912585a3c24d36cdc1d0a7b4
