### ISSUE TITLE
FTBFS on RHEL7?

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#432]
Posting from x2go-user-list by Jean-Paul Davi <jpdavis@sandia.gov>:

>
> Also, can you please retry using the current developer version of nx-libs as
> described here:
> http://wiki.x2go.org/doku.php/doc:howto:nx-libs-betatesting
>

I finally got around to getting as far as I could trying to build a rpm for nx-libs 3.5.99.4 under RHEL 7 based on instructions at https://github.com/ArcticaProject/nx-libs/blob/3.6.x/README.md, but I get an error "File not found: /builddir/build/BUILDROOT/nx-libs-3.5.99.4-0.0build1.el7.centos.x86_64/usr/share/nx/fonts" no matter what I do.  There is no such directory under RHEL 7.

I had the opportunity to try the Windows x2go client on a different computer to remote into my server.  In that case, x2go correctly used the full resolution of the physical screen on the client computer, which I believe was something like 1920x1080.  Anyone have further ideas?

Jean-Paul

**Comment by uli42** [comment]
Can confirm this:

```
RPM build errors:
    File not found: /home/usibill/rpmbuild/BUILDROOT/nx-libs-3.5.99.6-0.0build1.el7.centos.x86_64/usr/share/nx/fonts
```

**Comment by uli42** [comment]
The problem is this code from commit 7bf444621830b2ae7c2e8dcf846de5fc425b3d74 :

```
+# this needs to be adapted distribution-wise...
+%if 0%{?suse_version}
+ln -s ../fonts %{buildroot}%{_datadir}/nx/fonts
+%elif 0%{?fedora} || 0%{?rhel}
+ln -s ../X11/fonts %{buildroot}%{_datadir}/nx/fonts
+%endif
```

I am not really sure what this is about. At this stage we are in the buildroot dir normally, ../X11/fonts does not exist naturally... So can someone please explain?

**Comment by Ionic** [comment]
This was to create a symlink to `/usr/share/fonts`. It won't resolve at build time, but should exist and work after installation.

What is the actual error? Is this a post-build check for dangling symlinks?

**Comment by uli42** [comment]
The error I see is above. The main cause is the `%elif` above not being true. I have changed the code like this and then it works:

```
# this needs to be adapted distribution-wise...
%if 0%{?suse_version}
ln -s ../fonts %{buildroot}%{_datadir}/nx/fonts
%else
%if 0%{?fedora} || 0%{?rhel}
ln -s ../X11/fonts %{buildroot}%{_datadir}/nx/fonts
%endif
%endif
```

**Comment by Ionic** [comment]
*sigh* that's because rpm does not support `%elif`...

**Comment by uli42** [comment]
BTW: using relative paths here assumes that datadir is pointing to `/usr/share` which is - well - unclean.

**Comment by Ionic** [comment]
Since we're supposed to install into `%{_datadir}` anyway, I don't see how that would be a problem?

**Comment by uli42** [comment]
There's no use using %_datadir if you assume a specifiy value for the variable. You can skip _datadir altogether then and simply replace it by /usr/share. If datadir happens to change at some time in future these links will probably be wrong.

**Comment by uli42** [comment]
Oh, you've been faster than me ;-(

**Comment by Ionic** [comment]
If `%{_datadir}` changes, this source package must be rebuilt with the new value anyway...

I don't see a problem with all of that, though. Your absolute patch is wrong because it assumes `%{_datadir}` to be `/usr/share`, which may not be the case.

**Comment by Ionic** [comment]
In contrast, the relative link will *always* point to the correct location (topdir and then fonts), which is independent of the actual `%{_datadir}` value at run-time and thus even more resilient.

**Comment by uli42** [comment]
`/usr/share/X11/fonts` comes from another rpm. The path in there probably was built using _datadir but IMHO that is not a valid assumption. If that path or rpm  changes, we must adapt our specfile, right.

But currently it is also the other way round: if WE decide to move nx to another location this link will be wrong. If we use an absolute link it will still work! Forgetting to adapt the relative link will not result in a packaging problem but will cause problems at runtime.

Update: maybe we could use _datadir on both sides

**Comment by Ionic** [comment]
No, the point is a different one: we assume our package and its dependencies are built with the same `%{_datadir}` value. As long as that is true, everything will be fine.

If `%{_datadir}` is being set to something else, all packages using it must be rebuilt, which is absolutely fine.

Trust me, the current implementation is correct.

**Comment by uli42** [comment]
ok, I trust you. But I don't like the solution... ;-)

**Comment by Ionic** [comment]
Think about it this way: pretend we want to bundle everything in `/opt/nx`. For that to work, we'd just define a different prefix and build special versions of nx-libs and all its dependencies. No changes required (short of defining the new prefix somehow) - it will magically work.

If `/usr/share/fonts` were hardcoded. this approach would fail badly, since the dependency that should pull this directory in would not pull in `/usr/share/fonts`, but `/opt/nx/share/fonts`. Boom, you'd be left with a dangling symlink.

**Comment by uli42** [comment]
`/usr/share/fonts` is an absolute path. And the link will point to an absolute path no matter what. I don't get it. Is there some chroot magic involved?

**Comment by Ionic** [comment]
No, but `/usr/share/fonts` would not exist if the dependency providing such a directory has been built with a different `datadir`/`prefix` value.
