### ISSUE TITLE
Add direct keystrokes for "suspend session" and "terminate session"

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#442]
We have a "terminate" keystroke. Session suspension used to be possible with the nxclient showing a selection dialog ("terminate", "suspend", "cancel"). Since we currently do not have this dialog stuff and it might be handy to have a direct way without having to deal with answering a dialog we should add an additional direct keystroke. Might also be of interest for "terminate"

**Comment by sunweaver** [comment]
Hi Uli,

On  Fr 21 Apr 2017 00:10:22 CEST, Ulrich Sibiller wrote:

> SSIA

/me agrees. This would also ease things for dealing with dialog  
callbacks via zenity. In zenity we have yes|no dialogs, but no  
suspend|terminate|cancel dialogs.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
From closed/duplicate bug #89... We need to make sure that such keystrokes also work in shadowed sessions.

From X2Go BTS:
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=846
package: nxagent

Currently, there doesn't seem to be a way to cleanly terminate a
shadow session running in fullscreen mode.

Ctrl-Alt-T doesn't work, Alt-Tab gets sent to the remote end, so one
can only run x2goterminatesession on the remote end or kill the
x2goclient task on the local side.

**Comment by uli42** [comment]
#767 brings nxdialog which can show the required dialog

**Comment by sunweaver** [comment]
nxdialog will be available in 3.5.99.19. Thus, closing this one.
