### ISSUE TITLE
Firefox scrolls very slow with gfx.xrender.enabled set to false

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#443]
We observe very slow rendering of graphics/fonts esp. during scrolling with gfx.xrender.enabled set to false.

The issue is more pressing when nxagent is used over nxcomp, but also visible with nxagent being used as a nested Xserver.

The issue does not occur in latest Xephyr and xRDP. So I presume that the issues has been addressed in the new code bases of those two X11 Xserver implementations.

This issue is about to be addressed by one of our developers as paid work. Thanks to all sponsors who contribute(d) to fixing this severe issue.

References:
     http://www.hackermusings.com/2012/05/firefoxs-graphics-performance-on-x11/
     https://www.reddit.com/r/firefox/comments/4nfmvp/ff_47_unbearable_slow_over_remote_x11/
     https://bugzilla.mozilla.org/show_bug.cgi?id=738937

Maybe also relevant:
      https://github.com/ArcticaProject/nx-libs/issues/381
      https://github.com/ssvb/xf86-video-fbturbo/issues/9

**Comment by Hybrid512** [comment]
Well, without proper xrender support, Firefox is not the only application with that kind of slowness.
Webkit based applications such as Chrome/Chromium, Electron based apps (ATOM, Rocke.chat, ....) all have that kind of problem.
Things are a more or less sluggish depending on the resolution/pack method/network speed settings but still, those applications are way slower in their refresh than other xrender friendly applications. (LibreOffice is blazingly fast, so does every MATE apps like pluma, nautilus, atril, ....)
Even GIMP is way faster.
