### ISSUE TITLE
Keyboard delay with 3.5.99.6

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#450]
I have upgraded nx-libs on a Centos7 system from 3.5.0.32 to nx-libs 3.5.99-6. After adapting x2goserver to not set LD_LIBRARY_PATH and to use rrxinerama it worked. However, the same connections (from a x2go thinclient) that had worked before were very laggy keyboardwise. Mouse operation was ok, graphic updates were fast. This makes 3.5.99/3.6 appear as a step back, not forth.

The rpms were built on that very system using the nx-libs.spec patched to worked with RHEL6 (see #447).

**Comment by sunweaver** [comment]
Hi Uli,

On  Sa 29 Apr 2017 17:50:56 CEST, Ulrich Sibiller wrote:

> I have upgraded nx-libs on a Centos7 system from 3.5.0.32 to nx-libs  
> 3.5.99-6. After adapting x2goserver to not set LD_LIBRARY_PATH and  
> to use rrxinerama it worked. However, the same connections (from a  
> x2go thinclient) that had worked before were very laggy  
> keyboardwise. Mouse operation was ok, graphic updates were fast.  
> This makes 3.5.99/3.6 appear as a step back, not forth.
>
> The rpms were build on that very system using the nx-libs.spec  
> pathed to worked with 3.6 (see #447).

I noticed such delays, as well, recently. But I thought that they were  
related to bad OpenVPN connectivity.

We need to investigate, I fear.

Do you have a fixed way of reproducing the issue? Do you see it always  
on remote connections? Or only in specific setups?

Greets,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Well, I don't have a fixed way. I don't even have a remote server for checking this ATM. I was investigating a different problem on Stefan Baur's server and had the permission to upgrade to nx 3.6. I used the current 3.5.99-6 state, fixed the spec file, built a srpm and rebuilt that. Then I installed all the resulting rpms, adapted /etc/x2go/x2goagent.options to include +rrxinerama and changed x2goruncommand to _not_ set LD_LIBRARY_PATH. And that was it. Stefan has reset the server to an older snapshot meanwhile.

As I am using 3.5.99 only locally I have never seen these before. It looks like NX keyboard handling got fragile regarding network lacency.

**Comment by uli42** [comment]
This is not centos related. You can provoke it easily: startup a session in your LAN and run this for your network interface on client side (eth2 for me):

```
sudo tc qdisc add dev eth2 root netem delay 80ms
```
This will add 80ms delay for each packet going over that interface.

-> keyboard will be close to unusable. nx-libs 3.5 does _not_ suffer from this.

(reset the delay with `sudo tc qdisc delete dev eth2 root netem delay 80ms`)

Update:
I have also tried this for the loopback interface, but nx 3.5.0 and 3.5.99 behave identically here, YMMV:

```
nxagent -nolisten unix -ac :55
xterm -display tcp:127.0.0.1:55
sudo tc qdisc add dev lo root netem delay 800ms
```

(if you do the sudo tc before the xterm it will take ages to open up...)

**Comment by uli42** [comment]
I suspect commit 38ac74d6 as the reason. That commit was included in 3.5.99.4, so we should check if if happens with 3.5.99.3.

**Comment by uli42** [comment]
Interestingly `nxcomp/(Client|Server)Channel.cpp` seem to have support for `XGetKeyboardMapping()` (which above commit is using) but not for the previously used `XKeycodeToKeysym()`! 

Can it really be that the caching is causing this?

**Comment by sunweaver** [comment]
Hi Uli,

On  Mi 03 Mai 2017 09:13:34 CEST, Ulrich Sibiller wrote:

> I suspect commit 38ac74d6 as the reason. That commit was included in  
> 3.5.99.4, so we should check if if happens with 3.5.99.3.

this commit is atomic and can easily reverted. As you have a test  
setup at hand already, can you do that revert and check?

Thanks,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Yes, that's what I am planning for tonight.

BTW: the revert needs some manual intervention as I have changed the code during my keystroke improvement work.

**Comment by uli42** [comment]
My tests showed that it was indeed commit 38ac74d.
