### ISSUE TITLE
investigate: fake SONAME in libNX_X11?

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#455]
I have an idea that - if successful - will enable us to
- drop `/usr/lib/x86_64-linux-gnu/nx/X11/` completely
- forget about LD_LIBRARY_PATH tricks (not sure if there are any left for nxagent)
- drop NX_LIBDIR variable
- make nxagent runable standalone without wrapper scripts

This will also completely kill all problems that are happening when libX11.so from the system somehow sneaks into the linking process (I was fighting with this just this evening when I downgrade from 3.5.99.7 to 3.5.0.32 for a test; there were some leftover libs in unexpected places).

Now, my idea:

`readelf -a libNX_X11.so` shows something like this:
```
...
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libXdmcp.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libNX_X11.so.6]
...
```
According to my google research SONAME is the relevant name that is used when searching for objects to link. nxagent is using some of the system libs like libXext and those have libX11.so.6 in their NEEDED entries. We currently make the linker find libNX_X11.so.6 instead by providing links like `libX11.so.6 -> libNX_X11.so.6` in `/usr/lib/x86_64-linux-gnu/nx/X11/`.

Now, if we change the SONAME for the _FILE_ libNX_X11.so.6 to `libX11.so.6` we might be able to stop the linker from searching for the system's libX11.so because it already has linked a library with that name.

It might be necessary to move libNX_X11 from the system lib directory to another place because ldconfig creates additional links based on the soname but as nxagent is the only consumer of libNX_X11 we can point nxagent to the new location using RPATH and be fine.

**Comment by uli42** [comment]
For a test the tool [patchelf](https://github.com/NixOS/patchelf) could be useful. It offers `--set-soname`.

**Comment by uli42** [comment]
It works:

1. copy libNX_X11.so.6 and nxagent to some tmp dir
```
uli@traube:/tmp/soname_test$ cp /usr/lib/x86_64-linux-gnu/libNX_X11.so.6 /tmp/soname_test/
uli@traube:/tmp/soname_test$ cp /usr/lib/x86_64-linux-gnu/nx/bin/nxagent /tmp/soname_test/
```

2. as nxagent has rpath set to our helper dir with libX11.so links the linker does not pull in the system's libX11.so.6 but our softlink that points to libNX_X11
```
uli@traube:/tmp/soname_test$ patchelf --print-rpath nxagent
/usr/lib/x86_64-linux-gnu/nx/X11
uli@traube:/tmp/soname_test$ ls -l /usr/lib/x86_64-linux-gnu/nx/X11
insgesamt 0
lrwxrwxrwx 1 root root 20 Apr  4 22:13 libX11.so.6 -> ../../libNX_X11.so.6
lrwxrwxrwx 1 root root 22 Apr  4 22:13 libX11.so.6.2 -> ../../libNX_X11.so.6.2
```

```
uli@traube:/tmp/soname_test$ LD_DEBUG=files ldd nxagent |& grep X11
      7721:     file=libNX_X11.so.6 [0];  needed by ./nxagent [0]
      7721:     file=libNX_X11.so.6 [0];  generating link map
      7721:     file=libX11.so.6 [0];  needed by /usr/lib/x86_64-linux-gnu/libXpm.so.4 [0]
        libNX_X11.so.6 => /usr/lib/x86_64-linux-gnu/libNX_X11.so.6 (0x00007f697501b000)
```

3. remove the helper dir from the rpath
```
uli@traube:/tmp/soname_test$ patchelf --remove-rpath nxagent
```

4. Now the system's libX11 is pulled in
```
uli@traube:/tmp/soname_test$ LD_DEBUG=files ldd nxagent |& grep X11
      7745:     file=libNX_X11.so.6 [0];  needed by ./nxagent [0]
      7745:     file=libNX_X11.so.6 [0];  generating link map
      7745:     file=libX11.so.6 [0];  needed by /usr/lib/x86_64-linux-gnu/libXpm.so.4 [0]
      7745:     file=libX11.so.6 [0];  generating link map
      7745:     file=libxcb.so.1 [0];  needed by /usr/lib/x86_64-linux-gnu/libX11.so.6 [0]
        libNX_X11.so.6 => /usr/lib/x86_64-linux-gnu/libNX_X11.so.6 (0x00007f7de8075000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f7de7542000)
```

5. change the rpath to to our tmp dir
```
uli@traube:/tmp/soname_test$ patchelf --set-rpath `pwd` nxagent
```

6. does not help, we still see the system's libX11.so.6
```
uli@traube:/tmp/soname_test$ LD_DEBUG=files ldd nxagent |& grep X11
      7764:     file=libNX_X11.so.6 [0];  needed by ./nxagent [0]
      7764:     file=libNX_X11.so.6 [0];  generating link map
      7764:     file=libX11.so.6 [0];  needed by /usr/lib/x86_64-linux-gnu/libXpm.so.4 [0]
      7764:     file=libX11.so.6 [0];  generating link map
      7764:     file=libxcb.so.1 [0];  needed by /usr/lib/x86_64-linux-gnu/libX11.so.6 [0]
        libNX_X11.so.6 => /tmp/soname_test/libNX_X11.so.6 (0x00007f63327c8000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6331c95000)
```

7. change the SONAME of libNX_X11.so.6
```
uli@traube:/tmp/soname_test$ patchelf --print-soname libNX_X11.so.6 
libNX_X11.so.6
uli@traube:/tmp/soname_test$ patchelf --set-soname libX11.so.6 libNX_X11.so.6 
uli@traube:/tmp/soname_test$ patchelf --print-soname libNX_X11.so.6 
libX11.so.6
```

8. And now our lib is treated as libNX_X11.so.6 (via the filename) and libX11.so.6 (via the SONAME) at the same time. Our helper dir with the links is not required anymore.

```
uli@traube:/tmp/soname_test$ LD_DEBUG=files ldd nxagent |& grep X11
      7779:     file=libNX_X11.so.6 [0];  needed by ./nxagent [0]
      7779:     file=libNX_X11.so.6 [0];  generating link map
        libNX_X11.so.6 => /tmp/soname_test/libNX_X11.so.6 (0x00007f7ac8181000)
```

So the steps to implement this into our builds are these:
- change the soname of  `/usr/lib/x86_64-linux-gnu/libNX_X11.so.6` to `libX11.so.6`
- remove the rpath from `/usr/lib/x86_64-linux-gnu/nx/bin/nxagent`
- drop `/usr/lib/x86_64-linux-gnu/nx/X11`

The only drawback of this is that we now have two libs (libNX_X11.so.6 and libX11.so.6) with the same SONAME. Some distribution rules might forbid bid this, I don't know.

Update: ldconfig takes the soname when creating symbolic links so we cannot put libX11 and libNX_X11 into the same directory. So we need to move libNX_X11 to `/usr/lib/x86_64-linux-gnu/nx/X11` and leave the rpath of nxagent as it has been before. It's not as elegant anymore but at least we still can get rid of the helper links

Comments?

**Comment by Ionic** [comment]
I can't comment on that right away, since I lack the necessary ELF knowledge.

One of my concerns is that while we currently only really support/test on Linux which natively uses ELF binaries, other systems (Windows, OS X) don't. I think Mach-O can handle such a situation via a similar mechanism, but I haven't ever tried to do that.

**Comment by uli42** [comment]
This is only relevant for nxagent, libNX_X11 is not used loaded by the proxy. So Windows and OS X are out anyway.

**Comment by uli42** [comment]
This is not relevant anymore, we have to put the linNX_X11 to a separate dir anyway (because of the ldconfig problem mentioned above) and have solved the linking some time ago.
