### ISSUE TITLE
no quilt tool in Leap 42.2

### ISSUE THREAD

**Issue by 4nanook** [ArcticaProject/nx-libs#457]
Build instructions for OpenSuse require obs-build but no obs-build in Leap 42.2 repositories.
I also checked OpenSuse software website and rpm.pbone.net and was not able to locate an obs-build package for Leap 42.2.

**Comment by Ionic** [comment]
I think OBS is a bit difficult to get for SUSE, it looks like you'll have to fetch an obs-worker appliance, but I have never done any of that myself.

**Comment by Ionic** [comment]
Generally, [this repository](https://build.opensuse.org/project/show/openSUSE:Tools) provides the necessary tools (including obs-build which is named "build" there), but it's not easily visible which packages are needed and if there is a pseudo-package pulling in everything that is necessary for building packages.

**Comment by uli42** [comment]
Can't you simply build the rpm using `rpmbuild -ba`?

**Comment by 4nanook** [comment]
I get:

Unable to create repository
from URL 'https://build.opensuse.org/project/show/OpenSUSE:Tools'

Change URL and try again?

      When I try to add the repository using the software management section
of Yast.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by Ionic** [comment]
Yes, you need to add the repository URL, this is just a web interface.

Try https://download.opensuse.org/repositories/openSUSE:/Tools/openSUSE_42.2

**Comment by 4nanook** [comment]
I managed to get build installed, next hurdle was what it wanted for
"VERSION", the way the repository is organized 13.2 was just "13.2", but
leap requires /leap/42.2/ now appears to be building.  Not working with a
rocket fast machine for this particular box so taking a while to compile.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
Ok, got build, had some problems with the instructions, says to get
3.5.99.0 but the spec says 3.5.99.7 so adjusted accordingly.  Compile fails
as follows:

[  109s] gcc -c -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall 
-D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables 
-fasynchronous-unwind-tables -fno-strict-aliasing -std=c99 -Wall -Wpedantic 
-Wpointer-arith -Wundef    -I../../../../../programs/Xserver/GL/mesa/X 
-I../../../../../exports/include/nx-X11 
-I../../../../../include/extensions 
-I../../../../../extras/Mesa/src/mesa 
-I../../../../../extras/Mesa/src/mesa/main 
-I../../../../../extras/Mesa/src/mesa/glapi 
-I../../../../../extras/Mesa/src/mesa/shader 
-I../../../../../extras/Mesa/src 
-I../../../../../extras/Mesa/src/mesa/drivers/x11 
-I../../../../../extras/Mesa/include 		-I../../../../../lib/GL/glx 
-I../../../../../lib/GL/include 
-I../../../../../programs/Xserver/include 
-I../../../../../programs/Xserver/GL/include 
-I../../../../../programs/Xserver/GL/glx 
-I../../../../../programs/Xserver/hw/xfree86/os-support 
-I../../../../../extras/drm/shared-core 		`pkg-config 
--cflags-only-I pixman-1`  -I../../../../.. -I../../../../../exports/include 
-Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L 		-D_POSIX_SOURCE 
-D_XOPEN_SOURCE 				-D_DEFAULT_SOURCE 
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 
-D_GNU_SOURCE 				  	-DSHAPE 	-DXINPUT 
-DXKB 	-DXCSECURITY 	-DXF86BIGFONT 	-DDPMSExtension 
-DRENDER 	-DRANDR 	-DPANORAMIX 	-DXFIXES 	-DDAMAGE 
-DCOMPOSITE 	 -DGCCUSESGAS -DAVOID_GLYPHBLT -DPIXPRIV -DSINGLEDEPTH 
-DXvExtension 				-DXFree86Server 	-DXvMCExtension 
-DBUILDDEBUG -DXResExtension 
-DX_BYTE_ORDER=X_LITTLE_ENDIAN 
-DXORG_VERSION_CURRENT="(((6) * 10000000) + ((9) * 100000) + ((0) * 1000) + 0)" 
-D_XSERVER64 -DNDEBUG    -DHAVE_SETITIMER=1  -DFUNCPROTO=15 -DNARROWPROTO 
-DGLXEXT -D__GLX_ALIGN64  -DNXAGENT_SERVER   xm_span.c
[  109s] xm_api.c: In function 'xmesa_alloc_back_buffer':
[  109s] xm_api.c:685:7: error: too few arguments to function 
'b->xm_visual->display->CreatePixmap'
[  109s]        b->backxrb->pixmap = XMesaCreatePixmap( b->xm_visual->display,
[  109s]        ^
[  109s] xm_api.c: In function 'setup_8bit_hpcr':
[  109s] xm_api.c:1039:7: error: too few arguments to function 
'v->display->CreatePixmap'
[  109s]        v->hpcr_clear_pixmap = XMesaCreatePixmap(v->display,
[  109s]        ^
[  109s] xm_api.c: In function 'initialize_visual_and_buffer':
[  109s] xm_api.c:1224:31: warning: variable 'front_xrb' set but not used 
[-Wunused-but-set-variable]
[  109s]     struct xmesa_renderbuffer *front_xrb, *back_xrb;
[  109s]                                ^
[  109s] Makefile:577: recipe for target 'xm_api.o' failed
[  109s] make[10]: *** [xm_api.o] Error 1
[  109s] make[10]: *** Waiting for unfinished jobs....
[  111s] make[10]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11/programs/Xserver/GL/mesa/X'
[  111s] Makefile:493: recipe for target 'all' failed
[  111s] make[9]: *** [all] Error 2
[  111s] make[9]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11/programs/Xserver/GL/mesa'
[  111s] Makefile:499: recipe for target 'mesa' failed
[  111s] make[8]: *** [mesa] Error 2
[  111s] make[8]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11/programs/Xserver/GL'
[  111s] Makefile:672: recipe for target 'GL' failed
[  111s] make[7]: *** [GL] Error 2
[  111s] make[7]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11/programs/Xserver'
[  111s] Makefile:456: recipe for target 'all' failed
[  111s] make[6]: *** [all] Error 2
[  111s] make[6]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11/programs'
[  111s] xmakefile:457: recipe for target 'all' failed
[  111s] make[5]: *** [all] Error 2
[  111s] make[5]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11'
[  111s] xmakefile:536: recipe for target 'World' failed
[  111s] make[4]: *** [World] Error 2
[  111s] make[4]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11'
[  111s] Makefile:37: recipe for target 'World' failed
[  111s] make[3]: *** [World] Error 2
[  111s] make[3]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7/nx-X11'
[  111s] Makefile:63: recipe for target 'build-full' failed
[  111s] make[2]: *** [build-full] Error 2
[  111s] make[2]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7'
[  111s] Makefile:90: recipe for target 'build' failed
[  111s] make[1]: *** [build] Error 2
[  111s] make[1]: Leaving directory 
'/home/abuild/rpmbuild/BUILD/nx-libs-3.5.99.7'
[  111s] Makefile:52: recipe for target 'all' failed
[  111s] make: *** [all] Error 2
[  111s] error: Bad exit status from /var/tmp/rpm-tmp.9mvt00 (%build)
[  111s]
[  111s]
[  111s] RPM build errors:
[  111s]     Bad exit status from /var/tmp/rpm-tmp.9mvt00 (%build)
[  111s]
[  111s] opensuse failed "build nx-libs.spec" at Wed May 17 21:27:29 UTC 2017.


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by uli42** [comment]
I had similar problems on Centos. I needed to add the quilt package to make the mesa-quilt script work. See #444

**Comment by 4nanook** [comment]
Unfortunately, quilt is already installed:

sudo zypper install quilt
root's password:
Retrieving repository 'Untested Updates' metadata 
.......................................................[done]
Building repository 'Untested Updates' cache 
............................................................[done]
Loading repository data...
Reading installed packages...
'quilt' is already installed.
No update candidate for 'quilt-0.64-3.21.noarch'. The highest available version 
is already installed.
Resolving package dependencies...


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by sunweaver** [comment]
if you build via obs-build, you need quilt inside the build-env. Not on your local system.

**Comment by 4nanook** [comment]
I've upgraded to 42.3 and have not tried again yet.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
