### ISSUE TITLE
FTBFS on epel7 on ppc64le

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#462]
See the build.log.gz [here](https://copr-be.cloud.fedoraproject.org/results/mikedep333/nx-libs-3.6/epel-7-ppc64le/00556581-nx-libs/).

There are multiple instances of the line like:
`Display.c:2273:3: error: 'for' loop initial declarations are only allowed in C99 mode
`

**Comment by uli42** [comment]
There are more places that use this construct, so I am wondering why it is only complaining here.

```
hw/nxagent/Display.c:  for (int i = 0; i < nxagentNumDepths; ++i)
hw/nxagent/Display.c:    for (int j = 0; j < nxagentNumDepthsRecBackup; ++j)
hw/nxagent/Display.c:  for (int i = 0; i < nxagentNumPixmapFormats; ++i)
hw/nxagent/Display.c:    for (int j = 0; j < nxagentRemoteNumPixmapFormats; ++j)
hw/nxagent/Events.c:  for (int i = 0; i < WINDOWSUFFIX_MAX; i++)
hw/nxagent/Events.c:  for (int i = 0; i < WINDOWSUFFIX_MAX; i++)
hw/nxagent/Keystroke.c:      for (int i = 0; nxagentSpecialKeystrokeNames[i] != NULL; i++)
hw/nxagent/Keystroke.c:                for (int j = 0; j < idx; j++)
hw/nxagent/Keystroke.c:  for (int i = 0; nxagentSpecialKeystrokeNames[i]; i++)
hw/nxagent/Screen.c:    for (int i = 0; i < c->numOutputs; i++) {
hw/nxagent/Screen.c:    for (int i=0; i < number; i++) {
hw/nxagent/Screen.c:        for (int j=0; j < pScrPriv->crtcs[i]->numOutputs; j++)
```

**Comment by sunweaver** [comment]
My builds here actually have -std=c99 set. So the real question is: why is it not set for your builds. Please provide details of the build method being used when the above issues get triggered.

Thanks!

**Comment by sunweaver** [comment]
@mikdep333: ping

**Comment by sunweaver** [comment]
@mikedep333: nx-libs build on epel-7 on ppc64le seem to be ok as of today:
https://japsand.x2go.org:8443/view/All%20ppc64le%20(nightly)/job/nx-libs+ppc64le+nightly+epel-7/

Thus, closing this issue.
