### ISSUE TITLE
improve option passing

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#476]
We can pass options to nxagent like this:

```echo "geometry=800x600,clipboard=none" > /tmp/opt && nxagent -options /tmp/opt :66```

Maybe introduce a further commandline option to directly pass a string, e.g. `-optstring=clipboard=none` Or check if the value of `-options` starts with `nx/nx` and then treat that as string. instead of a filename.  This way you could come around creating a (temporary) options file.

See #430 for further details

**Comment by sunweaver** [comment]
The reason for having the options file is some limitation in cmdline length in X11, IIRC. Can't remember where that's coded actually, though.

Really consolidating this needs some work.

1. Differentiate nxcomp nx/nx options from agent options (see man nxproxy for that, maybe).
2. Add an option to nxagent, I am fine with -optstring.
3. Accept agent options always, ignore nxcomp options when running in nested mode

**Comment by uli42** [comment]
I think the reason for having the option file is that you can manipulate it _after_ the session start (e.g. on reconnect). You cannot do this with an env variable or a command line argument. However, for non-persistent sessions and nested sessions it is useful to simply pass options on the command line.

**Comment by sunweaver** [comment]
On  Di 04 Jul 2017 23:11:18 CEST, Ulrich Sibiller wrote:

> I think the reason for having the option file is that you can  
> manipulate it _after_ the session start (e.g. on reconnect). You  
> cannot do this with an env variable or a command line argument.  
> However, for non-persistent sessions and nested sessions it is  
> useful to simply pass options on the command line.

True indeed. I agree that passing in options directly via cmdline is a  
missing feature. Thanks for thinking about how to add that.
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
