### ISSUE TITLE
Handling of DISPLAY variable is broken

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#477]
Running nxagent and trying to pass options via DISPLAY variable is broken:

```
$ DISPLAY=clipboard=both:0 ./nxagent :68
xagentParseOptions: Processing option 'clipboard' = 'both'.

NXAGENT - Version 3.5.99.7

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
Copyright (c) 2011-2016 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Copyright (c) 2014-2016 Ulrich Sibiller <uli42@gmx.de>
Copyright (c) 2014-2016 Mihai Moldovan <ionic@ionic.de>
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '18428'.
Session: Starting session at 'Tue Jul  4 19:09:24 2017'.
_X11TransSocketINETConnect() can't get address for clipboard=both,:6000: Name or service not known
Error: Aborting session with 'Unable to open display 'clipboard=both:0''.
Session: Aborting session at 'Tue Jul  4 19:09:24 2017'.
Session: Session aborted at 'Tue Jul  4 19:09:24 2017'.
[Inferior 1 (process 18428) exited with code 01]
```

The first output line (resulting from Args.c being compiled with TEST) shows the DISPLAY string is parsed and the clipboard option is recognized. But later on the window cannot be opened because the clipboard option is still contained in the display string. Should the DISPLAY env be modified after parsing?

Update: Turns out that - according to the nxagent manpage - using DISPLAY like this is only for connections using nxcomp: 

>  When launching an nxcomp  based  nx-X11 agent session (i.e. proxy <-> agent), you will normally set the $DISPLAY variable like this

So it is clear that it can/will not work for this setup. Thus closing this issue.

**Comment by sunweaver** [comment]
Yeah, but shouldn't we handle this more intellegently? Also, it might be helpful to set agent options in non-nxcomp mode (e.g. the clipboard mode). So, we might actually want the above as a feature. Don't you think?

**Comment by uli42** [comment]
I have another idea: What about allowing the =-options= option to not only accept a filename but also a string with options (e.g. if the first character is a `-` we interpret it as option string, else it is a filename)?

**Comment by sunweaver** [comment]
On  Di 04 Jul 2017 23:02:29 CEST, Ulrich Sibiller wrote:

> I have another idea: What about allowing the =-options= option to  
> not only accept a filename but also a string with options (e.g. if  
> the first character is a `-` we interpret it as option string, else  
> it is a filename)

Why not let it start with nx/nx and then append options comma  
separated: "nx/nx,foo=bar,[...]". That would be more consistent with  
the DISPLAY based notation.

-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Interestingly it kinda works (it does not stop, but it waits for a connection) if `$DISPLAY` starts with `nx`:

```
DISPLAY=nx,clipboard=both:0 ./nxagent  :66
nxagentParseOptions: Processing option 'nx' = '(null)'.
nxagentParseOptions: Processing option 'clipboard' = 'both'.

NXAGENT - Version 3.5.99.7

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
Copyright (c) 2011-2016 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Copyright (c) 2014-2016 Ulrich Sibiller <uli42@gmx.de>
Copyright (c) 2014-2016 Mihai Moldovan <ionic@ionic.de>
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '27165'.
Session: Starting session at 'Fri Jul  7 18:28:12 2017'.
Info: Proxy running in server mode with pid '27165'.
Info: Waiting for connection from any host on socket 'tcp:*:4000'.

```
