### ISSUE TITLE
RandR still at version 1.2

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#48]
I have an Ubuntu 15.04 64-bit test VM where I built nx-libs 3.6.x from commit 4ed85e8 (2015-05-29), which is after PR #21 was merged.

However, RandR still appears to be at version 1.2.

```
batmin@ubuntu-v:~$ xrandr -v
xrandr program version       1.4.1
Server reports RandR version 1.2
```

Furthermore, LXQt (Using Qt 5.4.1) still fails to start / show up correctly. OpenBox starts, and the lxqt-panel process is running. However, immediately after connecting with X2Go Client and seeing the X2Go logo, the panel appears to show up for a split-second, and then disappears.
([As discussed here](http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=637), It is believed that LXQt under Qt 5.4.x fails due it requiring a newer version of RandR).

This is the output in .xsession-x2go-errors after I tried to start the session, but it failed and I opened up a QTerminal (and maximized the x2go session window):

```
XSession-x2go: X session started for batmin at Mon Jun  1 01:11:03 EDT 2015
localuser:batmin being added to access control list
openConnection: connect: No such file or directory
cannot connect to brltty at :0
/etc/x2go/Xsession: 8: [: x: unexpected operator
QXcbConnection: Failed to get the primary output of the screen
iconTheme "oxygen"
iconTheme "oxygen"
iconTheme "oxygen"
iconTheme "oxygen"
Theme: Cannot open file for reading: "/usr/share/lxqt/themes/frost/lxqt-session.qss"
QXcbConnection: Failed to get the primary output of the screen
QXcbConnection: XCB error: 172 (Unknown), sequence: 162, resource id: 326, major code: 149 (Unknown), minor code: 20
QXcbConnection: XCB error: 172 (Unknown), sequence: 359, resource id: 326, major code: 149 (Unknown), minor code: 20
/build/lxqt-session-XT7UiZ/lxqt-session-0.9.0.0.1+bzr245+201505301638~ubuntu15.04.1/lxqt-session/src/sessionapplication.cpp : 75 Session "session" about to launch (default 'session')
Environment variable GTK_CSD = 0
"/home/batmin/.config/lxqt/session.conf"
xrdb: Xcursor.theme:whiteglass
Xcursor.size:18
Xcursor.theme_core:true

Window Manager started
start "/etc/xdg/autostart/deja-dup-monitor.desktop"
start "/etc/xdg/autostart/lxqt-desktop.desktop"
start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
start "/etc/xdg/autostart/lxqt-notifications.desktop"
start "/etc/xdg/autostart/lxqt-panel.desktop"
start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
start "/etc/xdg/autostart/lxqt-runner.desktop"
start "/etc/xdg/autostart/nm-applet.desktop"
start "/etc/xdg/autostart/print-applet.desktop"
start "/etc/xdg/autostart/pulseaudio.desktop"
Failure: Module initialization failed
start "/etc/xdg/autostart/update-notifier.desktop"
start "/etc/xdg/autostart/zeitgeist-datahub.desktop"
System Tray started
start tray app "/etc/xdg/autostart/lxqt-powermanagement.desktop"
QXcbConnection: Failed to get the primary output of the screen
QXcbConnection: Failed to get the primary output of the screen
QXcbConnection: Failed to get the primary output of the screen
QXcbConnection: XCB error: 172 (Unknown), sequence: 816, resource id: 326, major code: 149 (Unknown), minor code: 20
QXcbConnection: XCB error: 172 (Unknown), sequence: 821, resource id: 326, major code: 149 (Unknown), minor code: 20
QXcbConnection: XCB error: 172 (Unknown), sequence: 826, resource id: 326, major code: 149 (Unknown), minor code: 20
```

I am using LXQt from this PPA:
https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily

The session type under X2Go Client is custom: `startlxqt`

I am using x2goserver & x2goserver-xsession 4.0.1.19 from the X2Go PPA.

I am using x2goclient 4.0.4.0 from the Ubuntu PPA. I upgraded nxproxy (and every other nx-libs package) to the same version that the server has. The client OS is ubuntu 14.04 64-bit.

I tried uninstalling these packages from the server, but it did not help. They merely provide files under /usr/share/doc anyway:
libnx-xrandr2 libnx-xrandr2-dbg libnx-xrandr-dev nx-x11proto-randr-dev

**Comment by sunweaver** [comment]
Hi Mike#2,

I have just today started looking at upgrading the randr extenion in  
nxagent to proto version 1.5.

The task is not trivial, but feasible. Other comments, see inline...

Mike

On  Mo 01 Jun 2015 07:18:52 CEST, Mike DePaulo wrote:

> I have an Ubuntu 15.04 64-bit test VM where I built nx-libs 3.6.x  
> from commit 4ed85e8 (2015-05-29), which is after PR #21 was merged.
> 
> However, RandR still appears to be at version 1.2.
> 
> ```
> batmin@ubuntu-v:~$ xrandr -v
> xrandr program version       1.4.1
> Server reports RandR version 1.2
> ```

It is indeed.

> Furthermore, LXQt (Using Qt 5.4.1) still fails to start / show up  
> correctly. OpenBox starts, and the lxqt-panel process is running.  
> However, immediately after connecting with X2Go Client and seeing  
> the X2Go logo, the panel appears to show up for a split-second, and  
> then disappears.

Ok...

> ([As discussed  
> here](http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=637), It is  
> believed that LXQt under Qt 5.4.x fails due it requiring a newer  
> version of RandR).
> 
> This is the output in .xsession-x2go-errors after I tried to start  
> the session, but it failed and I opened up a QTerminal (and  
> maximized the x2go session window):
> 
> ```
> XSession-x2go: X session started for batmin at Mon Jun  1 01:11:03 EDT 2015
> localuser:batmin being added to access control list
> openConnection: connect: No such file or directory
> cannot connect to brltty at :0
> 
> /etc/x2go/Xsession: 8: [: x: unexpected operator
> ```

What's the above error? That should not happen.

> QXcbConnection: Failed to get the primary output of the screen
> iconTheme "oxygen"
> iconTheme "oxygen"
> iconTheme "oxygen"
> iconTheme "oxygen"
> Theme: Cannot open file for reading:  
> "/usr/share/lxqt/themes/frost/lxqt-session.qss"
> QXcbConnection: Failed to get the primary output of the screen
> QXcbConnection: XCB error: 172 (Unknown), sequence: 162, resource  
> id: 326, major code: 149 (Unknown), minor code: 20
> QXcbConnection: XCB error: 172 (Unknown), sequence: 359, resource  
> id: 326, major code: 149 (Unknown), minor code: 20
> /build/lxqt-session-XT7UiZ/lxqt-session-0.9.0.0.1+bzr245+201505301638~ubuntu15.04.1/lxqt-session/src/sessionapplication.cpp : 75 Session "session" about to launch (default  
> 'session')
> Environment variable GTK_CSD = 0
> "/home/batmin/.config/lxqt/session.conf"
> xrdb: Xcursor.theme:whiteglass
> Xcursor.size:18
> Xcursor.theme_core:true
> 
> Window Manager started
> start "/etc/xdg/autostart/deja-dup-monitor.desktop"
> start "/etc/xdg/autostart/lxqt-desktop.desktop"
> start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
> start "/etc/xdg/autostart/lxqt-notifications.desktop"
> start "/etc/xdg/autostart/lxqt-panel.desktop"
> start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
> start "/etc/xdg/autostart/lxqt-runner.desktop"
> start "/etc/xdg/autostart/nm-applet.desktop"
> start "/etc/xdg/autostart/print-applet.desktop"
> start "/etc/xdg/autostart/pulseaudio.desktop"
> Failure: Module initialization failed
> start "/etc/xdg/autostart/update-notifier.desktop"
> start "/etc/xdg/autostart/zeitgeist-datahub.desktop"
> System Tray started
> start tray app "/etc/xdg/autostart/lxqt-powermanagement.desktop"
> QXcbConnection: Failed to get the primary output of the screen
> QXcbConnection: Failed to get the primary output of the screen
> QXcbConnection: Failed to get the primary output of the screen
> QXcbConnection: XCB error: 172 (Unknown), sequence: 816, resource  
> id: 326, major code: 149 (Unknown), minor code: 20
> QXcbConnection: XCB error: 172 (Unknown), sequence: 821, resource  
> id: 326, major code: 149 (Unknown), minor code: 20
> QXcbConnection: XCB error: 172 (Unknown), sequence: 826, resource  
> id: 326, major code: 149 (Unknown), minor code: 20
> 
> ```
> 
> I am using LXQt from this PPA:
> https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily
> 
> The session type under X2Go Client is custom: `startlxqt`
> 
> I am using x2goserver & x2goserver-xsession 4.0.1.19 from the X2Go PPA.
> 
> I am using x2goclient 4.0.4.0 from the Ubuntu PPA. I upgraded  
> nxproxy (and every other nx-libs package) to the same version that  
> the server has. The client OS is ubuntu 14.04 64-bit.
> ```

Thanks for all of the above info. That will help reproducing the issue  
and setting up a test setup.

> I tried uninstalling these packages from the server, but it did not  
> help. They merely provide files under /usr/share/doc anyway:
> libnx-xrandr2 libnx-xrandr2-dbg libnx-xrandr-dev nx-x11proto-randr-dev

Those packages are transitional packages merely, that should be removable via

   apt-get autoremove --purge

Mike

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by sunweaver** [comment]
This becomes more and more important as now the MATE upstream folks (for MATE 1.12) presume that the Xserver supports RandR proto version 1.3 at least.

**Comment by mikedep333** [comment]
Hi @sunweaver ,
- I no longer have access to the test VM.
- I wouldn't worry about

```
/etc/x2go/Xsession: 8: [: x: unexpected operator
```
- If need be, I can setup a new test VM for Ubuntu 15.04 through 16.04.
- This (MATE 1.12 incompatibility) is a huge problem in the Fedora world. MATE 1.12.1 is in EPEL7 testing right now. It's already been pushed to Fedora 22 and 23 as a stable release update.
- I will test EPEL7 (and Fedora 23) with MATE 1.12, X2Go and nx-libs 3.5.0.x right now. Assuming the test fails, I can at least provide negative karma for the EPEL7 update, and perhaps delay it by doing so.

**Comment by mikedep333** [comment]
@sunweaver I tested both distros: MATE 1.12 started fine. I didn't test MATE very thoroughly, but mate-session, mate-panel and marco are obviously working.

http://imgur.com/a/WX2m6

**Comment by sunweaver** [comment]
Hi Michael,

On  Sa 02 Jan 2016 17:27:23 CET, Mike DePaulo wrote:

> @sunweaver I tested both distros: MATE 1.12 started fine. I didn't  
> test MATE very thoroughly, but mate-session, mate-panel and marco  
> are obviously working.
> 
> http://imgur.com/a/WX2m6

The libxrandr >= 1.3 deps I spotted were in mate-power-manager and  
mate-screensaver.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by sunweaver** [comment]
Fixed since https://github.com/ArcticaProject/nx-libs/commit/17f3e3bc5157eeb6018ddaa6d862ca94f4b02b2b
