### ISSUE TITLE
more dependencies for specfile

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#481]
I have just tried to build an rpm on a fresh Centos6 machine. Running =yum-builddep= on the specfile installed lots of rpms but not =rpm-build=. I had to install that manually:

```
Installing:
 rpm-build                                       x86_64                               4.8.0-47.el6                                        dvdunion                               130 k
Installing for dependencies:
 elfutils                                        x86_64                               0.161-3.el6                                         dvdunion                               237 k
 gdb                                             x86_64                               7.2-83.el6                                          dvdunion                               2.3 M
 redhat-rpm-config                               noarch                               9.0.3-44.el6.centos                                 dvdunion                                59 k
```

**Comment by sunweaver** [comment]
uhm... no... In Debian, we have a set of packages that are called essential and build-essential. If Centos6 has a similar thing like the Debian meta package 'build-essential', I guess that rpm-build is on that list...

Adding rpm-build to our spec feels really wrong, so please don't do that. Please reconsider and possibly close this issue afterwards.

**Comment by uli42** [comment]
I am not aware of such a package (which does not necessarily mean that there is none)

This would have really been just a convenience addition, so we can leave that out. I just stumbled over it when I tried to build on a fresh machine.
