### ISSUE TITLE
RHEL6: git too old for make_changelog script

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#482]
```
root@centos6.7-std nx-libs # ./make-changelog.sh 
fatal: ambiguous argument '1970': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
```

```
root@centos6.7-std nx-libs # rpm -q git
git-1.7.1-3.el6_4.1.x86_64
```

-> Adapt `make_changelog.sh`? Leaving out the --since option would fix the problem.

**Comment by sunweaver** [comment]
The make-changelog script is for release managers only. (And I don't run ancient distros for development). Thus closing...

If you think it is needed, please provide a patch that checks the Git version and lets the script exit if Git's major version number is below 2.

**Comment by uli42** [comment]
I basically agree but from my POV there's no need for `--since "1970"` as this seems to resemble that default.

**Comment by sunweaver** [comment]
Hi,

On Tuesday, July 11, 2017, Ulrich Sibiller wrote:
> I basically agree but from my POV there's no need for --since "1970" as this seems to resemble that default. 

IIRC, git would truncate the changelog to the last two years or such. I remember having issues like that which got solved with --since 1970...

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by uli42** [comment]
Have not seen this anywhere in the git log manpage. Also my git 2.9.3 goes down to the very first commit when called without --since.
