### ISSUE TITLE
remove libXinerama from build

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#49]
I have stumbled over this commit: http://cgit.freedesktop.org/xorg/xserver/commit/?id=2c69deb92e11542f615df0f24fdc03e3b4415475

I think we should include that into 3.6.x to simplify the build process.

commit 2c69deb92e11542f615df0f24fdc03e3b4415475
Author: Rémi Cardona remi@gentoo.org
Date:   Fri Jul 3 10:51:50 2009 +0200

```
configure: libXinerama isn't needed anymore

since libXinerama commit 90d4d23bf2e94721149ddc0a80093b10a82e8845 and
xineramaproto commit 21477147613c28c968b5e1eb9d8aea7017dd399d, the
server no longer needs libXinerama.

Signed-off-by: Rémi Cardona <remi@gentoo.org>
```

**Comment by uli42** [comment]
The following commit is doing the same for libXfont:

http://cgit.freedesktop.org/xorg/xserver/commit/dix/dixfonts.c?id=a00066d2916b6910429cc1c7feedafbaee0d4750

**Comment by Ionic** [comment]
Commits in question: [libXinerama](http://cgit.freedesktop.org/xorg/lib/libXinerama/commit/?id=90d4d23bf2e94721149ddc0a80093b10a82e8845), [xineramaproto](http://cgit.freedesktop.org/xorg/proto/xineramaproto/commit/?id=21477147613c28c968b5e1eb9d8aea7017dd399d)

We should revisit this once the current cleanups PR's are through, thanks!
