### ISSUE TITLE
Fails to build on CentOS 7

### ISSUE THREAD

**Issue by 4nanook** [ArcticaProject/nx-libs#510]
Build fails on Centos 7:
[build-log.txt](https://github.com/ArcticaProject/nx-libs/files/1289487/build-log.txt)

**Comment by sunweaver** [comment]
This is not a problem with nx-libs, your error is this:

```
error: File /builddir/build/SOURCES/nx-libs-3.5.99.9.tar.gz: No such file or directory
```

**Comment by 4nanook** [comment]
If that does not come from the build where does it come from

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by sunweaver** [comment]
Hi Robert,

On  Do 14 Sep 2017 20:28:14 CEST, Robert Dinse wrote:

> If that does not come from the build where does it come from
>

It is a problem with your mock setup. You need to provide the tarball  
for nx-libs 3.5.99.9 to mock "somehow" (beyond my knowledge, maybe  
@Ionic knows).

It certainly is a mock setup problem on your side.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by 4nanook** [comment]
I only followed the build instructions verbatim.  Mock is that which is
supplied by yum install mock.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by Ionic** [comment]
The instructions are (mostly) fine. Some stuff like applying patches is missing though and the version numbers will have to be adjusted, which you probably haven't done correctly. The build instructions are not to be taken "verbatim".

Make sure to `yum install quilt` first.

Something a bit more generic:
```sh
cd "${HOME}"
typeset temp_dir="$(mktemp -d --tmpdir="${HOME}/tmp" "tmp.XXXXXXXXXXXXXXXXXXXXXXXXXX")"
cd "${temp_dir}"
mkdir "git-clone" "srpm-staging" "srpm-result" "rpm-result"
pushd "git-clone"
git clone https://github.com/ArcticaProject/nx-libs.git
pushd "nx-libs"
rm -rf ".git"
QUILT_PATCHES="debian/patches" quilt push -a && rm -Rf -- ".pc/"
typeset upstream_version="$(grep -E -- "^Version:.*" "nx-libs.spec" | awk '{ print $2 }')"
cp -av "nx-libs.spec" "../../srpm-staging/"
popd
mv "nx-libs" "nx-libs-${upstream_version}"
tar -czf "../srpm-staging/nx-libs-${upstream_version}.tar.gz" "nx-libs-${upstream_version}"
rm -rf "nx-libs-${upstream_version}"
popd
mock --buildsrpm --spec "srpm-staging/nx-libs.spec" --sources "srpm-staging/" --resultdir "srpm-result/"
mock --resultdir "rpm-result" "srpm-result/"*".src.rpm"
```

**Comment by 4nanook** [comment]
Thanks, will give it a try.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
