### ISSUE TITLE
no more history for libX11?

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#520]
looking at the source files in nx-X11/lib/src/ I can see no git history anymore. Has history been dropped on purpose in commit c350873c7c977efe5210484f04160be45f84ba7e ?

**Comment by Ionic** [comment]
No, as said on IRC, it's just git not recognizing the file renames correctly or something like that. I did also notice that, but there's nothing we can do about this.

The history is still there - although more difficult to get to. Essentially, get the old location from commit c350873c7c977efe5210484f04160be45f84ba7e and use `git log -- old/file/path` (or any other command) to get the previous history. Not the best solution, but we can't make git smarter. It obviously recognized the rename within the commit, but does not apply it to the history for some reason.

**Comment by uli42** [comment]
using `git log --follow` one can still see the history
