### ISSUE TITLE
add auto-generated files to .gitignore/make clean

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#523]
```
nx-X11/config/cf/date.def 
nx-X11/config/cf/nxversion.def 
nx-X11/config/cf/version.def 
nx-X11/extras/Mesa_6.4.2/.pc/
```

should be added to .gitignore (and probably make clean, too)

**Comment by Ionic** [comment]
> ```
>nx-X11/config/cf/date.def 
>nx-X11/config/cf/nxversion.def
>```

Both handled by our top-level `Makefile`. Nothing to do.

>```
>nx-X11/config/cf/version.def
>```

I can't find any location where this file might be generated. Could this be some non-Arctica leftover? I do see `version.def` showing up in the old X2Go 3.5.0.x builds, but nothing in the modern version.

>```
>nx-X11/extras/Mesa_6.4.2/.pc/
>```

Is removed via the "Mesa" symlink in our top-level `Makefile`. Nothing to do.
