### ISSUE TITLE
PANIC! No port specified for multimedia connections.

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#525]
@vtq:
```
Loop: WARNING! Overriding auxiliary X11 port with new value '1'.
Loop: PANIC! No port specified for multimedia connections.
```

Currently, nxproxy does not come up due to the above error being thrown.

**Comment by vatral** [comment]
Looking into it.

**Comment by sunweaver** [comment]
On  Di 10 Okt 2017 10:11:37 CEST, Vadim Troshchinskiy wrote:

> Looking into it.

THANKS!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
