### ISSUE TITLE
nxproxy should _not_ honor $TEMP for the X11 socket

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#536]
If `TEMP` is set to anything other then `/tmp` nxproxy will try to find the X servers's socket there. IMHO this is wrong:
```
$ TEMP=dummy strace nxproxy -C :40
...
bind(6, {sa_family=AF_LOCAL, sun_path="dummy/.X11-unix/X40"}, 110) = -1 ENOENT (No such file or directory)
...
```
Clients using the system's libX11/libxcb are depending on the socket being at a predictable location so it must not depend on any local variable.

It is probably this code in `nxcomp/src/Loop.cpp` that causing this. Right before these lines the path is hardcoded for linux, but overwritten afterwards:
```
   4227     struct stat statInfo;
   4228 
   4229     char unixSocketDir[DEFAULT_STRING_LENGTH];
   4230 
   4231     snprintf(unixSocketDir, DEFAULT_STRING_LENGTH - 1, "%s/.X11-unix",
   4232                  control -> TempPath);
   4233 
```

Maybe caused by this commit: aaf4a59e4c4ec54a26283bce6bf25281e12f0424

**Comment by Ionic** [comment]
No, that has been standard NX behavior.

`GetTempPath()` always used to check `NX_TEMP`, then `TEMP` and lastly default to `/tmp`.

I agree that in concert with `pam_tmpdir`, which sets `TMP`, `TEMP`, `TMPDIR` and `TEMPDIR`, the socket location will be broken if we keep the `TEMP` override, so I'm okay with removing it.

This said, I want to make sure that the `tmpDir` class variable is not used for anything else that we would break with removing this override.

I'd like to keep the `NX_TEMP` override in any case, since this should normally not get in our way.

**Comment by sunweaver** [comment]
Hi,

On  Do 19 Okt 2017 12:13:09 CEST, Mihai Moldovan wrote:

> No, that has been standard NX behavior.
>
> `GetTempPath()` always used to check `NX_TEMP`, then `TEMP` and  
> lastly default to `/tmp`.
>
> I agree that in concert with `pam_tmpdir`, which sets `TMP`, `TEMP`,  
> `TMPDIR` and `TEMPDIR`, the socket location will be broken if we  
> keep the `TEMP` override, so I'm okay with removing it.
>
> This said, I want to make sure that the `tmpDir` class variable is  
> not used for anything else that we would break with removing this  
> override.
>
> I'd like to keep the `NX_TEMP` override in any case, since this  
> should normally not get in our way.

Please note, that x2goagent and x2goserver handle pam_tmpdir fairly well.

This was introduced around the release of nx-libs 3.5.0.15.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment]
Yes, since the wrapper scripts set `NX_TEMP` to `/tmp` explicitly if not already set, overriding whatever `pam_tmpdir` supplies via `TEMP`. The problem shows up on systems where our wrapper scripts for `nxproxy` or `nxagent` are not used (for instance in the Ubuntu version of `nxproxy`, that installs the binary directly into `/usr/bin/`).

**Comment by uli42** [comment]
I'd say use only the fixed path for the socket. Nothing else, never.
If nx is to be compiled on a system that uses a different path, the
packager must adapt the hardcoded path anyway.

**Comment by Ionic** [comment]
I like to retain an override capability via `NX_TEMP`. This won't be accidentally set, so we're clear. I'll remove the `TEMP` override for some calls (like connecting the X11 socket.)

**Comment by uli42** [comment]
Once again: The only situation where you can use the socket at a
different location would be a system where libX11/libxcb and the X
server were _compiled_ to use a different location. _Only_ on such a
system you would need to adapt nxcomp as well.  Besides: if for some
completely unrelated reason NX_TEMP gets set in wrapper scripts we'll
face the same problem again.

So there's no sense in making that tweakable via NX_TEMP.

**Comment by sunweaver** [comment]
In nxcomp, the GetTempPath() function is used to populate ``control -> TempPath``.

And ``control -> TempPath`` is used for two purposes. 

  1. defining where to find X11 sockets (/tmp/.X11-unix)
  1. defining where to put cache dumps (see Proxy.cpp)

As UNIX_DIR and UNIX_PATH are really hard-coded in libxtrans/Xtranssock.c, we should really not allow the user to tinker with this path. Atmost, the UNIX_DIR/UNIX_PATH could become a build time option in nxcomp's configure.ac. But I really don't think that this is necessary.

For the second use case (cache dumping), we should keep the NX_TEMP variable.

@Ionic: do you see any use case for having NX_TEMP affect the UNIX__DIR/UNIX_PATH settings? The only use case I see is forwarding those socket streams through some application. However, this is not really possible, as on Linux systems at least, the UNIX_PATH on the file system is only rarely used and the traffic goes through the Kernel's abstract socket provisioning by default (if available).

**Comment by uli42** [comment]
Looks like this in incomplete,  I just stumbled over this code in nx-X11/lib/include/Xtranssock.c:
```
ifdef NX_TRANS_SOCKET
/*
 * Override the UNIX_DIR and UNIX_PATH settings and
 * make them configurable, based on the NX_TEMP or
 * the TEMP environment.
 *
 * We must be careful as the same defines are used
 * for different directories, based on the subsystem
 * that is compiling this, while we want to override
 * only the '/tmp/.X11-unix' and '/tmp/.X11-unix/X'
 * settings.
 */

static char _NXUnixDir[1024];
static char _NXUnixPath[1024];

static char *_NXGetUnixDir(char *dir)
{
    const char *tempDir;

    prmsg (3, "_NXGetUnixDir(%s)\n", dir);

    if (strcmp(dir, UNIX_DIR) != 0)
    {
#ifdef NX_TRANS_TEST
        fprintf(stderr, "_NXGetUnixDir: Returning other Unix directory [%s].\n", dir);
...
```

**Comment by Ionic** [comment]
Hmm, I may have overlooked this, must investigate again.
