### ISSUE TITLE
How to use meta/super character?

### ISSUE THREAD

**Issue by vonpupp** [ArcticaProject/nx-libs#580]
Hi,

I am using x2goserver which uses nxlibs. I am using awesomewm which uses the meta/super key for many things, i.e: `meta+1` to move to virtual desktop 1 and so forth, `meta+enter` to open a terminal, among other combinations.

When I use x2goclient to log to another awesomewm server I would like to be able to issue the same `meta` commands for the server I am logged into.

Is this currently possible? I found [this stackoverflow quesion], but the answer is pointing to #384 which seems a bit unrelated to me.

Thank you very much.

[this stackoverflow quesion]: https://unix.stackexchange.com/questions/304894/how-to-make-x2go-s-windows-get-focus-on-click

**Comment by uli42** [comment]
Autograb is exactly the feature you need. Unfortunately it is incomplete
regarding fullscreen handling. Plus you have to Compiler it yourself.

Uli

Am 02.12.2017 21:04 schrieb "Vonpupp" <notifications@github.com>:

**Comment by vonpupp** [comment]
Thanks @uli42,

Since it seems to be an already planned feature, I will close this issue. Feel free to reopen it if you see it necessary.

Best regards.
