### ISSUE TITLE
Major memory leak seems pixmap-related as of e54e42a

### ISSUE THREAD

**Issue by mbecroft** [ArcticaProject/nx-libs#596]
From this version (setting aside issues with the asprintf pull) there is a huge memory leak in which nxagent can easily grow to 10's of gigabytes in size within seconds.

Easiest way to reproduce is: login to an nxagent session. Run the following command:

glxgears

while this is running, examine memory usage of nxagent using the top command. It will increase after every frame, at a rate of about 1 gigabyte per 10 seconds.

The issue also occurs with any other X clients sending a lot of pixmaps to the X server. Google Chrome is a prime example. Every time you scroll the window it will send a new pixmap. Simply scrolling a web page up and down will lead nxagent to grow by about 200 megabytes per 10 seconds.

**Comment by Ionic** [comment]
The memory leakage is definitely related to the new logging code and I pretty much know why. We've never releasing data in the buffer for messages that have a higher log level than what should be printed out.

I've given Mario a stopgap workaround and will look into this more closely at a later point and fix the issue.

**Comment by mbecroft** [comment]
Thanks a lot to Ionic, I'm about to try here with the workaround. I can't believe that nobody detected this earlier, it's just about impossible to miss if you are doing more than running an xterm in your nxagent!

**Comment by uli42** [comment]
interestingly it was not that obvious in my tests, maybe because I was using -d4 for nxproxy
