### ISSUE TITLE
custom version string

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#606]
I would like to have a way to use a custom version number to nxagent and nxproxy because I am redistributing an own version of nx in the company I work at and need to give it an internal version. Currently building will always construct the version string from the latest git tag which is not helping if your are compiling HEAD.

So I would like to pass an additional custom string to the make run that replaces the version string in nxagent and nxproxy.

e.g. 

```
NXAGENT - Version 3.5.99.10-custom1
```

**Comment by sunweaver** [comment]
Hi Uli,

On Thursday, December 14, 2017, Ulrich Sibiller wrote:
> I would like to have a way to use a custom version number to nxagent and nxproxy because I am redistributing an own version of nx in the company I work at and need to give it an internal version. Currently building will always construct the version string from the latest git tag which is not helping if your are compiling HEAD.
> So I would like to pass an additional custom string to the make run that replaces the version string in nxagent and nxproxy.
> e.g.
> NXAGENT - Version 3.5.99.10-custom1

Please add a buildtime option / variable and pass it on to imake and autotools via the main Makefie.

Thanks for working on this!
Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by uli42** [comment]
I already have, but I am not happy with it. I will upload it later today.

Am 14.12.2017 17:01 schrieb "Mike Gabriel" <notifications@github.com>:

**Comment by uli42** [comment]
it is quite easy to run make NX_VERSION_CUSTOM=bla and let nxagent show that version. But I am failing in passing down that variable to nxcomp. Any ideas how to achieve that?

See #607
