### ISSUE TITLE
printver.c is gone but not forgotten

### ISSUE THREAD

**Issue by opoplawski** [ArcticaProject/nx-libs#63]
I get:

```
cd nx-X11 && make World
make[2]: Entering directory '/export/home/orion/fedora/nx-libs/nx-libs-HEAD/nx-X11'
cc: error: ./config/util/printver.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
Makefile:46: recipe for target 'World' failed
make[2]: [World] Error 4 (ignored)
```

printver.c does not appear to exist but is referenced in:
./nx-libs-arctica/nx-X11/Makefile:VERSSRC = $(CONFIGSRC)/util/printver.c
./nx-libs-arctica/debian/copyright.in: nx-X11/config/util/printver.c

**Comment by sunweaver** [comment]
@opolawski: Thanks for notifying us on this. Will take a look during the next days...
