### ISSUE TITLE
interesting reconnect problem

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#635]
(I have an nxagent 3.5.99.12 with DEBUG and TEST set) 

(I have cookies in XAUTHORITY for display :55, so I don't need to specify one here)

1. `Xephyr :33`
2. `DISPLAY=:33 nxagent :55` -> works, but prints these:
```
nxagentInitDepths: Got [7] available depths:
 [1] [4] [8] [15] [16] [24] [32].
nxagentInitPixmapFormats: Set format [0] to depth [1] bits per pixel [1] scanline pad [32].
nxagentInitPixmapFormats: Set format [1] to depth [4] bits per pixel [8] scanline pad [32].
nxagentInitPixmapFormats: Set format [2] to depth [8] bits per pixel [8] scanline pad [32].
nxagentInitPixmapFormats: Set format [3] to depth [15] bits per pixel [16] scanline pad [32].
nxagentInitPixmapFormats: Set format [4] to depth [16] bits per pixel [16] scanline pad [32].
nxagentInitPixmapFormats: Set format [5] to depth [24] bits per pixel [32] scanline pad [32].
nxagentInitPixmapFormats: Set format [6] to depth [32] bits per pixel [32] scanline pad [32].
nxagentInitPixmapFormats: Got [7] available remote pixmap formats:
nxagentInitPixmapFormats: Remote pixmap format [0]: depth [1] bits_per_pixel [1] scanline_pad [32].
nxagentInitPixmapFormats: Remote pixmap format [1]: depth [4] bits_per_pixel [4] scanline_pad [32].
nxagentInitPixmapFormats: Remote pixmap format [2]: depth [8] bits_per_pixel [8] scanline_pad [32].
nxagentInitPixmapFormats: Remote pixmap format [3]: depth [15] bits_per_pixel [16] scanline_pad [32].
nxagentInitPixmapFormats: Remote pixmap format [4]: depth [16] bits_per_pixel [16] scanline_pad [32].
nxagentInitPixmapFormats: Remote pixmap format [5]: depth [24] bits_per_pixel [32] scanline_pad [32].
nxagentInitPixmapFormats: Remote pixmap format [6]: depth [32] bits_per_pixel [32] scanline_pad [32].
nxagentCheckForPixmapFormatsCompatibility: WARNING! Tolerance [0] too low and failed to match internal pixmap format (depth [4] bpp [8] pad [32]).
nxagentCheckForPixmapFormatsCompatibility: WARNING! Internally available pixmap formats [7] don't match with external pixmap formats [7] at tolerance [0]. Only [6] depth values matched.
```
The nxagent runs anyway and is usable.
3. `kill -HUP ($pidof nxagent)` -> nxagent suspends
4. `kill -HUP ($pidof nxagent)` -> nxagent tries to "reconnect", but fails:
```
nxagentCheckForPixmapFormatsCompatibility: WARNING! Tolerance [0] too low and failed to match internal pixmap format (depth [4] bpp [8] pad [32]).
nxagentCheckForPixmapFormatsCompatibility: WARNING! Internally available pixmap formats [7] don't match with external pixmap formats [7] at tolerance [0]. Only [6] depth values matched.
nxagentReconnect: WARNING! Failed display reconnection.
nxagentReconnect: Reconnection failed in display step. Restoring options.
nxagentReconnect: Reconnection failed with reason 'Couldn't restore all the required pixmap formats.'
```

A reconnect should be possible since the underlying system has not changed. nxagent is still running on the same Xephyr.

**Comment by uli42** [comment]
today I have experienced the same with Xnest. 

The problem is that after startup nxagent's nxagentNumPixmapFormats is 2 DESPITE xdpyinfo showing 7. At reconnect it is still 2 but nxagentRemoteNumPixmapFormats is 7. And  nxagentCheckForPixmapFormatsCompatibility() with mode "strict" fails id the numbers to not match.

**Comment by uli42** [comment]
Using =tolerance=safe= makes it work. Maybe we should set the default to =safe= instead of =strict=.

**Comment by uli42** [comment]
Xnest and Xephyr show

```
  depths (2):    1, 24
```
and
```
number of supported pixmap formats:    7
supported pixmap formats:
    depth 1, bits_per_pixel 1, scanline_pad 32
    depth 4, bits_per_pixel 8, scanline_pad 32
    depth 8, bits_per_pixel 8, scanline_pad 32
    depth 15, bits_per_pixel 16, scanline_pad 32
    depth 16, bits_per_pixel 16, scanline_pad 32
    depth 24, bits_per_pixel 32, scanline_pad 32
    depth 32, bits_per_pixel 32, scanline_pad 32
```
(note there are pixmap formats whose depth is greater than the supported depths.

nxagent internally filters the pixmap formats it supports by the depths it supports, and it gets 2 depths from the remote X server (Xnest/Xephyr). The outcome is that only 2 of the 7 pixmap formats make it to the internal list of pixmap formats. But the the remote list is not filtered and therefore contains all 7 pixmap formats which then will fail for the "strict" compatibility test.

I am a bit unsure if Xnest has a bug here or not.

**Comment by Ionic** [comment]
Using `safe` makes sure that all pixmap formats used on the server side are also understood on the remote side, while the `strict` check requires all to match.

`safe` could be an okay default, but we've used `strict` without huge issues for a long time.

Filtering out formats from the remote side's list sounds like a bad idea because it makes the `strict` behavior useless (i.e., it would pretty much degrade it to the `safe` test).

I'd lean towards an Xnest/Xephyr bug.

**Comment by uli42** [comment]
Yes, I basically agree. But what's the point in strictly checking for remote pixmap formats we are never using in nxagent?

Besides, in theory the initial X server could offer multiple pixmap formats per depth while the Xserver at reconnect does not (or vice versa). In that case the filtering would produce different results and the strict check would detect that!
