### ISSUE TITLE
Xinerama bounding box issue

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#662]
Try this...

  * do this on a system with only one output head!!! Like a notebook.

  * start nxagent in windowed desktop mode
  * start LXDE, MATE, XFCE inside
  * move the nxagent window to the left of the screen, so parts of it are outside the visible area
  * resize the window
  * watch the desktop's panel and everything else
  * move the nxagent window back into the visible area

-> The left part that was invisible while resizing has been "split off" from the rest of the agent's desktop session.

-> Same pattern works when moving the nxagent window outside the top visible area of the real Xservers output.

**Comment by uli42** [comment]
I have played around and found a possible fix. However, I must rethink about what is happening here exactly. Can you please check if this patch fixes the issue for you?

```
diff --git a/nx-X11/programs/Xserver/hw/nxagent/Screen.c b/nx-X11/programs/Xserver/hw/nxagent/Screen.c
index d4a083a..94f637e 100644
--- a/nx-X11/programs/Xserver/hw/nxagent/Screen.c
+++ b/nx-X11/programs/Xserver/hw/nxagent/Screen.c
@@ -112,8 +112,8 @@ is" without express or implied warranty.
 
 #define PANIC
 #define WARNING
-#undef  TEST
-#undef  DEBUG
+#define  TEST
+#define  DEBUG
 #undef  WATCH
 #undef  DUMP
 
@@ -4179,6 +4179,7 @@ int nxagentAdjustRandRXinerama(ScreenPtr pScreen)
             refcnt by 1. We decrease it again by calling only
             RRModeDestroy() and forget about prevmode */
          RRModeDestroy(mymode);
+          RRCrtcSet(pScrPriv->crtcs[i], mymode, new_x, new_y, RR_Rotate_0, 1, &(pScrPriv->outputs[i]));
         }
         else
        { 
```

**Comment by sunweaver** [comment]
Hi Uli,

On  Di 27 Feb 2018 23:48:37 CET, Ulrich Sibiller wrote:

> I have played around and found a possible fix. However, I must  
> rethink about what is happening here exactly. Can you please check  
> if this patch fixes the issue for you?
>
> diff --git a/nx-X11/programs/Xserver/hw/nxagent/Screen.c  
> b/nx-X11/programs/Xserver/hw/nxagent/Screen.c
> index d4a083a..94f637e 100644
> --- a/nx-X11/programs/Xserver/hw/nxagent/Screen.c
> +++ b/nx-X11/programs/Xserver/hw/nxagent/Screen.c
> @@ -112,8 +112,8 @@ is" without express or implied warranty.
>
>  #define PANIC
>  #define WARNING
> -#undef  TEST
> -#undef  DEBUG
> +#define  TEST
> +#define  DEBUG
>  #undef  WATCH
>  #undef  DUMP
>
> @@ -4179,6 +4179,7 @@ int nxagentAdjustRandRXinerama(ScreenPtr pScreen)
>              refcnt by 1. We decrease it again by calling only
>              RRModeDestroy() and forget about prevmode */
>           RRModeDestroy(mymode);
> +          RRCrtcSet(pScrPriv->crtcs[i], mymode, new_x, new_y,  
> RR_Rotate_0, 1, &(pScrPriv->outputs[i]));
>          }
>          else
>         {

Nope, this is not the expected behaviour. With your patch above the  
session window behaves as if NXAGENT_RANDR_XINERAMA_CLIPPING is defined.

The expected result should be:

   * I move the nxagent window partly out of the real Xserver's  
visible area (to the left or up)
   * I resize the nxagent window (bottom right corner)
   * the inner session inside nxagent resizes as if the nxagent window  
had been fully visible
     - the lower right part of the session adapts)
     - the top left part stays as is

With your patch, the top left part adjust and "jumps" into the visible  
area of the real Xserver, although great portions of the nxagent  
window are in the invisible area.

Mike


-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Can you provide some screenshots to ensure I understand correctly? From
your explanation I am still thinking that y patch fixes exactly that.

Am 28.02.2018 11:36 schrieb "Mike Gabriel" <notifications@github.com>:

**Comment by sunweaver** [comment]
Hi Uli,

the below patch fixes things for me on a 1-output system.

```
diff --git a/nx-X11/programs/Xserver/hw/nxagent/Screen.c b/nx-X11/programs/Xserver/hw/nxagent/Screen.c
index d4a083a1b..266f01742 100644
--- a/nx-X11/programs/Xserver/hw/nxagent/Screen.c
+++ b/nx-X11/programs/Xserver/hw/nxagent/Screen.c
@@ -113,7 +113,7 @@ is" without express or implied warranty.
 #define PANIC
 #define WARNING
 #undef  TEST
-#undef  DEBUG
+#define DEBUG
 #undef  WATCH
 #undef  DUMP
 
@@ -3690,6 +3690,15 @@ Bool intersect_bb(int ax1, int ay1, unsigned int aw, unsigned int ah,
         #endif
        *h = ah;
     }
+
+    /* Don't allow the top left corner to have negative coordinates */
+    if (ax1 < bbx1) {
+       *x = 0;
+    }
+    if (ay1 < bby1) {
+       *y = 0;
+    }
+
   }
 
   return result;
```

I need to fire up my dual head system and check it there. Can you also test? It would be nice, getting this fixes for Ubuntu 18.04 (which means: today before 21.00 UTC)

**Comment by Ionic** [comment]
Coordinates might be negative in multi-display setups with the origin (0,0) being on the primary display. (That's the case on Windows IIRC, no idea how X.Org handles this.)

Be careful with that.

**Comment by Ionic** [comment]
When testing, make sure to put the primary display on both the left and right hand side of the secondary displays (plus for the y axis top/bottom).

**Comment by sunweaver** [comment]
Hi,

On  Do 01 Mär 2018 08:27:54 CET, Mihai Moldovan wrote:

> Coordinates might be relative in multi-display setups with the  
> origin (0,0) being on the primary display. (That's the case on  
> Windows IIRC, no idea how X.Org handles this.)
>
> Be careful with that.

Those coordinates are coordinates in the NX session AFAIU.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
Highly improbable that I can look at this today before 9pm, sorry

Am 01.03.2018 08:24 schrieb "Mike Gabriel" <notifications@github.com>:

**Comment by uli42** [comment]
I doubt the change being at the correct location. Intersect is a general
purpose function. It should be replaced by x11 box functions.

Am 01.03.2018 08:54 schrieb Ulrich Sibiller <uli42@gmx.de>:

**Comment by uli42** [comment]
I have checked what's happening again: The existing code tries to cover cases where part of the window is outside the visible area, and it does that fine. But it fails to do so for the resizing case.
