### ISSUE TITLE
FTBFS on Fedora rawhide/pre-28: fatal error: rpc/rpc.h: No such file or directory

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#665]
In nxagent... 

```
rpcauth.c:47:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by Ionic** [comment]
I'm aware of this.

This needs more work, I've committed some initial one in 6449b554837e0c8c566a00a7342fd787711d57ca, but more code changes are necessary since tirpc is not a direct drop-in replacement for the deprecated SUN-RPC glibc headers.

**Comment by sunweaver** [comment]
https://fedoraproject.org/wiki/Changes/SunRPCRemoval

**Comment by sunweaver** [comment]
oha... then we should revert my recent commit on nx-libs.spec.

**Comment by sunweaver** [comment]
From the above document, I don't see anything about ABI/API changes.

**Comment by Ionic** [comment]
Your recent commit is already included in nx-libs.spec... and since it's been there for a few weeks already, but the builds are still not working, it needs other changes.

Hopefully/mostly just adding the `tirpc/` prefix to the include path for some distro versions, but I'll have to try and see how that goes.

I'll work on it eventually, but this isn't a highly pressing issue for me right now since only Fedora Rawhide is affected currently.

**Comment by mjtrangoni** [comment]
@sunweaver I was compiling today on F29, and found that this isn't working with a simple `make` call. OTOH, it is working perfectly when the `nx-libs.spec` is used building RPMs.
 
What is the status here? Shouldn't this be checked automatically? Why is it still built by **imake**, and not by **autotools**? I saw you have started porting this [here](https://github.com/sunweaver/nx-libs/tree/pr/xserver-autotools).

**Comment by sunweaver** [comment]
Hi,

On  So 27 Jan 2019 17:29:30 CET, Mario Trangoni wrote:

> @sunweaver I was compiling today on F29, and found that this isn't  
> working with a simple `make` call. OTOH, it is working perfectly  
> when the `nx-libs.spec` is used building RPMs.
>
> What is the status here? Shouldn't this be checked automatically?  
> Why is it still built by **imake**, and not by **autotools**? I saw  
> you have started porting this  
> [here](https://github.com/sunweaver/nx-libs/tree/pr/xserver-autotools).

the porting has stalled mostly due to lack of time / prio. I heard on  
IRC that @mbecroft plans to start looking into the autotools porting.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
No, not mbecroft but Mario Trangoni

**Comment by mjtrangoni** [comment]
@sunweaver yes, I am looking into the autotools for nx-X11, following your branch, and some @uli42 changes. I think this would be fixing this issue, and also some places where the variables **CC** does not propagate correctly.

**Comment by sunweaver** [comment]
Hi

On  Sa 02 Feb 2019 14:59:06 CET, Mario Trangoni wrote:

> @sunweaver yes, I am looking into the autotools for nx-X11,  
> following your branch, and some @uli42 changes. I think this would  
> be fixing this issue, and also some places where the variables  
> **CC** does not propagate correctly.

@mjtrangoni: ahhh.. then this was a misunderstanding. From @uli42 I  
understood that @mbecroft (also Mario with firstname) is doing the  
autotools work. But it is you!

Awesome!!! Let me know if you need anything that @uli42 cannot provide.

Greets + Thanks,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
