### ISSUE TITLE
nxagent crashes when moving the session window into another screen

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#677]
I have played with a Xinerama setup with unequal outputs today.

I observed nxagent crashes regularly, whenever I moved thr agent window into the other outout. The crashes always occurred once the window was completely in the other output.

While the agent window was half on this, half on that output, no crash. Window fully moved over... Boom.

This was on i3's window manager...

**Comment by uli42** [comment]
Hmm this works for me with kwin

Mike Gabriel <notifications@github.com> schrieb am Fr., 9. März 2018, 20:35:

**Comment by ngaywood** [comment]
I'm seeing this as well on Fedora 27.  Happened after these (among others) updates:
nxproxy-3.5.99.15-0.0build1.1.git20180308.2971.main.fc27.x86_64 Mon 12 Mar 2018 09:14:38 AEDT
nxagent-3.5.99.15-0.0build1.1.git20180308.2971.main.fc27.x86_64 Mon 12 Mar 2018 09:14:38 AEDT
libXcompshad3-3.5.99.15-0.0build1.1.git20180308.2971.main.fc27.x86_64 Mon 12 Mar 2018 09:14:37 AEDT
libXcomp3-3.5.99.15-0.0build1.1.git20180308.2971.main.fc27.x86_64 Mon 12 Mar 2018 09:14:36 AEDT
libNX_X11-6-3.5.99.15-0.0build1.1.git20180308.2971.main.fc27.x86_64 Mon 12 Mar 2018 09:14:36 AEDT
nx-libs-3.5.99.15-0.0build1.1.git20180308.2971.main.fc27.x86_64 Mon 12 Mar 2018 09:14:35 AEDT

And it does not seem possible to roll-back

**Comment by uli42** [comment]
I can confirm this, here's the backtrace:

#0  0x000055db185705fb in nxagentMoveCorruptedRegion (pWin=pWin@entry=0x55db1a9b2b30, mask=mask@entry=131072) at Drawable.c:1797
#1  0x000055db1857733b in nxagentConfigureWindow (pWin=0x55db1a9b2b30, mask=131072) at Window.c:1312
#2  0x000055db18577918 in nxagentFlushConfigureWindow () at Window.c:3510
#3  0x000055db185652a7 in nxagentBlockHandler (data=<optimized out>, timeout=0x7ffd08a050f8, mask=<optimized out>) at Handlers.c:285
#4  0x000055db1853386d in BlockHandler (pTimeout=pTimeout@entry=0x7ffd08a050f8, pReadmask=pReadmask@entry=0x55db18b29ba0 <LastSelectMask>) at dixutils.c:403
#5  0x000055db1853da7a in WaitForSomething (pClientsReady=pClientsReady@entry=0x55db1ac12d50) at WaitFor.c:244
#6  0x000055db1850cdaf in Dispatch () at NXdispatch.c:360
#7  0x000055db184f0a0b in main (argc=16, argv=0x7ffd08a05478, envp=<optimized out>) at main.c:353


<s>Interestingly this is only happening in x2go, not when nxagent is running standalone. It is crashing at the same location #679 does.</s> Update: Used the wrong binaries. With the ones of x2go the testscript and the standalone run show the same crash.

**Comment by uli42** [comment]
Interestingly I can provoke this on my two-monitor setup on Ubuntu 16.04 when using x2goclient and connect to localhost (starting a new desktop session with /usr/bin/xterm as the desktop enviroment). Running an nxagent standalone or via =testscripts/run-nxproxy2nxagent-on-localhost= (original or modified to use the same options as in the x2go case) does not provoke the behaviour.

Update: Used the wrong binaries. With the ones of x2go the testscript and the standalone run show the same crash.

**Comment by sunweaver** [comment]
Hi Uli,

On Wednesday, March 14, 2018, Ulrich Sibiller wrote:
> Interestingly I can provoke this when using x2goclient and connect to localhost (starting a new desktop session with /usr/bin/xterm as the desktop enviroment). Running an nxagent standalone or via =testscripts/run-nxproxy2nxagent-on-localhost= (original or modified to use the same options as in the x2go case) does not provoke the behaviour. 

This is indeed very interesting and explains while I failed to spot the issue during all my tests while working on the bounding box patch.

Hmmm...

Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by Ionic** [comment]
I haven't been able to reproduce this with an Ubuntu 16.04 VM (both as client and server) with two emulated displays using spice.

nxagent never crashed on me, and I have been resizing and dragging like crazy.

**Comment by ngaywood** [comment]
@Ionic Were the 2 emulated displays of different size? It seems this might be a requirement for a crash.

**Comment by Ionic** [comment]
No, they weren't. Different sizes make nxagent crash indeed. Looking into it.

**Comment by Ionic** [comment]
@ngaywood please test the current X2Go nightly packages on your dev box and see if that issue is gone for you, too.

**Comment by mpuzio** [comment]
I am experiencing this problem too (with two screens of different size), the difference being that I am unable to start the x2go session at all - the session window briefly appears and then disappears. However, the underlying issue seems to be the same. I installed the nightly packages on my test VM and I am happy to report that the problem appears to be solved.

For the reference, related reports in x2go bug tracker:
https://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1272
https://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1269

**Comment by ngaywood** [comment]
:+1: 
Installing the nightly build fixed it for me :-)
That is, moving my x2goclient window across 2 different size displays no longer causes a SEGV in nxagent on the x2goserver.
