### ISSUE TITLE
Desktop flashing when maximizing window on second screen with Windows client X2go

### ISSUE THREAD

**Issue by soportecasator** [ArcticaProject/nx-libs#690]
Hello everybody, Can someone tell me how to configure the current vcxsrv  with the x2go client?

**Comment by sunweaver** [comment]
The quick answer is: get latest VcXsrv and install it. Then replace X2Go Client's vcxsrv/ subfolder by the one you just installed.

If you have further questions, please consult the x2go-user mailing list with this question. This issue tracker is neither for user questions nor about X2Go.
