### ISSUE TITLE
Missing RPM upgrade logic for libNX_*

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#70]
I just followed my instructions from #68, and here is what I now have installed:

```
[mike@dropship nx-libs]$ dnf list installed | grep -e 'libNX\|nx'
libNX_X11-6.x86_64                     3.5.99.0-0.0build1.fc23  @@commandline   
libNX_Xau6.x86_64                      3.5.99.0-0.0build1.fc23  @@commandline   
libNX_Xcomposite.x86_64                3.5.0.32-3.fc23          @updates        
libNX_Xdamage.x86_64                   3.5.0.32-3.fc23          @updates        
libNX_Xdmcp.x86_64                     3.5.0.32-3.fc23          @updates        
libNX_Xext6.x86_64                     3.5.99.0-0.0build1.fc23  @@commandline   
libNX_Xfixes.x86_64                    3.5.0.32-3.fc23          @updates        
libNX_Xinerama.x86_64                  3.5.0.32-3.fc23          @updates        
libNX_Xpm.x86_64                       3.5.0.32-3.fc23          @updates        
libNX_Xrandr.x86_64                    3.5.0.32-3.fc23          @updates        
libNX_Xrender1.x86_64                  3.5.99.0-0.0build1.fc23  @@commandline   
libNX_Xtst.x86_64                      3.5.0.32-3.fc23          @updates        
nx-libs.x86_64                         3.5.0.32-3.fc23          @updates        
nxagent.x86_64                         3.5.99.0-0.0build1.fc23  @@commandline   
nxauth.x86_64                          3.5.99.0-0.0build1.fc23  @@commandline   
nxproxy.x86_64                         3.5.99.0-0.0build1.fc23  @@commandline        
```

I think I need to add [RPM Obsoletes logic](https://fedoraproject.org/wiki/Upgrade_paths_%E2%80%94_renaming_or_splitting_packages#.28n:1.29_Many-to-one_replacement) to the spec file.

**Comment by sunweaver** [comment]
Hi Michael,

On Tue Jan 19 04:21:59 2016 GMT+0100, Mike DePaulo wrote:

> I just followed my instructions from #68, and here is what I now have installed: 
> [mike@dropship nx-libs]$ dnf list installed | grep -e 'libNX|nx'
> libNX_X11-6x86_64                     35990-00build1fc23  @@commandline  
> libNX_Xau6x86_64                      35990-00build1fc23  @@commandline  
> libNX_Xcompositex86_64                35032-3fc23          @updates  
> libNX_Xdamagex86_64                   35032-3fc23          @updates  
> libNX_Xdmcpx86_64                     35032-3fc23          @updates  
> libNX_Xext6x86_64                     35990-00build1fc23  @@commandline  
> libNX_Xfixesx86_64                    35032-3fc23          @updates  
> libNX_Xineramax86_64                  35032-3fc23          @updates  
> libNX_Xpmx86_64                       35032-3fc23          @updates  
> libNX_Xrandrx86_64                    35032-3fc23          @updates  
> libNX_Xrender1x86_64                  35990-00build1fc23  @@commandline  
> libNX_Xtstx86_64                      35032-3fc23          @updates  
> nx-libsx86_64                         35032-3fc23          @updates  
> nxagentx86_64                         35990-00build1fc23  @@commandline  
> nxauthx86_64                          35990-00build1fc23  @@commandline  
> nxproxyx86_64                         35990-00build1fc23  @@commandline        
> 
> I think I need to add RPM Obsoletes logic to the spec file 
> —
> Reply to this email directly or view it on GitHub.￼
> With @Ionic I agreed earlier, that removal of deprecated packages in RPM based distros is handle at dist-upgrade. In Debian and alike, the package maintainers have to take care about package removals, in RPM distros, Ionic figured out, the removal of unused pkgs is handled by the package management software.

Please provide feedback if you have different info.

## Mike

Sent from my Jolla

**Comment by Ionic** [comment]
At least OpenSuSE developers frown upon dummy packages as used in Debian. Instead, the preferred way is to leave the packages intact (but not update them) and rebuild the other packages to not link against and depend on them anymore + remove the package. This will make these packages orphans, which can be removed through various methods during dist-upgrades (I think zypper does this automatically, while dnf has special tools for removing orphaned packages.)

**Comment by mikedep333** [comment]
Hi guys, I think your advice does not apply to this case. The reason is that some libraries have to be installed explicitly. They are never pulled in by nxagent.

So the "Obsoletes" logic, which does avoid dummy packages, would solve this problem and meet the OpenSuSE guidelines.

**Comment by sunweaver** [comment]
Hi Mike,

On  Di 19 Jan 2016 14:44:45 CET, Mike DePaulo wrote:

> Hi guys, I think your advice does not apply to this case. The reason  
> is that some libraries have to be installed explicitly. They are  
> never pulled in by nxagent.
> 
> So the "Obsoletes" logic, which does avoid dummy packages, would  
> solve this problem and meet the OpenSuSE guidelines.

Ah, I see what you mean.

In Debian, there can be two approaches for this (nowadays):

(1) Hard-code dependencies of the very same version between nxagent  
and libnx-\* packages.

(2) Use debian/libnx-*.symbols files (which declare explicit  
dependencies on minimum required versions of shared library)

In the RPM world, I have no clue, if there is such a thing as .symbols  
files. I guess not.

Thus, I'd recommend taking approach (1).

Mike

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by mikedep333** [comment]
Hi @sunweaver I don't think I explained the situation properly. We got rid of many library packages in 3.6.x. Because we got rid of them, they should be removed at upgrade time. A perfect example being `libNX_Xcomposite`.

**Comment by sunweaver** [comment]
On  Mi 20 Jan 2016 00:00:10 CET, Mike DePaulo wrote:

> Hi @sunweaver I don't think I explained the situation properly. We  
> got rid of many library packages in 3.6.x. Because we got rid of  
> them, they should be removed at upgrade time. A perfect example  
> being `libNX_Xcomposite`.

As already said, at least in the SUSE world, this is handled at  
dist-upgrade time.

@opolawski: Could you take some time and look at the issue that  
mikedep333, Ionic and I are currently discussing regarding nx-libs  
Xclient library removal? If you need any extra explanation, please  
ping me/us. But the previous post on this issue report document well  
enough, what we are currently disagreeing on (mostly because of half  
knowledge on my side, I fear). So, your expertise on the Fedora realm  
of things is required and highly appreciated here. Thanks you!

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by sunweaver** [comment]
@opoplawski: Could you take some time and look at the issue that mikedep333, Ionic and I are currently discussing regarding nx-libs Xclient library removal? If you need any extra explanation, please ping me/us. But the previous post on this issue report document well enough, what we are currently disagreeing on (mostly because of half knowledge on my side, I fear). So, your expertise on the Fedora realm of things is required and highly appreciated here. Thanks you!

**Comment by opoplawski** [comment]
All rpms must handle removal of no-longer existing package via Obsoletes.  The mixture of versions that you end up with above is also an indication that the sub-packages are probably also missing a dependency on the explicit version of the base package, e.g.

```
%package -n libNX_X11
Summary:        Core NX protocol client library
Requires:       %{name}%{?_isa} = %{version}-%{release}
```

**Comment by mikedep333** [comment]
@opoplawski Thanks, I will submit a PR for both the Obsoletes and the explicit version dependencies.
