### ISSUE TITLE
JEdit issues with showing certain lines of text with latest snapshot

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#714]
Today I've opened a text file in JEdit and was a bit shocked because some lines of the text was just shown as empty lines. A quick test with vi showed that the file was correct, only showing it in JEdit was affected.

In the end I found the culprit: it's the latest nx-libs snapshot from Jul 3 which I compiled yesterday and used today. So, the issue comes from a change which was committed between Jun 17 and Jul 3.

Does anyone have an idea which change could be the source of the issue?

**Comment by uli42** [comment]
On Thu, Jul 5, 2018 at 3:29 PM, Simon Matter <notifications@github.com> wrote:
>
> Today I've opened a text file in JEdit and was a bit shocked because some lines of the text was just shown as empty lines. A quick test with vi showed that the file was correct, only showing it in JEdit was affected.
>
> In the end I found the culprit: it's the latest nx-libs snapshot from Jul 3 which I compiled yesterday and used today. So, the issue comes from a change which was committed between Jun 17 and Jul 3.

Thanks for reporting that!

> Does anyone have an idea which change could be the source of the issue?

Yes, for sure we need to repair this one, brackets need to be
introduced here (before one line, now three lines in the if clause):

--- a/nx-X11/programs/Xserver/mi/mizerline.c
+++ b/nx-X11/programs/Xserver/mi/mizerline.c
@@ -158,7 +158,9 @@ miZeroLine(pDraw, pGC, mode, npt, pptInit)
     pspanInit = (DDXPointPtr)malloc(list_len * sizeof(DDXPointRec));
     pwidthInit = (int *)malloc(list_len * sizeof(int));
     if (!pspanInit || !pwidthInit)
-       return;
+        free(pspanInit);
+        free(pwidthInit);
+        return;

     Nspans = 0;
     new_span = TRUE;
diff --git a/nx-X11/programs/Xserver/render/render.c
b/nx-X11/programs/Xserver/render/render.c
index fb9208ad1..65ca41881 100644
--- a/nx-X11/programs/Xserver/render/render.c
+++ b/nx-X11/programs/Xserver/render/render.c
@@ -1346,6 +1346,8 @@ ProcRenderCompositeGlyphs (ClientPtr client)
     {
        listsBase = (GlyphListPtr) malloc (nlist * sizeof (GlyphListRec));
        if (!listsBase)
+           free(glyphsBase);
+           free(listsBase);
            return BadAlloc;
     }

And there are more like that, I found 8 locations in a quick scan!

We have been to careless reagarding
913fcf1a74426725f14380dd5b34286a21c37ab7, so please revert it and
retry!

Uli

**Comment by realsimix** [comment]
I can confirm that reverting 913fcf1 resolves the issue.

**Comment by uli42** [comment]
Fixed via 9926731 and 15f6948
