### ISSUE TITLE
cmsColNm.c:317]: (warning) Logical disjunction always evaluates to true: EXPR != '\n' || EXPR != '\0'.

### ISSUE THREAD

**Issue by dcb314** [ArcticaProject/nx-libs#719]
Source code is

      if ((*pBuf != '\n') || (*pBuf != '\0')) {

maybe better code
      if ((*pBuf != '\n') && (*pBuf != '\0')) {

**Comment by uli42** [comment]
isn't that the same as #716?

**Comment by uli42** [comment]
has been merged yesterday
