### ISSUE TITLE
Files missing in libNX_X11

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#723]
The following files are existing libX11 1.6.6 but not in our tree:
```
src/xlibi18n/XlcSL.c 
src/xlibi18n/XDefaultIMIF.c
src/xlibi18n/XDefaultOMIF.c
src/xlibi18n/Xaixlcint.h
src/xlibi18n/lcDynamic.c
src/xlibi18n/XlcDL.c
```

Check what's the reason (if any)

**Comment by sunweaver** [comment]
They are obsolete with non-loadable i18n support. See 09cf1bcc0cc5f8b9d33b25e46320a9725742a38e.
