### ISSUE TITLE
Consider BPG as bitmap compression engine in NX

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#75]
Importing from X2Go BTS...
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=707

Hi all,

By Savko Sergey I have just been pointed to the upcoming BPG image  
compression library [1].

Quoting their website:

"""
BPG (Better Portable Graphics) is a new image format. Its purpose is  
to replace the JPEG image format when quality or file size is an  
issue. Its main advantages are:

```
High compression ratio. Files are much smaller than JPEG for  
```

similar quality.
    Supported by most Web browsers with a small Javascript decoder  
(gzipped size: 55 KB).
    Based on a subset of the HEVC open video compression standard.
    Supports the same chroma formats as JPEG (grayscale, YCbCr 4:2:0,  
4:2:2, 4:4:4) to reduce the losses during the conversion. An alpha  
channel is supported. The RGB, YCgCo and CMYK color spaces are also  
supported.
    Native support of 8 to 14 bits per channel for a higher dynamic range.
    Lossless compression is supported.
    Various metadata (such as EXIF, ICC profile, XMP) can be included.
"""

We should take a look at this new compression library and check if it  
is usable in NX.

Mike

[1] http://bellard.org/bpg/

**Comment by sunweaver** [comment]
Quoting Lee from x2go-dev

>  Sweet....
> But keep in mind that "data size" is not the only issue....
> Encoding latency is also an issue...
> Smaller "data" usually means more complex encoding...
> Though its is ofcourse possible that something new could potentially be
> producing smaller data and doing so more efficiently.
> Though the roots of this format is stuff that would be potentially heavy
> to digest in a larger multi-user environment.
> Though then again... the roots of this may eventually lead to it being
> something more well suited for GPU acceleration...
> 
> There is one concern however, one which would need to be properly sorted
> out before any large scale adoption would ever take place:
> http://en.wikipedia.org/wiki/Better_Portable_Graphics#Patents

**Comment by yatsek** [comment]
Hi there.

I'm one of interested users of x2go (which I love! - thank you for this work!) which I would like to test with BPG or some other libs. Is there a way to maybe standardize (within x2go) compression libs and allow users choose on their own?

I'm willing to participate/help btw. Just point me to some directions how in DIY way it could be achieved and I'm wiling to check/test/script it and provide tutorial/results for others.

In Europe we do not have software patents and hopefully we will never have those. In US it should be possible to leave users with just empty interface and not be liable if users actually use it in a way which breaks patents. IANAL of course.

Edit: I've noticed that this is another project using parts of x2go libs. Anyway my offer still stands if the result will be x2go replacement with BPG support.

**Comment by sunweaver** [comment]
Closing issue #75 as BPG is license wise no option for us.

**Comment by yatsek** [comment]
Bummer, but I appreciate your effort. What about offer to standardize somehow compression so adding any library/algorithm by user would be easier?

**Comment by gznget** [comment]
Multi pass encoding takes more time and cost more resources...  The human eye is more sensitive to latency and jitter (shapes) than shades of colors.... so your best bet on a slow link is usually to reduce the quality and amount of color in your jpeg.
