### ISSUE TITLE
Tooltips, pull-down menus, and context menus too far away (X2Go #1359)

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#757]
https://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1359

"I've recently started experiencing a problem when running single
applications over X2Go.  Quite often small windows such as tooltips,
pull-down menus, and context menus get positioned far, far away from
where they are supposed to be.  For example, I'm currently writing this
message in Claws Mail; when I activate the "Edit" pull-down menu, the
menu doesn't appear under the menu bar but rather way over on my second
screen.  (I use a dual-monitor setup.)

The problem happens with a lot of different applications, but not
always consistently.  For instance, sometimes I might hover my pointer
over a widget that causes a tooltip to display halfway across the
screen, and a minute or two later I'll do the same thing but this time
the tooltip will display right over the widget like it's supposed to.

I'm not sure if this is a bug in X2Go or in my window manager, and if
it is in X2Go, whether its the client or server that's at fault.  I'm
running the X2Go Server 4.1.0.4 on openSUSE Tumbleweed, and connecting
from X2Go Client 4.1.1.1 on openSUSE Leap 15.0, using KDE Plasma
5.12.6.  (I can't upgrade the client due to Bug #1358.)"

**Comment by logological** [comment]
I'm the reporter of the bug on the X2Go bug tracker.  I'm available here to answer queries and perform testing.

**Comment by uli42** [comment]
Ok, thanks for the information. Can you please retry with another window manager? It would also help if you could out how to reliably replicate it.

Can you tell if this happens on both new connections and reconnected sessions?

And just to be sure: what version of nx-libs/nxagent are you using?

**Comment by logological** [comment]
> Ok, thanks for the information. Can you please retry with another window manager? 

That might be tricky, since I work exclusively in Plasma, but the problem is not always consistently reproducible.  I'll try using some other environment and hopefully that won't put too big a dent in my productivity.

> It would also help if you could out how to reliably replicate it.

I would like nothing more, but so far I haven't been able to.

> Can you tell if this happens on both new connections and reconnected sessions?

I haven't tested whether this makes a difference.  I'll do some testing and get back to you.

> And just to be sure: what version of nx-libs/nxagent are you using?

On the server:
nx-libs-3.5.99.17-0.0build1.0.git20181127.3186.heuler.x86_64
nxagent-3.5.99.17-0.0build1.0.git20181127.3186.heuler.x86_64

On the client:
nx-libs-3.5.99.16-0.0build1.1.git20180719.2988.main.x86_64
nxagent-3.5.99.16-0.0build1.1.git20180719.2988.main.x86_64

**Comment by logological** [comment]
> > Can you tell if this happens on both new connections and reconnected sessions?
> 
> I haven't tested whether this makes a difference.

I can now confirm that it definitely happens with reconnected sessions (but not consistently).  If I notice it happening with a new session, I will let you know.

**Comment by uli42** [comment]
Just choose another window manager and run it with "--replace"

**Comment by logological** [comment]
The following steps seem to reproduce the problem consistently, using the setup described in my original report.

1. Use X2Go to launch a terminal emulator in single application mode.  I do this by having X2Go run the following remote command:
```
#!/bin/sh
PROFILEREAD=
export PROFILEREAD
exec /bin/bash --login -c /usr/bin/xfce4-terminal
```
2. Launch `claws-mail`.  View a message and right-click somewhere in the message preview pane.  Context menu appears where it should.
3. Suspend the X2Go session.
4. Resume the X2Go session.
5. In the Claws Mail window, right-click somewhere in the message preview pane.  Context menu now appears far, far away.

**Comment by logological** [comment]
> Just choose another window manager and run it with "--replace"

Ah, I see how that would be easier.  Now that I have a way of consistently reproducing the problem with kwin, I'll try another window manager.  I won't have time to do this today, though.  Maybe tomorrow.

**Comment by uli42** [comment]
I can also see something similar this when I take out x2go of the equation:
1. run `nxagent -R :55`
2. export DISPLAY=:55
3. run you script
4. run claws-mail in the newly-opened termina
5. View a message and right-click somewhere in the message preview pane. Context menu appears where it should.
6. pkill -HUP nxagent && sleep 5 && pkill -HUP nxagent
7. In the Claws Mail window, right-click somewhere in the message preview pane. Context menu now appears at a different location

Can you confirm this?

**Comment by logological** [comment]
I can't get past step 3.  Is there some other step missing?

```
$ nxagent -R :55 &
[1] 29990

NXAGENT - Version 3.5.99.16

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
Copyright (c) 2011-2016 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Copyright (c) 2014-2016 Ulrich Sibiller <uli42@gmx.de>
Copyright (c) 2014-2016 Mihai Moldovan <ionic@ionic.de>
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '29990'.
Session: Starting session at 'Thu Jan 10 09:32:49 2019'.
Info: Using alpha channel in render extension.
Info: Not using local device configuration changes.
Warning: Cannot read keystroke file '/home/miller/.nx/config/keystrokes.cfg'.
Info: using keystrokes file '/etc/nxagent/keystrokes.cfg'
Warning: ignoring keystroke 'viewport_scroll_up' (already in use by 'viewport_move_up')
Warning: ignoring keystroke 'viewport_scroll_up' (already in use by 'viewport_move_up')
Warning: ignoring keystroke 'viewport_scroll_right' (already in use by 'viewport_move_right')
Warning: ignoring keystroke 'viewport_scroll_right' (already in use by 'viewport_move_right')
Warning: ignoring keystroke 'viewport_scroll_down' (already in use by 'viewport_move_down')
Warning: ignoring keystroke 'viewport_scroll_down' (already in use by 'viewport_move_down')
Current known keystrokes:
  close_session         Ctrl+Alt+t
  switch_all_screens    Ctrl+Alt+f
  fullscreen            Ctrl+Shift+Alt+f
  minimize              Ctrl+Alt+m
  defer                 Ctrl+Alt+e
  ignore                Ctrl+Alt+BackSpace
  force_synchronization Ctrl+Alt+j
  resize                Ctrl+Alt+r
  viewport_move_left    Ctrl+Shift+Alt+Left
  viewport_move_left    Ctrl+Shift+Alt+KP_Left
  viewport_move_up      Ctrl+Alt+Up
  viewport_move_up      Ctrl+Alt+KP_Up
  viewport_move_right   Ctrl+Alt+Right
  viewport_move_right   Ctrl+Alt+KP_Right
  viewport_move_down    Ctrl+Alt+Down                                                                                                              
  viewport_move_down    Ctrl+Alt+KP_Down                                                                                                           
  viewport_scroll_left  Ctrl+Alt+Left                                                                                                              
  viewport_scroll_left  Ctrl+Alt+KP_Left                                                                                                           
  reread_keystrokes     Ctrl+Alt+k
Warning: SessionPath not defined                                                                         
Info: Keycode conversion auto-determined as on                                                                                                     
Session: Session started at 'Thu Jan 10 09:32:49 2019'.

$ export DISPLAY=:55

$ ./launchxterm                                                                                                                      
AUDIT: Thu Jan 10 09:33:31 2019: 29990 nxagent: client 1 rejected from local host ( uid=1000 gid=100 pid=30138 )
No protocol specified
No protocol specified
Unable to init server: Could not connect: Connection refused

(xfce4-terminal:30138): Gtk-WARNING **: cannot open display: :55
```

**Comment by uli42** [comment]
Alright, my fault, you must run "nxagent -ac :55 -R".

**Comment by logological** [comment]
> Alright, my fault, you must run "nxagent -ac :55 -R".

OK, now I can do the test.   I can confirm that the problem is reproducible this way, with nxagent running locally.  In fact, step 3 isn't necessary -- the problem can be reproduced simply by invoking claws-mail directly.

Do you still need me to test with a different window manager?

**Comment by uli42** [comment]
yes, please

**Comment by logological** [comment]
Yes, the problem still occurs when using IceWM instead of kwin.

**Comment by uli42** [comment]
Ok. Does it show exactly the same window positions?

I think it has to do with the window properties. Please check the following:
- use the variant where you have a terminal + claws-mail in the session
- run the following commands, once before the kill -HUP and once
after. Store the outputs to files:
  - xprop -root in the session
  - xprop _in_ the session. This will change the mouse cursor. click
on the claws window
  - xprop _outside_ the session This will change the mouse cursor.
click on the claws window.
- send me the files to find differences

**Comment by logological** [comment]
> Ok. Does it show exactly the same window positions? I think it has to do with the window properties. Please check the following:

Output attached.  By "outside the session", I assume you mean the terminal from which I launched nxagent and where I did `export DISPLAY=:55`.

[xprop.inside.after.txt](https://github.com/ArcticaProject/nx-libs/files/2746680/xprop.inside.after.txt)
[xprop.inside.before.txt](https://github.com/ArcticaProject/nx-libs/files/2746681/xprop.inside.before.txt)
[xprop.outside.after.txt](https://github.com/ArcticaProject/nx-libs/files/2746682/xprop.outside.after.txt)
[xprop.outside.before.txt](https://github.com/ArcticaProject/nx-libs/files/2746683/xprop.outside.before.txt)
[xprop-root.inside.after.txt](https://github.com/ArcticaProject/nx-libs/files/2746684/xprop-root.inside.after.txt)
[xprop-root.inside.before.txt](https://github.com/ArcticaProject/nx-libs/files/2746685/xprop-root.inside.before.txt)

**Comment by uli42** [comment]
Thanks!  in `xprop-root.inside*` there's no real difference. But in `xprop.inside*` you can see this difference (same in xprop.outside*):

before:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                program specified minimum size: 320 by 200
                window gravity: NorthWest
```

after:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 249, 29
                program specified location: 249, 29
                program specified minimum size: 320 by 200
                window gravity: Static
```

Must check were this originates from.

**Comment by uli42** [comment]
Thanks!  in `xprop-root.inside*` there's no real difference. But in `xprop.inside*` you can see this difference (same in xprop.outside*):

before:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                program specified minimum size: 320 by 200
                window gravity: NorthWest
```

after:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 249, 29
                program specified location: 249, 29
                program specified minimum size: 320 by 200
                window gravity: Static
```

I have now scanned the source and tested quite some stuff, and I can tell that - while this is not perfect here - is not responsible for the problems we try to resolve in this issue.

Further testing revealed that this is tied to a wrong screen size setting after reconnect. While the claws-mail main window can be placed anywhere on the screen the menus cannot go beyond the max screen size. Please do the following to verify my observations:
1. same procedure as previously
2. right before issuing the first pkill -HUP run `DISPLAY=:55 xrandr`
3. right after the second pkill -HUP run the command from 2. again
4. observation: the screen size has changed to 3/4 of the old value! Can you confirm?

**Comment by logological** [comment]
> Please do the following to verify my observations:
> 
>     1. same procedure as previously
> 
>     2. right before issuing the first pkill -HUP run `DISPLAY=:55 xrandr`
> 
>     3. right after the second pkill -HUP run the command from 2. again
> 
>     4. observation: the screen size has changed to 3/4 of the old value! Can you confirm?

Before suspending, xrandr reports in its first line of output that Screen 0 currently has a resolution of 3600×1080.  This roughly matches the total resolution of my dual-monitor setup: my left monitor is 1680×1050 and my right monitor is 1920×1080.  xrandr goes on to report that there is a single "default" connection to a 3600×1080 display:

```
Screen 0: minimum 320 x 240, current 3600 x 1080, maximum 3600 x 1200
default connected 3600x1080+0+0 0mm x 0mm
```

After suspending and reconnecting, xrandr still gives the same screen information on the first line, but the next lines no longer mention a "default" connection.  Instead, two separate connections named "NX1" and "NX2" are shown, with resolutions of 1020×810 and 1680×810, respectively.  Added together, this gives 2700×810, which is indeed 3/4 the size previously reported:

```
Screen 0: minimum 320 x 240, current 3600 x 1080, maximum 3600 x 1200
NX1 connected 1020x810+1680+0 0mm x 0mm
   nx_1020x810   60.00* 
NX2 connected 1680x810+0+0 0mm x 0mm
   nx_1680x810   60.00* 
```

Attached is the complete output of both xrandr commands: [xrandr.before.txt](https://github.com/ArcticaProject/nx-libs/files/2749684/xrandr.before.txt) [xrandr.after.txt](https://github.com/ArcticaProject/nx-libs/files/2749686/xrandr.after.txt)

**Comment by uli42** [comment]
Ok, thanks. I have a patch available which I can provide later today, hopefully

**Comment by uli42** [comment]
See #761 for a fix. You can try building an own package with the included spec file until it gets included into the release packages.

**Comment by logological** [comment]
Thanks.  I don't have time to test the fix now but may do so soon.

Does this mean that X2Go #1359 can be closed?

**Comment by uli42** [comment]
On Mon, Jan 14, 2019 at 9:29 AM Tristan Miller <notifications@github.com> wrote:
>
> Thanks. I don't have time to test the fix now but may do so soon.
>
> Does this mean that X2Go #1359 can be closed?

Well, if the fix proves to work on your side, yes.

Uli

**Comment by logological** [comment]
I built and installed from the 3.6.x branch, into which your changes had been merged.  With this version, I can verify that the problem is no longer reproducible.  I'll try closing X2Go #1359 but I'm not sure if non-developers have access rights to do so.  If my control message doesn't get applied, I'd be grateful if you (or someone else with the requisite permissions) could close the bug for me.

**Comment by sunweaver** [comment]
Hi,

On Friday, 1 February 2019, Tristan Miller wrote:
> I built and installed from the 3.6.x branch, into which your changes had been merged.  With this version, I can verify that the problem is no longer reproducible.  I'll try closing X2Go #1359 but I'm not sure if non-developers have access rights to do so.  If my control message doesn't get applied, I'd be grateful if you (or someone else with the requisite permissions) could close the bug for me.
> 

You should be able to close bugs on X2Go BTS.

Mike
-- 
Sent from my Sailfish device
