### ISSUE TITLE
NXagent segfault randomly (apparently)

### ISSUE THREAD

**Issue by numerical2017** [ArcticaProject/nx-libs#758]
We remotely access to a Centos 7 server with X2GO from 3 very similar Windows clients.
Two of these "randomly"  experience a crash of the X2GO session with the following error:

kernel: x2goagent[160448]: segfault at 40 ip 00005573ac1af9ba sp 00007fff868b6f60 error 4 in nxagent[5573ac0c2000+43f000]

NXlibs version installed is the latest one, 3.5.99.17.
The problem occurred for the first time at the beginning of November, I updated the packages to the latest ones but nothing has changed. It is annoying because it happens quite often and it is not possible to work with X2GO.
The strange thing is that from one client it works without problems but the software installed is the same, and the configuration as well....do you experienced a similar behaviour?

**Comment by uli42** [comment]
No, I am not aware of such a sceario. Have you possibly updated
Windows by that date?

Can you reliably provoke that crash? Can you describe a situation
where it happened?

**Comment by numerical2017** [comment]
Windows machines have Windows 10 so they update often, once a week more or less. But all the three clients are regularly equally updated. 
X2GO client software has been also updated after the first crash but it didn't solve the issue.
The same when I installed VCXSRV as custom X-server.

I cannot reproduce the crash because we actually don't understand what is the cause. What I can do is to wait for a crash and collect all the information you need to figure out what happens.
We can start the session, then use the software on the remote server and after an amount of time between 10 to 40 minutes it crashes. 

Looking in the folder /$HOME/.x2go/C-<sessionID> I found the backtrace with this message:

*** Error in `x2goagent': corrupted size vs. prev_size: 0x000055ca3581fe60 ***

Which data and log should I look for to identify the problem? I already added the "debug" flag to the X2Go config file.

**Comment by uli42** [comment]
Well, sorry for the delay. Can you try attaching gdb to the x2goagent process on the server (prior to crash) and print the backtrace after it happened (command bt)?

**Comment by uli42** [comment]
ping!

**Comment by uli42** [comment]
no answer from OP anymore, closing
