### ISSUE TITLE
libNX_X11: autotools is lacking some defines vs imake

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#769]
I have compared how libNX_X11 sources are compiled using autotools and how they used to be compiled using Imake. I found some missing defines in the autotools build which had been used by the imake build.

```
-DHASXDMAUTH
-DSECURE_RPC
-DHAS_STICKY_DIR_BIT
-DHAS_FCHOWN
-DFAIL_HARD
-DXTRANS_SEND_FDS=0
-DXCMSDB=\"/usr/local/share/nx/Xcms.txt\" -DXCMSDIR=\"/usr/local/share/nx\"
-DXLOCALEDIR=\"/usr/local/lib/nx/X11/locale\" -DXLOCALELIBDIR=\"../../exports/lib/locale\" 
```

Here a list of the affected files:

```
ConnDis.c: -DHASXDMAUTH -DSECURE_RPC  -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN    -DFAIL_HARD -DXTRANS_SEND_FDS=0
OpenDis.c:  -DFAIL_HARD -DXTRANS_SEND_FDS=0
XlibInt.c: -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN -DFAIL_HARD -DXTRANS_SEND_FDS=0
globals.c: -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN
cmsColNm.c: -DXCMSDB=\"/usr/local/share/nx/Xcms.txt\" -DXCMSDIR=\"/usr/local/share/nx\"                                        x11_trans.c: -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN -DFAIL_HARD -DXTRANS_SEND_FDS=0
xim_trans.c: -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN -DFAIL_HARD -DXTRANS_SEND_FDS=0
lcFile.c: -DXLOCALEDIR=\"/usr/local/lib/nx/X11/locale\" -DXLOCALELIBDIR=\"../../exports/lib/locale\" 
imTransR.c -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN -DFAIL_HARD -DXTRANS_SEND_FDS=0
ImTrans.c: -DHAS_STICKY_DIR_BIT -DHAS_FCHOWN  -DFAIL_HARD -DXTRANS_SEND_FDS=0
```

See also #768 for a related issue regarding XCursor.

**Comment by uli42** [comment]
ping

**Comment by sunweaver** [comment]
This seems like we need to go over those files and check what those macros do at build time... I won't have time for this before March, due to work tasks waiting for being done until end of Feb.

**Comment by uli42** [comment]
FYI: I have fixed HAS_XDMAUTH, SECURE_RPC and HAS_STICKY_DIR_BIT here:  https://github.com/uli42/nx-libs/tree/pr/libx11_xdmauth

For HAS_FCHOWN I have found the required stuff in Xorg's libxtrans/configure.ac but it does nor work with my autoconf 2.69.

**Comment by uli42** [comment]
Closing this issue as I have split it up into issues #779 to #786
