### ISSUE TITLE
Fullscreen not working anymore

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#772]
With the latest commits from 13.02.2019, fullscreen mode doesn't work for me anymore.

Using `nxagent .... -autodpi -geometry fullscreen ....` shows a window without borders but it's not full size.

Before diving into the latest changes, any idea what could cause this?

Regards,
Simon

**Comment by realsimix** [comment]
I'm not sure but I think the latest changes consider variables like nxagentOptions.Fullscreen to be boolean but they seem to be tristate.

I found this:

```
#define UNDEFINED -1
#define False 0
#define True 1

nxagentOptions.Fullscreen = UNDEFINED;
nxagentChangeOption(Fullscreen, True);
nxagentChangeOption(Fullscreen, False);
if (nxagentOption(Fullscreen) == UNDEFINED)
```
Maybe that's breaking things here?

Regards,
Simon

**Comment by uli42** [comment]
On Fri, Feb 15, 2019 at 7:45 AM Simon Matter <notifications@github.com> wrote:
>
> I'm not sure but I think the latest changes consider variables like nxagentOptions.Fullscreen to be booleab but they seem to be tristate.
>
> I find this:
>
> nxagentOptions.Fullscreen = UNDEFINED;
> nxagentChangeOption(Fullscreen, True);
> nxagentChangeOption(Fullscreen, False);
> if (nxagentOption(Fullscreen) == UNDEFINED)
>
> #define UNDEFINED -1
> #define True 1
> #define False 0
>
> Maybe that's breaking things here?

Thanks for spotting that! I was just sitting down to check just that
very patch because for me reconnects are not working anymore.

Uli

**Comment by uli42** [comment]
Well, UNDEFINED is only used/checked for during startup. Maybe we have paths where the value stays at UNDEFINED and is then recognized as being True somewhere else. Difficult to check if that's the case. 

Those "Booleans" are never really taken into account as being tristate so any check could be buggy. The clean solution was to really make them Booleans without having to bother about a third state.

**Comment by sunweaver** [comment]
@uli42: I closed this bug with PR #773. Please, if needed, file a new bug that reminds us on this boolean cleanup stuff. Thanks.

**Comment by uli42** [comment]
On Fri, Feb 15, 2019 at 6:34 AM Simon Matter <notifications@github.com> wrote:
>
> With the latest commits from 13.02.2019, fullscreen mode doesn't work for me anymore.
>
> Using nxagent .... -autodpi -geometry fullscreen .... shows a window without borders but it's not full size.
>
> Before diving into the latest changes, any idea what could cause this?

I hope this is working again with 3.5.99.19?

Uli

**Comment by realsimix** [comment]
Yes, it works perfect with 3.5.99.19.

Thanks,
Simon
