### ISSUE TITLE
Misc.cpp:120: error: unknown escape sequence: '\011'

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#777]
Recent commit introduced a bug affecting old compilers:
```
Misc.cpp: At global scope:
Misc.cpp:120: error: unknown escape sequence: '\011'
```
Patch below fixes it:
[nx-libs-3.6.x-20190219-help_typo.patch.txt](https://github.com/ArcticaProject/nx-libs/files/2878483/nx-libs-3.6.x-20190219-help_typo.patch.txt)

**Comment by uli42** [comment]
On Tue, Feb 19, 2019 at 6:49 AM Simon Matter <notifications@github.com> wrote:
>
> Recent commit introduced a bug affecting old compilers:
>
> Misc.cpp: At global scope:
> Misc.cpp:120: error: unknown escape sequence: '\011'
>
> Patch below fixes it:
> nx-libs-3.6.x-20190219-help_typo.patch.txt

Thanks!

Could you please create an own branch and file a pull request? This
would make it integration cleaner (submitter, date,...)

Uli

**Comment by realsimix** [comment]
Hi Uli, as I'm not a software developer I don't intend to learn git and how to do it all just for my small contributions. I hope you understand :-)

Simon

**Comment by uli42** [comment]
ok ;-) (But for the records: git is not complicated. And it can be
used for other purposes, too, not limited to software development.
E.g. you could manage your config files using git ;)
