### ISSUE TITLE
nxagent segfaults in LibNX_X11.so when disconnecting

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#81]
From X2Go BTS:

Package:  x2goagent
Version:   3.5.0.31-1.el6

When I disconnected from a windows client, I lost my session.  This is the
result in the server at the time of the disconnect.  It does not happen
every time, just some times when I disconnect.  I can re-connect fine with a
new session, but the running session is lost.

Sep  2 00:34:36 tyler kernel: x2goagent[28724]: segfault at 7fff43451ff8 ip
00007fcf05ebad84 sp 00007fff43451ff0 error 6 in
libNX_X11.so.6.2[7fcf05e73000+10c000]

Sep  2 00:34:36 tyler /usr/bin/x2gosuspend-session: session with ID
jameskohout-58-1441122134_stDGNOME_dp32 has been suspended successfully

Sep  2 00:34:45 tyler abrt[11437]: Saved core dump of pid 28724
(/usr/lib64/nx/bin/nxagent) to
/var/spool/abrt/ccpp-2015-09-02-00:34:36-28724 (390942720 bytes)

Sep  2 00:34:45 tyler abrtd: Directory 'ccpp-2015-09-02-00:34:36-28724'
creation detected

Sep  2 00:34:45 tyler abrtd: Package 'nxagent' isn't signed with proper key

Sep  2 00:34:45 tyler abrtd: 'post-create' on
'/var/spool/abrt/ccpp-2015-09-02-00:34:36-28724' exited with 1

Sep  2 00:34:45 tyler abrtd: Deleting problem directory
'/var/spool/abrt/ccpp-2015-09-02-00:34:36-28724'

[...]

 looked and the /var/spool/abrt/ccpp-2015-09-02-00:34:36-28724 is gone.

**Comment by sunweaver** [comment]
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=938

**Comment by opoplawski** [comment]
You may be able to get abrt to recognize the key for nxagent by reinstalling it:

yum reinstall nxagent

assuming it is actually a signed package.  Not sure where  it's coming from as 3.5.0.32-3.el6 is what is current from EPEL.  If not signed, there should be a config somewhere in /etc/abrt\* to tell it to keep coredumps from unsigned packages.

**Comment by uli42** [comment]
I vote for closing this, we have improved libX11 a lot since Feb 2016...

**Comment by uli42** [comment]
closing, pretty old, for old codebase, not seen in a long time
