### ISSUE TITLE
very slow startup of nxproxy/nxagent

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#824]
I see very strange slow startup of nxproxy/nxagent on certain networks.
Nxproxy seems to connect to nxagent but then it takes very long to start the session and the desktop to appear. I don't remember exactly how long it takes but it's a minute or so. Once the session is established, it works very well without any issues.

My question is, does anyone see the same issue or have an idea why it happens?

First I thought it could be a DNS issue but I couldn't find anything. Or could it be an IPv6 issue somehow because of dual stack?

Any help is much appreciated.

Regards,
Simon

**Comment by uli42** [comment]
On Tue, Jul 9, 2019 at 6:49 PM Simon Matter <notifications@github.com> wrote:
>
> I see very strange slow startup of nxproxy/nxagent on certain networks.
> Nxproxy seems to connect to nxagent but then it takes very long to start the session and the desktop to appear. I don't remember exactly how long it takes but it's a minute or so. Once the session is established, it works very well without any issues.
>
> My question is, does anyone see the same issue or have an idea why it happens?
>
> First I thought it could be a DNS issue but I couldn't find anything. Or could it be an IPv6 issue somehow because of dual stack?
>
> Any help is much appreciated.


There are two things that come to mind:
1. in the past years we added some more communication with the real X
server that will take place during startup (namely xinerama and
keyboard related). For a slow connection this might increase the
startup and/or reconnect time
2. nxproxy and nxagent must agree on the state of their respective
caches. If the cache directories (in .nx or .x2go) are large or on a
slow harddisk this might affect the startup.

I know you are familiar with coding so maybe you can just compile a
version with debugging enabled in nxcomp and nxagent's Init.c (and
maybe more) and watch where it takes long. I have not seen such
extreme times but 10-20s is not unheard of...

Uli

**Comment by realsimix** [comment]
> There are two things that come to mind:
> 1. in the past years we added some more communication with the real X server that will take place during startup (namely xinerama and keyboard related). For a slow connection this might increase the startup and/or reconnect time
> 2. nxproxy and nxagent must agree on the state of their respective caches. If the cache directories (in .nx or .x2go) are large or on a slow harddisk this might affect the startup. I know you are familiar with coding so maybe you can just compile a version with debugging enabled in nxcomp and nxagent's Init.c (and maybe more) and watch where it takes long. I have not seen such extreme times but 10-20s is not unheard of...

As for 1) it's not related to code version. I understand that newer versions may take a bit more time but that's not the issue here. I've tested with latest Git as well as ancient NoMachine code. Both behave almost the same.

For 2) it's also not the problem here. I just took my laptop from the other network to my home network and all is well again. Latency to the server is low here in home network (~9ms) while the other network was 9000km away with latency of 200-300ms. That said, the problem is new and didn't show up some weeks ago.

I just can't figure out what change has lead to the issue.

Simon

**Comment by uli42** [comment]
On Wed, Jul 10, 2019 at 10:41 AM Simon Matter <notifications@github.com> wrote:
>
> There are two things that come to mind:
>
> in the past years we added some more communication with the real X server that will take place during startup (namely xinerama and keyboard related). For a slow connection this might increase the startup and/or reconnect time
> nxproxy and nxagent must agree on the state of their respective caches. If the cache directories (in .nx or .x2go) are large or on a slow harddisk this might affect the startup. I know you are familiar with coding so maybe you can just compile a version with debugging enabled in nxcomp and nxagent's Init.c (and maybe more) and watch where it takes long. I have not seen such extreme times but 10-20s is not unheard of...
>
> As for 1) it's not related to code version. I understand that newer versions may take a bit more time but that's not the issue here. I've tested with latest Git as well as ancient NoMachine code. Both behave almost the same.
>
> For 2) it's also not the problem here. I just took my laptop from the other network to my home network and all is well again. Latency to the server is low here in home network (~9ms) while the other network was 9000km away with latency of 200-300ms. That said, the problem is new and didn't show up some weeks ago.

So just to get this right: this problem is latency related?

Have you tried if there's a difference between a rootless session
(nxagent -R) and a desktop session (nxagent -D)?
Have you tried if it depends on the desktop environment?

> I just can't figure out what change has lead to the issue.

You might try bisecting the code. But I doubt it is a code issue as it
is working in your home network.

Update: please test if changing the connection type helps (adsl vs lan vs wan).

Uli

**Comment by uli42** [comment]
On Wed, Jul 10, 2019 at 10:51 AM Ulrich Sibiller <uli42@gmx.de> wrote:
>
> On Wed, Jul 10, 2019 at 10:41 AM Simon Matter <notifications@github.com> wrote:
> >
> > There are two things that come to mind:
> >
> > in the past years we added some more communication with the real X server that will take place during startup (namely xinerama and keyboard related). For a slow connection this might increase the startup and/or reconnect time
> > nxproxy and nxagent must agree on the state of their respective caches. If the cache directories (in .nx or .x2go) are large or on a slow harddisk this might affect the startup. I know you are familiar with coding so maybe you can just compile a version with debugging enabled in nxcomp and nxagent's Init.c (and maybe more) and watch where it takes long. I have not seen such extreme times but 10-20s is not unheard of...
> >
> > As for 1) it's not related to code version. I understand that newer versions may take a bit more time but that's not the issue here. I've tested with latest Git as well as ancient NoMachine code. Both behave almost the same.
> >
> > For 2) it's also not the problem here. I just took my laptop from the other network to my home network and all is well again. Latency to the server is low here in home network (~9ms) while the other network was 9000km away with latency of 200-300ms. That said, the problem is new and didn't show up some weeks ago.
>
> So just to get this right: this problem is latency related?
>
> Have you tried if there's a difference between a rootless session
> (nxagent -R) and a desktop session (nxagent -D)?
> Have you tried if it depends on the desktop environment?
>
> > I just can't figure out what change has lead to the issue.
>
> You might try bisecting the code. But I doubt it is a code issue as it
> is working in your home network.
>
> Update: please test if changing the connection type helps (adsl vs lan vs wan).

One more idea: could this be related to fonts? You could enable DEBUG
in Fonts.c and check the output.

I have reworked the font handling some months ago.

Uli

**Comment by realsimix** [comment]
I've changed connection type from WAN to ADSL with noc change.

Font handling is not the problem as the problem also exists with the ancient NoMachine code.

And I think the problem is not really latency related because it has worked very well with even higher latency in the past.

I'll let you know if I find something.

Simon

**Comment by nitomartinez** [comment]
Perhaps unrelated,

Have you got a custom logo pixmap?

We used to have errors on high latency networks with large custom pixmaps.

**Comment by realsimix** [comment]
No, we use the NoMachine logo in old builds with only patched colors and the standard X logo with latest Git.

One more question to those who know the code well: How do I get a DEBUG enabled build of the complete code? Is it possible to enable it for the whole project somehow?

**Comment by realsimix** [comment]
I start to believe the problem is not related to NX. Doing an ssh -X to the slow remote host and from there another ssh -X back to the local host, then starting only an xterm shows the delay of two and a half minutes!

**Comment by sunweaver** [comment]
Hi Simon,

On  Mi 10 Jul 2019 13:49:40 CEST, Simon Matter wrote:

> No, we use the NoMachine logo in old builds with only patched colors  
> and the standard X logo with latest Git.
>
> One more question to those who know the code well: How do I get a  
> DEBUG enabled build of the complete code? Is it possible to enable  
> it for the whole project somehow?

You probably don't want that. I will produce tons of debug lines and  
the whole debugging becomes rather unspecific.

You can surely use sed to enable DEBUG for all files in  
nx-X11/programs/Xserver/hw/nxagent/, but well...

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 486 14 27

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
On Wed, Jul 10, 2019 at 4:54 PM Mike Gabriel <notifications@github.com>
wrote:

> Hi Simon,
>
> On Mi 10 Jul 2019 13:49:40 CEST, Simon Matter wrote:
>
> > No, we use the NoMachine logo in old builds with only patched colors
> > and the standard X logo with latest Git.
> >
> > One more question to those who know the code well: How do I get a
> > DEBUG enabled build of the complete code? Is it possible to enable
> > it for the whole project somehow?
>
> You probably don't want that. I will produce tons of debug lines and
> the whole debugging becomes rather unspecific.
>
> You can surely use sed to enable DEBUG for all files in
> nx-X11/programs/Xserver/hw/nxagent/, but well...
>
>
That's true but it might still help to point where nxagent loses time...
There's also a define called NXAGENT_TIMESTAMP. Maybe that'll be enough to
get a rough guess. I have not looked currently but I am aware of at least
two locations in the code where this will print out timing information.


Uli

**Comment by Djelff** [comment]
The same symptoms: on nx_libs 3.5.99.16 and earlier, after the appearance of the nxclient window in windows, a delay of about 3s passes, on nx_libs 3.5.99.17 and later about 17s
I have to work through 4g and OpenVPN with an average delay of 85ms.
The server I'm trying to use is the old/new freenx-server running on the nx-libs libraries, from dimbor-ru https://github.com/dimbor-ru

**Comment by uli42** [comment]
@Djelff  I have just checked the differences between 3.5.99.16 and 3.5.99.17. The biggest change is keyboard related but I doubt that this is the reason. Another thing is a bigrequests fix. I can image some problems with big requests over your slow 4G connection. So _maybe_ disabling bigrequests helps. Can you please try this? (add `-extension BIG-REQUESTS` to the nxagent startup (I do not know how to accomplish that for freenx).

Also, can you point to anything that nxagent might be doing during that delay? Any visible stuff happening?

**Comment by uli42** [comment]
One more question: does this only happen in windows? Can you check with a Linux client?

**Comment by Djelff** [comment]
I specifically checked all versions to determine at what exact moment regression occurred. 
On Linux, the client behaves the same way. 
Visually nothing happens, the client starts, the logo appears and nothing happens 15s. 
We could not find anything suspicious in the logs.

4G is not slow, and the delay is not so high https://www.speedtest.net/result/8913515284

Add -extension BIG-REQUESTS to the launch of the nxagent, it was not difficult, but no effect.

**Comment by Djelff** [comment]
Мaybe it will help? I found delay in file "session" on server.

Info: Using ZLIB data compression 1/1/32.
Info: Using ZLIB stream compression 9/9.
Info: No suitable cache file found.
Info: Listening to X11 connections on display ':2000'.
Info: Established X client connection.
Info: Using shared memory parameters 1/1/0/0K.
-----   15c delay -----
Info: Using alpha channel in render extension.
Info: Using local device configuration changes.
Warning: Cannot read keystroke file '/home/addm/.nx/config/keystrokes.cfg'.
Info: using keystrokes file '/etc/nxagent/keystrokes.cfg'
Info: ignoring unknown keystroke action 'autograb'

**Comment by uli42** [comment]
Thnaks for that hint! However, there's a lot happening between these two prints. Are you able to compile a new nxagent? If so, it would help if you could activate TEST and DEBUG in `Args.c` and `Screen.c` (and maybe `Init.c` and `Keyboard.c`).

**Comment by Djelff** [comment]
Done, for both 3.5.99.16 and 3.5.99.17 with the NXAGENT_TIMESTAMP key.
P.S. Info: Image rate limit set to 10000 kB / s. and so on, I didn’t remove the experiments with the parameters.

[session.3.5.99.16.txt](https://github.com/ArcticaProject/nx-libs/files/4021856/session.3.5.99.16.txt)
[session.3.5.99.17.txt](https://github.com/ArcticaProject/nx-libs/files/4021857/session.3.5.99.17.txt)

**Comment by Djelff** [comment]
+TEST and DEBUG on Display.c

[session.3.5.99.16.txt](https://github.com/ArcticaProject/nx-libs/files/4021891/session.3.5.99.16.txt)
[session.3.5.99.17.txt](https://github.com/ArcticaProject/nx-libs/files/4021892/session.3.5.99.17.txt)

**Comment by uli42** [comment]
Thank you! Whet we can see is that there a lot more of these:
```
212: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
213: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
214: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
215: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
216: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
217: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
218: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
219: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
220: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
221: nxagentDisplayErrorPredicate: CHECK! Error is [0] with [0][0][0][0][0].
```

That function is called whenever Xlib is going to perform a network operation. So the newer version is producing a lot more network operations than the older one.

I am not sure what is causing them.

Can you please copy the libs (libNX11, libxcomp, libxcomshad) from 3.5.99.16 to the 3.5.99.17 installation (and vice versa) and retry? It would help if we knew where the problem originates from (nxagent or one of the libs).

**Comment by uli42** [comment]
No need to copy the libs. I have identified the problem. We deliver the icon for the main window in xpm format. The code can read it from disk or can use embedded data structures. In 3.5.99.17 the nomachine icon with 16x16px has been replaced by a neutral one in 128x128px (commit 4d6bae082)

Turns out that simply converting this xpm data into a pixmap is VERY expensive via nx transport, in my case around 9s!

As a workaround you can copy the `nxagent.xpm` from 3.5.99.16 to 17. I am not sure of your setup so maybe you need to copy it to a directory in your path. Or simply to the hardcoded path `/usr/NX/share/images/nxagent.xpm`. This should improve startup significantly! Can you confirm?

Update: it looks like it is not the size but the number of colours. Still testing!

**Comment by uli42** [comment]
Fix available in #889

**Comment by Djelff** [comment]
Excellent! Startup speed restored to normal.
About nxagent.xpm I would not have guessed ;(

**Comment by sunweaver** [comment]
Hi,

On  Fr 03 Jan 2020 15:59:40 CET, Djelff wrote:

> The same symptoms: on nx_libs 3.5.99.16 and earlier, after the  
> appearance of the nxclient window in windows, a delay of about 3s  
> passes, on nx_libs 3.5.99.17 and later about 17s
> I have to work through 4g and OpenVPN with an average delay of 85ms.
> The server I'm trying to use is the old/new freenx-server running on  
> the nx-libs libraries, from dimbor-ru https://github.com/dimbor-ru

OT here, but maybe something for personal email...

@Djelff: Could you test a recent remmina release against your  
freenx-server and report back to Remmina upstream, if that is broken  
or still working?
https://gitlab.com/Remmina/Remmina

Thanks+Greets,
Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Djelff** [comment]
I checked and answered the mail to Mike, Remmina on the new FreeNX server using ArcticaProject/nx-libs works.
I think it should work with any client using the FreeNX connection protocol.
https://gyazo.com/f555f929d8097c8d43a5b3a37e02b3bc
