### ISSUE TITLE
Weird colors and image issues on ppc64le Ubuntu 14.04

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#83]
From X2Go BTS:
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=898

Package: nx-libs
Version: 3.5.0.29

After building and installing X2Go packages on Ubuntu 14.04 ppc64le some months
ago, I experienced the following strange behavior(s):
- image colors were distorted sometimes (but sometimes not) - instead of
  brown, pink was shown
- images (PNG? SVG?) didn't load or show correctly. Colors were way off (see
  above) and mostly only contours drawn, if even that.
- scrolling in a scrollview (e.g., XFCE's settings manager(?)) sometimes
  forced a correct redraw of images, but mostly only partitially
- hovering over an image broke it visually again
- mouse cursor either disappeared completely or was replaced with a block
  (what seemed to be random data converted to an image)

I have not done any debugging on these issues yet.

Mihai

**Comment by merseph** [comment]
I see the same issue with incorrect colors with X2GO NX-LIBS on CentOS 7.3.1611-ppc64le.
Grabbed the NX-LIBS SRPM and tried rebuilding. I noticed the compiler directives during the rebuild were -DX_BIG_ENDIAN, even though it's a little endian operating system.. then the rebuild failed.
For comparison, CentOS 7.3.1611-ppc64 (on big endian same code levels) colors are fine.

**Comment by sunweaver** [comment]
Hi,

On  Mo 20 Mär 2017 02:50:34 CET, Merseph wrote:

> I see the same issue with incorrect colors with X2GO NX-LIBS on  
> CentOS 7.3.1611-ppc64le.
> Grabbed the NX-LIBS SRPM and tried rebuilding. I noticed the  
> compiler directives during the rebuild were -DX_BIG_ENDIAN, even  
> though it's a little endian operating system.. then the rebuild  
> failed.

In nx-X11/config/cf/Imake.tmpl there is a line like this:

```
X_BYTE_ORDER = ByteOrder
```

Set it to X_LITTLE_ENDIAN for a test build and then check (a) if your  
build succeeds and (b) if the result is usable regarding colors and  
stuff.


```
X_BYTE_ORDER = X_LITTLE_ENDIAN
```

Thanks for your feedback,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment]
Fixed by f76d4b54118627adb13dd896537c01033d989158.
