### ISSUE TITLE
[abrt] nxagent: GetULONG(): nxagent killed by SIGSEGV

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#85]
Package: nx-libs
Version: 3.5.0.29
#0  GetULONG (buffer=buffer@entry=0x31ff000 <error: Cannot access memory at

address 0x31ff000>, bigEndian=0) at Misc.cpp:518
518     return *((unsigned int *) buffer);

Thread 1 (Thread 0x7fae35376740 (LWP 4320)):
#0  GetULONG (buffer=buffer@entry=0x31ff000 <error: Cannot access memory at

address 0x31ff000>, bigEndian=0) at Misc.cpp:518
        next = <optimized out>
        result = <optimized out>
#1  0x00007fae342b1525 in ClientChannel::handleRead (this=0x27015c0,

encodeBuffer=..., message=<optimized out>, length=<optimized out>) at
ClientChannel.cpp:1220
        numPixels = <optimized out>
        nextSrc = 0x31ff000 <error: Cannot access memory at address 0x31ff000>
        inputOpcode = 88 'X'
        bits = <optimized out>
        inputMessage = 0x28acac0 "X"
        inputLength = 4
        hit = 0
#2  0x00007fae34298284 in Proxy::handleRead (this=0x2182650, fd=<optimized

out>, data=0x1eac1d0 "\213\032\v", size=8160) at Proxy.cpp:1750
        result = <optimized out>
        size = 8160
        data = 0x1eac1d0 "\213\032\v"
        fd = <optimized out>
        this = 0x2182650

-------- Forwarded Message --------
Subject: [Bug 1217630] New: [abrt] nxagent: GetULONG(): nxagent killed by SIGSEGV
Date: Thu, 30 Apr 2015 21:28:13 +0000
From: bugzilla@redhat.com
To: orion@cora.nwra.com

https://bugzilla.redhat.com/show_bug.cgi?id=1217630

```
        Bug ID: 1217630
       Summary: [abrt] nxagent: GetULONG(): nxagent killed by SIGSEGV
       Product: Fedora
       Version: 21
     Component: nx-libs
      Assignee: orion@cora.nwra.com
      Reporter: ruslanpisarev@gmail.com
    QA Contact: extras-qa@fedoraproject.org
            CC: orion@cora.nwra.com
```

Description of problem:
I worked in PyCharm 4.0.4 by x2go. Connection closed unexpected.

Version-Release number of selected component:
nxagent-3.5.0.29-1.fc21

Additional info:
reporter:       libreport-2.3.0
backtrace_rating: 4
cmdline:        /usr/lib64/nx/../x2go/bin/x2goagent -extension XFIXES -nolisten
tcp -nolisten tcp -dpi 96 -D -auth /home/ruslan/.Xauthority -name
X2GO-ruslan-50-1430428104_stDMATE_dp32 :50
crash_function: GetULONG
executable:     /usr/lib64/nx/bin/nxagent
kernel:         3.19.5-200.fc21.x86_64
runlevel:       N 5
type:           CCpp
uid:            1000
var_log_messages: [System Logs]:\n-- Logs begin at Ср 2015-03-04 11:56:00 MSK,
end at Пт 2015-05-01 00:16:33 MSK. --

Truncated backtrace:
Thread no. 1 (10 frames)
 #0 GetULONG at Misc.cpp:518
 #1 ClientChannel::handleRead at ClientChannel.cpp:1220
 #2 Proxy::handleRead at Proxy.cpp:1750
 #3 NXTransWriteVector at Loop.cpp:2276
 #4 _XSend at XlibInt.c:1957
 #5 XRenderCompositeText32 at Glyph.c:1160
 #6 nxagentGlyphs at Render.c:1533
 #7 ProcRenderCompositeGlyphs at X/NXrender.c:1784
 #8 ProcRenderDispatch at X/NXrender.c:2519
 #9 Dispatch at X/NXdispatch.c:748
## 

You are receiving this mail because:
You are on the CC list for the bug.
You are the assignee for the bug.

**Comment by tasleson** [comment]
I look to be hitting this same issue, occurring on F24, nxagent-3.5.0.32-4.fc24.x86_64

```
Core was generated by `/usr/lib64/nx/../x2go/bin/x2goagent -extension XFIXES -nolisten tcp -nolisten t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  GetULONG (buffer=buffer@entry=0x3eabe54 <error: Cannot access memory at address 0x3eabe54>, bigEndian=0) at Misc.cpp:518
518     return *((unsigned int *) buffer);
(gdb) bt
#0  GetULONG (buffer=buffer@entry=0x3eabe54 <error: Cannot access memory at address 0x3eabe54>, bigEndian=0) at Misc.cpp:518
#1  0x00007ff4028d888b in ClientChannel::handleRead (this=0x11bac30, encodeBuffer=..., message=<optimized out>, length=<optimized out>) at ClientChannel.cpp:2549
#2  0x00007ff4028be40a in Proxy::handleRead (this=0xf0c950, fd=<optimized out>, data=data@entry=0x11fb550 "\001", size=size@entry=8192) at Proxy.cpp:1750
#3  0x00007ff402893377 in NXTransWriteVector (fd=<optimized out>, iovdata=0x7ffe399d1720, iovsize=2) at Loop.cpp:2276
#4  0x00007ff4032c2acf in _XSend (dpy=dpy@entry=0xef8d00, data=0x1648d6c "U", size=size@entry=4) at XlibInt.c:1957
#5  0x00007ff40223293c in XRenderCompositeText32 (dpy=0xef8d00, op=op@entry=3, src=<optimized out>, dst=<optimized out>, maskFormat=<optimized out>, xSrc=xSrc@entry=0, ySrc=363, xDst=0, yDst=0, elts=0x1b09ad0, nelt=63)
    at Glyph.c:1160
#6  0x00000000004931df in nxagentGlyphs (op=<optimized out>, pSrc=pSrc@entry=0x1cdf280, pDst=pDst@entry=0x1d6b740, maskFormat=maskFormat@entry=0x0, xSrc=<optimized out>, ySrc=<optimized out>, nlists=63, elts=0x1b09ad0, 
    sizeID=4, glyphsBase=0x7ffe399d1d50) at Render.c:1552
#7  0x0000000000430e03 in ProcRenderCompositeGlyphs (client=0x1b18180) at X/NXrender.c:1784
#8  0x000000000042b27f in ProcRenderDispatch (client=<optimized out>) at X/NXrender.c:2519
#9  0x000000000042a5ca in Dispatch () at X/NXdispatch.c:748
#10 0x000000000040dedf in main (argc=17, argv=0x7ffe399d2ba8, envp=<optimized out>) at main.c:450

```

and

```
Core was generated by `/usr/lib64/nx/../x2go/bin/x2goagent -extension XFIXES -nolisten tcp -nolisten t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  GetULONG (buffer=buffer@entry=0x7da9000 <error: Cannot access memory at address 0x7da9000>, bigEndian=0) at Misc.cpp:518
518     return *((unsigned int *) buffer);
(gdb) bt
#0  GetULONG (buffer=buffer@entry=0x7da9000 <error: Cannot access memory at address 0x7da9000>, bigEndian=0) at Misc.cpp:518
#1  0x00007f84feeb45d4 in ClientChannel::handleRead (this=0x1e7cc30, encodeBuffer=..., message=<optimized out>, length=<optimized out>) at ClientChannel.cpp:1220
#2  0x00007f84fee9a40a in Proxy::handleRead (this=0x1bce950, fd=<optimized out>, data=data@entry=0x1ebd550 "\001", size=size@entry=8192) at Proxy.cpp:1750
#3  0x00007f84fee6f377 in NXTransWriteVector (fd=<optimized out>, iovdata=0x7ffefb5dede0, iovsize=2) at Loop.cpp:2276
#4  0x00007f84ff89eacf in _XSend (dpy=dpy@entry=0x1bbad00, data=0x623eeec "T", size=size@entry=4) at XlibInt.c:1957
#5  0x00007f84fe80e93c in XRenderCompositeText32 (dpy=0x1bbad00, op=op@entry=3, src=<optimized out>, dst=<optimized out>, maskFormat=<optimized out>, xSrc=xSrc@entry=420, ySrc=602, xDst=0, yDst=0, elts=0x399ad20, 
    nelt=49) at Glyph.c:1160
#6  0x00000000004931df in nxagentGlyphs (op=<optimized out>, pSrc=pSrc@entry=0x435e780, pDst=pDst@entry=0x293ef70, maskFormat=maskFormat@entry=0x0, xSrc=<optimized out>, ySrc=<optimized out>, nlists=49, elts=0x399ad20, 
    sizeID=4, glyphsBase=0x7ffefb5df410) at Render.c:1552
#7  0x0000000000430e03 in ProcRenderCompositeGlyphs (client=0x39ab430) at X/NXrender.c:1784
#8  0x000000000042b27f in ProcRenderDispatch (client=<optimized out>) at X/NXrender.c:2519
#9  0x000000000042a5ca in Dispatch () at X/NXdispatch.c:748
#10 0x000000000040dedf in main (argc=17, argv=0x7ffefb5e0268, envp=<optimized out>) at main.c:450
```

**Comment by uli42** [comment]
I tend to close this as we are way gone from 3.5.0 nx packages. Also nx 3.5.99 releases are running extremly stable...

**Comment by sunweaver** [comment]
Am Mittwoch, 15. Januar 2020 schrieb Ulrich Sibiller:
> I tend to close this as we are way gone from 3.5.0 nx packages. Also nx 3.5.99 releases are running extremly stable...
> 

ok, please close this, then.

Mike

-- 
Gesendet von meinem Sailfish Gerät
