### ISSUE TITLE
Terminating a Fullscreen Shadow Session on Linux is Clumsy

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#89]
From X2Go BTS:
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=846
package: nxagent

Currently, there doesn't seem to be a way to cleanly terminate a
shadow session running in fullscreen mode.

Ctrl-Alt-T doesn't work, Alt-Tab gets sent to the remote end, so one
can only run x2goterminatesession on the remote end or kill the
x2goclient task on the local side.

**Comment by uli42** [comment]
I guess ctrl-alt-t will work if there's a nxclient binary in the path.

**Comment by sunweaver** [comment]
It will be covered by a potential fix for #442 (suspend and terminate nxagent via separate keystrokes).

Thus closing, and adding the above demand as a note to #442.
