### ISSUE TITLE
fullscreen on single screen not configurable

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#923]
nxagent knows `-geometry fullscreen` (cmdline) and `fullscreen=1` (options file). Both work but will open a fullscreen session covering all screens. There's no option to restrict that to a single screen like with the relevant keystrokes. 

So let's support `fullscreen=2` meaning "only span one screen"

For the command line options we could use `-geometry singlescreen`.

Comments?

**Comment by sunweaver** [comment]
Hi Uli,

Am Mittwoch, 6. Mai 2020 schrieb Ulrich Sibiller:
> nxagent knows `-geometry fullscreen` (cmdline) and `fullscreen=1` (options file). Both work but will open a fullscreen session covering all screens. There's no option to restrict that to a single screen like with the relevant keystrokes. 
> 
> So let's support `fullscreen=2` meaning "only span on screen"
> 
> For the command line options we could use `-geometry singlescreen`.
> 
> Comments?
> 

Sounds like a plan...

Mike

-- 
Gesendet von meinem Sailfish Gerät

**Comment by uli42** [comment]
For the records: my patch implements
- commandline `-geometry singlescreen`
- commandline `-geometry allscreens` (synonym to `-geometry fullscreen`)
- options file: `fullscreen=0/1/2`
