### ISSUE TITLE
mutter resize bug

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#925]
(post from x2go-user mailing list by Kees Bakker, https://lists.x2go.org/pipermail/x2go-user/2020-May/thread.html)

```
Hi,

The client shows a weird resizing bug. I want to know what I can do to
analyse this further and report it as a bug.
I've mentioned this already earlier on the [X2Go-User] mailing list [1].

I'm surprised that I'm the only one seeing this, because I see it on all
the environments that I work on. That is,
on all PCs where I am logged in with the standard Ubuntu desktop.

My client is Ubuntu (with Ubuntu desktop) and the server side is Ubuntu
with a Mate (or Openbox or XFCE) session.
Also worthwhile to mention that I don't have my x2go client full screen.

When I move(!) the X2GO window, it resizes(!). And when I keep the mouse
clicked on the top bar for the move,
(and even if I don't move anymore) it keeps resizing until it reaches
the maximum height of my local monitor.
BTW. That maximum monitor height is not(!) the maximum height of my
local window manager. The maximum
height for the X2GO client window is the monitor height minus the height
of the top bar.

What I also noticed is that the height increments in steps of 37 pixels.
I'm not sure, but I think the the height
of the top bar in the Ubuntu desktop is 37.

Here are the last few lines of the remote session.log. I start with a
session of 800x600
Info: Screen [0] resized to geometry [799x600] fullscreen [0].
Info: Screen [0] resized to geometry [799x674] fullscreen [0].
Info: Screen [0] resized to geometry [798x674] fullscreen [0].
Info: Screen [0] resized to geometry [798x711] fullscreen [0].
Info: Screen [0] resized to geometry [797x711] fullscreen [0].
Info: Screen [0] resized to geometry [797x748] fullscreen [0].
Info: Screen [0] resized to geometry [796x748] fullscreen [0].
Info: Screen [0] resized to geometry [796x748] fullscreen [0].

Kind regards,
Kees Bakker

[1] https://lists.x2go.org/pipermail/x2go-user/2020-April/005936.html
```

Later Michael Ashley reported he also sees this:
```
Just to let you know that I also see the resizing bug, and have for a year (?) or so. It drives me up the wall! My client is on Ubuntu 18.04 desktop, X2Go Client v. 4.1.1.1 (Qt - 5.9.5).
```

(see https://lists.x2go.org/pipermail/x2go-user/2020-May/006004.html for the whole thread)

**Comment by uli42** [comment]
I managed to replicate the problem after switching to mutter window manager (3.30.2-9~deb10u1 amd64 on debian Buster).

**Comment by uli42** [comment]
Some more information:

If you look at the nxagent window with `xprop` when mutter is the WM you see this property:
```
...
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, <value>, 0
...
```

<value> is exactly the value the window grows vertically.

I have looked at the code and it _seems_ that we get a ConfigureNotify event informing us about the new window size of the so-called root window and then run XResizeWindow() on the so-called default window. Which normally works because they are the same size. But with mutter the root window also contains the title bar and therefore is bigger. So the default window is resized using the wrong (outer) height. Which results in vertical growth. Unfortunately at the location where that resize happens there's no information about the ConfigureNotify event anymore so we do not know where the size informing is coming from. So we cannot simply check for the right window here and act accordingly.

I am still thinking how a fix could fit in the current code.

**Comment by keestux** [comment]
In a working situation (non-mutter), I get something like this
```
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 28, 1
```

**Comment by uli42** [comment]
Yeah, and probably that WM als draws small borders around the window.
Which mutter does not. So everything is correct.

**Comment by uli42** [comment]
Unfortunately the fix I have is still not covering all cases with mutter:

1. start a windowed session
2. press ctrl-alt-f (switch_all_screens) several times.
3. press ctrl-alt-shift-f (fullscreen) several times.

I see wrong window placements in 3. but not in 2. I addition I see the old wrong vertical window growing after the step 2 or step 3 has been executed.
