### ISSUE TITLE
Remote Icedove kills X2Go client on MacOSX and Windows

### ISSUE THREAD

**Issue by sebastiendu** [ArcticaProject/nx-libs#94]
To reproduce : Debian 7 or 8 as X2Go server, MacOSX or Windows as client.

Open an XFCE session, all works fine until you start Icedove. It kills the X2Go client.

Debian and Ubuntu versions of X2Go client are not affected.

No other application caused this bug as far as I know.

**Comment by uli42** [comment]
On Sun, Feb 28, 2016 at 8:09 PM, Sébastien notifications@github.com wrote:

> To reproduce : Debian 7 or 8 as X2Go server, MacOSX or Windows as client.
> 
> Open an XFCE session, all works fine until you start Icedove. It kills the X2Go client.
> 
> Debian and Ubuntu versions of X2Go client are not affected.
> 
> No other application caused this bug as far as I know.

Does this also happen when you run Icedove like this:

  export MOZ_DISABLE_IMAGE_OPTIMIZE=1
  icedove

(see also: http://multivax.blogspot.de/2010/08/firefox-memory-management-nightmare.html)

Uli

**Comment by sunweaver** [comment]
@sebastiendu: Can you please grab the 3.6.x branch of nx-libs, build it on your X2Go Server and replace the 3.5.x version of nx-libs from X2Go with the packages derived from the 3.6.x source tree?

You can also obtain pre-built binaries of 3.6.x nx-libs packages as described here:
https://sunweavers.net/blog/node/20

**Comment by sebastiendu** [comment]
I installed the pre-built binaries of 3.6.x nx-libs packages on our server.
It fixed the issue on MacOSX at least. I am waiting for more feedback from users.

**Comment by sunweaver** [comment]
@sebastiendu: any more feedback on your nxagent crashes caused by Icedove? Thanks for feedback.

**Comment by sebastiendu** [comment]
Ok I just got feedback from the other user, who does not use X2Go so often. The bug does not occur anymore with the new libs, server-side.
